- updated netperf_ scripts to use scls if possible

diff --git a/netperf/netperf_arr b/netperf/netperf_arr
--- a/netperf/netperf_arr
+++ b/netperf/netperf_arr
@@ -240,7 +240,7 @@ function help()
     cat <<EOF
 Arguments:
     HOSTNAME
-        name of remote host [Default: $default_hostname]
+	name of remote host [Default: $default_hostname]
     CPU
 	calibrate CPU [Default: $default_calibrate]
 Options:
@@ -251,7 +251,7 @@ Options:
     -H, --hostname=HOSTNAME[:PORT]
 	add a name or address to the netserver host list
     -l, --hostnames='HOSTNAME[:PORT][ HOSTNAME[:PORT]]*'
-        names or addresses of netserver hosts [Default: $default_hostnames]
+	names or addresses of netserver hosts [Default: $default_hostnames]
     -n, --numproc=NUMPROC
 	add a processor number to the list
     -N, --numprocs='NUMPROC[ NUMPROC]*'
@@ -624,8 +624,8 @@ esac
 
 args=($nonopt${nonopt:+ }${1+$@})
 
-if test "$verbose" -gt 2 ; then
-$ECHO "Nonoption arguments: ${args[@]}"
+if test "$verbose" -gt 3 ; then
+    $ECHO "Nonoption arguments: ${args[@]}"
 fi
 
 while test "${#args[@]}" -gt 0
@@ -684,12 +684,39 @@ done
 
 function netperf_options()
 {
-    if test ${verbose:-1} -gt 2 ; then
+    if test ${verbose:-1} -gt 3 ; then
 	for arg in $defaults ; do
 	    val=`eval 'echo $'"$arg"`
 	    $ECHO "Option $arg is \`$val'"
 	done
+	$ECHO
     fi
+}
+
+function scls_find()
+{
+    scls=`which scls 2>/dev/null`
+    pname=`$ECHO "$scls" | $SED -e 's%^.*/%%'`
+    if test ":$pname" = ":scls" ; then
+	return
+    fi
+    if test -x "$scls" ; then
+	return
+    fi
+    # scls is not in our path, check elsewhere
+    scls=`whereis scls 2>/dev/null`
+    scls=`$ECHO "$scls" | $SED -e 's%^scls:[[:space:]]*%%;s%[[:space:]].*%%'`
+    pname=`$ECHO "$scls" | $SED -e 's%^.*/%%'`
+    if test ":$pname" = ":scls" ; then
+	return
+    fi
+    if test -x "$scls" ; then
+	return
+    fi
+    if test ${verbose:-1} -gt 0 ; then
+	$ECHO "$program: warning -- cannot find scls executable" >&2
+    fi
+    scls=scls
 }
 
 function netperf_find()
@@ -781,6 +808,52 @@ function netperf_calibrate()
     fi
 }
 
+function scls_show()
+{
+    if test ${verbose:-1} -le 1 ; then
+	return
+    fi
+    if test :${xti:-no} = :no ; then
+	return
+    fi
+    scls_modules="sth timod"
+    if test :${device:-/dev/udp} = :/dev/udp ; then
+	scls_modules="$scls_modules inet"
+    fi
+    if test :${device:-/dev/udp} = :/dev/udp2 ; then
+	scls_modules="$scls_modules udp2"
+    fi
+    if test :${device:-/dev/tcp} = :/dev/tcp ; then
+	scls_modules="$scls_modules inet"
+    fi
+    if test :${device:-/dev/tcp} = :/dev/tcp2 ; then
+	scls_modules="$scls_modules tcp2"
+    fi
+    if test :${device:-/dev/sctp} = :/dev/sctp ; then
+	scls_modules="$scls_modules sctp"
+    fi
+    if test :${device:-/dev/sctp} = :/dev/sctp2 ; then
+	scls_modules="$scls_modules sctp2"
+    fi
+    if test ${verbose:-1} -gt 2 ; then
+	scls_options="-b -a"
+    else
+	scls_options="-c -a"
+    fi
+    if test ${verbose:-1} -gt 2 ; then
+	$ECHO "STREAMS statistics"
+	$ECHO
+	$ECHO "------------------------------------"
+    fi
+    if test ${verbose:-1} -gt 1 ; then
+	$ECHO "$scls $scls_options $scls_modules"
+    fi
+    if test :${run:-yes} != :no ; then
+	$scls $scls_options $scls_modules
+    fi
+    $ECHO
+}
+
 procsarray=($numprocs)
 
 function netperf_rr_tests()
@@ -814,6 +887,7 @@ function netperf_rr_tests()
 		if test :${run:-yes} != :no ; then
 		    $netperf ${port:+-p }$port $stats $headers -l $testtime -t $testcase -H $host $calibration -- -r $rrsize $device &
 		fi
+		scls_show
 		if test ${verbose:-1} -gt 0 ; then
 		    $ECHO
 		    $ECHO
@@ -860,10 +934,11 @@ function netperf_lla_tests()
 function netperf_test()
 {
     if test ${verbose:-1} -gt 0 ; then
-	$ECHO "Netperf arr script started at `date`"
+	$ECHO "Netperf $program script started at `date`"
 	$ECHO
     fi
     netperf_calibrate
+    scls_show
     netperf_sctp_tests
     netperf_tcp_tests
     netperf_udp_tests
@@ -889,6 +964,7 @@ function run_command()
     netperf_copying
     netperf_options
     netperf_find
+    scls_find
     if test "${verbose:-1}" -gt 1 ; then
 	((verb=$verbose-1))
 	verb="-v $verb"
diff --git a/netperf/netperf_packet_byte b/netperf/netperf_packet_byte
--- a/netperf/netperf_packet_byte
+++ b/netperf/netperf_packet_byte
@@ -181,6 +181,7 @@ default_verbose=1
 default_run=yes
 
 default_netperf=${NETPERF_CMD:=netperf}
+default_calibrate=no
 default_testtime=${NETPERF_TIME:=20}
 default_port=${NETPERF_PORT:=}
 default_bufsizes=${NETPERF_SKTS:='32768'}
@@ -192,7 +193,7 @@ default_headers='-P 0'
 default_calibrate=no
 default_rrsizes='1,1 16,16 32,32 64,64 128,128 256,256 512,512 1024,1024, 1460,1460 2920,2920 2921,2921 4380,4380 4381,4381'
 
-defaults='command debug verbose run netperf testtime port hostname device xti stats headers calibrate bufsizes rrsizes'
+defaults='command debug verbose run netperf calibrate testtime port hostname device xti stats headers calibrate bufsizes rrsizes'
 
 function version()
 {
@@ -233,16 +234,16 @@ function help()
     cat <<EOF
 Arguments:
     HOSTNAME
-        name of remote host [Default: $default_hostname]
+	name of remote host [Default: $default_hostname]
     CPU
 	calibrate CPU [Default: $default_calibrate]
 Options:
     -c, --calibrate
 	calibrate CPU [Default: $default_calibrate]
     -H, --hostname=HOSTNAME
-        name or address of netserver host [Default: $default_hostname]
+	name or address of netserver host [Default: $default_hostname]
     -p, --port=PORTNUM
-        netserver port number [Default: ${default_port:-12865}]
+	netserver port number [Default: ${default_port:-12865}]
     -t, --testtime=SECONDS
 	duration of each test in seconds [Default: $default_testtime]
     -b, --bufsize=SIZE
@@ -407,6 +408,7 @@ do
 	--debug=* | --debu=* | --deb=* | --de=* | --d=* | \
 	--verbose=* | --verbos=* | --verbo=* | --verb=* | \
 	--port=* | --por=* | --po=* | --p=* | \
+	--xti=* | --xt=* | --x=* | \
 	--hostname=* | --hostnam=* | --hostna=* | --hostn=* | --host=* | --hos=* | --ho=* | --h=* | \
 	--testtime=* | --testime=* | --testtim=* | --testim=* | --time=* | --t=* | \
 	--bufsizes=* | --bufsize=* | --bufsiz=* | --bufsi=* | --bufs=* | --buf=* | --bu=* | --b=* | \
@@ -458,118 +460,67 @@ do
     # Have we seen a non-optional argument yet?
     case $arg in
 	--help | --h | --\? | -h | -\?)
-	    show_help=yes
-	    if test ":$command" = ":" ; then command=none ; fi
-	    ;;
+	    show_help=yes ; if test ":$command" = ":" ; then command=none ; fi ;;
 	--version | --versio | --versi | --vers | -V)
-	    show_version=yes
-	    if test ":$command" = ":" ; then command=none ; fi
-	    ;;
+	    show_version=yes ; if test ":$command" = ":" ; then command=none ; fi ;;
 	--copying | --copyin | --copyi | --copy | --cop | --co | --c | -C)
-	    show_copying=yes
-	    if test ":$command" = ":" ; then command=none ; fi
-	    ;;
+	    show_copying=yes ; if test ":$command" = ":" ; then command=none ; fi ;;
 	--verbose | --verbos | --verbo | --verb)
-	    prevopt="$arg"
-	    prev=verbose
-	    ;;
+	    prevopt="$arg" ; prev=verbose ;;
 	-v)
-	    ((verbose++))
-	    ;;
+	    ((verbose++)) ;;
 	--verbose=* | --verbos=* | --verbo=* | --verb=*)
-	    verbose="$optarg"
-	    ;;
+	    verbose="$optarg" ;;
 	--debug | --debu | --deb)
-	    prevopt="$arg"
-	    prev=debug
-	    ;;
+	    prevopt="$arg" ; prev=debug ;;
 	-D)
-	    $ECHO "$program: enabling shell trace mode" 1>&2
-	    set -x
-	    ;;
+	    $ECHO "$program: enabling shell trace mode" 1>&2 ; set -x ;;
 	--debug=* | --debu=* | --deb=*)
-	    debug="$optarg"
-	    ;;
+	    debug="$optarg" ;;
 	--dry-run | --dryrun | --n | -n)
-	    run=no
-	    ;;
+	    run=no ;;
 	--quiet | --silent | -q)
-	    show=no
-	    verbose=0
-	    debug=0
-	    ;;
+	    show=no ; verbose=0 ; debug=0 ;;
 	--port | --por | --po | --p | -p)
-	    prevopt=$arg
-	    prev=port
-	    ;;
+	    prevopt=$arg ; prev=port ;;
 	--port=* | --por=* | --po=* | --p=* | -p*)
-	    port="$optarg"
-	    ;;
+	    port="$optarg" ;;
 	--testtime | --testime | --testtim | --testim | --time | --t | -t)
-	    prevopt="$arg"
-	    prev=testtime
-	    ;;
+	    prevopt="$arg" ; prev=testtime ;;
 	--testtime=* | --testime=* | --testtim=* | --testim=* | --time=* | --t=* | -t*)
-	    testtime="$optarg"
-	    ;;
+	    testtime="$optarg" ;;
 	--hostname | --hostnam | --hostna | --hostn | --host | --hos | --ho | --h | -H)
-	    prevopt="$arg"
-	    prev=hostname
-	    ;;
+	    prevopt="$arg" ; prev=hostname ;;
 	--hostname=* | --hostnam=* | --hostna=* | --hostn=* | --host=* | --hos=* | --ho=* | --h=* | -H*)
-	    hostname="$optarg"
-	    ;;
+	    hostname="$optarg" ;;
 	--bufsize | --bufsiz | --bufsi | --bufs | --buf | --bu | --b | -b)
-	    prevopt="$arg"
-	    prev=bufsize
-	    ;;
+	    prevopt="$arg" ; prev=bufsize ;;
 	--bufsize=* | --bufsiz=* | --bufsi=* | --bufs=* | --buf=* | --bu=* | --b=* | -b*)
-	    bufsizes="$bufsizes${bufsizes:+ }$optarg"
-	    ;;
+	    bufsizes="$bufsizes${bufsizes:+ }$optarg" ;;
 	--bufsizes | -B)
-	    prevopt="$arg"
-	    prev=bufsizes
-	    ;;
+	    prevopt="$arg" ; prev=bufsizes ;;
 	--bufsizes=* | -B*)
-	    bufsizes="$optarg"
-	    ;;
+	    bufsizes="$optarg" ;;
 	--rrsize | --rrsiz | --rrsi | --rrs | --rr | --r | -r)
-	    prevopt="$arg"
-	    prev=rrsize
-	    ;;
+	    prevopt="$arg" ; prev=rrsize ;;
 	--rrsize=* | --rrsiz=* | --rrsi=* | --rrs=* | --rr=* | --r=* | -r*)
-	    rrsizes="$rrsizes${rrsizes:+ }$optarg"
-	    ;;
+	    rrsizes="$rrsizes${rrsizes:+ }$optarg" ;;
 	--rrsizes | -R)
-	    prevopt="$arg"
-	    prev=rrsizes
-	    ;;
+	    prevopt="$arg" ; prev=rrsizes ;;
 	--rrsizes=* | -R*)
-	    rrsizes="$optarg"
-	    ;;
+	    rrsizes="$optarg" ;;
 	--calibrate | --calibrat | --calibra | --calibr | --calib | --cali | --cal | --ca | --c | -c)
-	    calibrate=yes
-	    ;;
+	    calibrate=yes ;;
 	--xti | --xt | --x | -x)
-	    xti=yes
-	    prevopt="$arg"
-	    prev=device
-	    ;;
+	    xti=yes ; prevopt="$arg" ; prev=device ;;
 	--xti=* | --xt=* | --x=* | -x*)
-	    xti=yes
-	    device="$optarg"
-	    ;;
-	--)
-	    # end of options
-	    more_options=no
-	    ;;
+	    xti=yes ; device="$optarg" ;;
+	--) # end of options
+	    more_options=no ;;
 	-* | \+*)
-	    option_unrec $arg
-	    ;;
-	*)
-	    # permute all non-options to the end
-	    nonopt="${nonopt}${nonopt:+ }$arg"
-	    ;;
+	    option_unrec $arg ;;
+	*)  # permute all non-options to the end
+	    nonopt="${nonopt}${nonopt:+ }$arg" ;;
     esac
 done
 
@@ -604,6 +555,8 @@ for def in $defaults ; do
     val=`eval 'echo $'"$def"`
     if test :${val:+set} != :set ; then
 	eval "$def=\$default_$def"
+    else
+	eval "$def=\"\$val\""
     fi
 done
 
@@ -620,6 +573,32 @@ function netperf_options()
 	done
 	$ECHO
     fi
+}
+
+function scls_find()
+{
+    scls=`which scls 2>/dev/null`
+    pname=`$ECHO "$scls" | $SED -e 's%^.*/%%'`
+    if test ":$pname" = ":scls" ; then
+	return
+    fi
+    if test -x "$scls" ; then
+	return
+    fi
+    # scls is not in our path, check elsewhere
+    scls=`whereis scls 2>/dev/null`
+    scls=`$ECHO "$scls" | $SED -e 's%^scls:[[:space:]]*%%;s%[[:space:]].*%%'`
+    pname=`$ECHO "$scls" | $SED -e 's%^.*/%%'`
+    if test ":$pname" = ":scls" ; then
+	return
+    fi
+    if test -x "$scls" ; then
+	return
+    fi
+    if test ${verbose:-1} -gt 0 ; then
+	$ECHO "$program: warning -- cannot find scls executable" >&2
+    fi
+    scls=scls
 }
 
 function netperf_find()
@@ -711,6 +690,52 @@ function netperf_calibrate()
     fi
 }
 
+function scls_show()
+{
+    if test ${verbose:-1} -le 1 ; then
+	return
+    fi
+    if test :${xti:-no} = :no ; then
+	return
+    fi
+    scls_modules="sth timod"
+    if test :${device:-/dev/udp} = :/dev/udp ; then
+	scls_modules="$scls_modules inet"
+    fi
+    if test :${device:-/dev/udp} = :/dev/udp2 ; then
+	scls_modules="$scls_modules udp2"
+    fi
+    if test :${device:-/dev/tcp} = :/dev/tcp ; then
+	scls_modules="$scls_modules inet"
+    fi
+    if test :${device:-/dev/tcp} = :/dev/tcp2 ; then
+	scls_modules="$scls_modules tcp2"
+    fi
+    if test :${device:-/dev/sctp} = :/dev/sctp ; then
+	scls_modules="$scls_modules sctp"
+    fi
+    if test :${device:-/dev/sctp} = :/dev/sctp2 ; then
+	scls_modules="$scls_modules sctp2"
+    fi
+    if test ${verbose:-1} -gt 2 ; then
+	scls_options="-b -a"
+    else
+	scls_options="-c -a"
+    fi
+    if test ${verbose:-1} -gt 2 ; then
+	$ECHO "STREAMS statistics"
+	$ECHO
+	$ECHO "------------------------------------"
+    fi
+    if test ${verbose:-1} -gt 1 ; then
+	$ECHO "$scls $scls_options $scls_modules"
+    fi
+    if test :${run:-yes} != :no ; then
+	$scls $scls_options $scls_modules
+    fi
+    $ECHO
+}
+
 function netperf_tcp_test_rr()
 {
     save_headers="$headers"
@@ -780,6 +805,7 @@ function netperf_tcp_test_rr()
 	if test :${run:-yes} != :no ; then
 	    $netperf ${port:+-p }$port $stats $headers -l $testtime -t $testcase -H $hostname $calibration -- -r $rrsize -s $1 -S $1 $tcpdev
 	fi
+	scls_show
 	headers='-P 0'
     done
     if test ${verbose:-1} -gt 0 ; then
@@ -806,6 +832,7 @@ function netperf_tcp_test_crr()
     if test :${run:-yes} != :no ; then
 	$netperf ${port:+-p }$port $stats $headers -l $testtime -t $testcase -H $hostname $calibration -- -s $1 -S $1 $tcpdev
     fi
+    scls_show
     if test ${verbose:-1} -gt 0 ; then
 	$ECHO
     fi
@@ -818,6 +845,7 @@ function netperf_test()
 	$ECHO
     fi
     netperf_calibrate
+    scls_show
     for bufsize in $bufsizes ; do
 	netperf_tcp_test_rr $bufsize
 	netperf_tcp_test_crr $bufsize
@@ -844,6 +872,7 @@ function run_command()
     netperf_copying
     netperf_options
     netperf_find
+    scls_find
     if test "${verbose:-1}" -gt 1 ; then
 	((verb=$verbose-1))
 	verb="-v $verb"
diff --git a/netperf/netperf_sctp_range b/netperf/netperf_sctp_range
--- a/netperf/netperf_sctp_range
+++ b/netperf/netperf_sctp_range
@@ -184,6 +184,7 @@ default_verbose=1
 default_run=yes
 
 default_netperf=${NETPERF_CMD:=netperf}
+default_calibrate=no
 default_testtime=${NETPERF_TIME:=60}
 default_port=${NETPERF_PORT:=}
 default_bufsizes=${NETPERF_SKTS:='32768'}
@@ -198,7 +199,7 @@ default_sndend=65536
 default_sndadd=0
 default_sndmult=4
 
-defaults='command debug verbose run netperf testtime port hostname device xti stats headers calibrate bufsizes sndstart sndend sndadd sndmult'
+defaults='command debug verbose run netperf calibrate testtime port hostname device xti stats headers calibrate bufsizes sndstart sndend sndadd sndmult'
 
 function version()
 {
@@ -239,22 +240,22 @@ function help()
     cat <<EOF
 Arguments:
     HOSTNAME
-        name of remote host [Default: $default_hostname]
+	name of remote host [Default: $default_hostname]
     CPU
 	calibrate CPU [Default: $default_calibrate]
 Options:
     -c, --calibrate
 	calibrate CPU [Default: $default_calibrate]
     -H, --hostname=HOSTNAME
-        name or address of netserver host [Default: $default_hostname]
+	name or address of netserver host [Default: $default_hostname]
     -p, --port=PORTNUM
-        netserver port number [Default: ${default_port:-12865}]
+	netserver port number [Default: ${default_port:-12865}]
     -t, --testtime=SECONDS
 	duration of each test in seconds [Default: $default_testtime]
     -b, --bufsize=SIZE
 	add an additional buffer size to the list
     -B, --bufsizes='SIZE[ SIZE]*'
-        specify the list of buffer sizes to test [Default: '$default_bufsizes']
+	specify the list of buffer sizes to test [Default: '$default_bufsizes']
     -s, --start=SIZE
 	send size at which to start test [Default: $default_sndstart]
     -e, --end=SIZE
@@ -417,6 +418,7 @@ do
 	--debug=* | --debu=* | --deb=* | --de=* | --d=* | \
 	--verbose=* | --verbos=* | --verbo=* | --verb=* | \
 	--port=* | --por=* | --po=* | --p=* | \
+	--xti=* | --xt=* | --x=* | \
 	--hostname=* | --hostnam=* | --hostna=* | --hostn=* | --host=* | --hos=* | --ho=* | --h=* | \
 	--testtime=* | --testime=* | --testtim=* | --testim=* | --time=* | --t=* | \
 	--bufsizes=* | --bufsize=* | --bufsiz=* | --bufsi=* | --bufs=* | --buf=* | --bu=* | --b=* | \
@@ -469,132 +471,75 @@ do
     # Have we seen a non-optional argument yet?
     case $arg in
 	--help | --h | --\? | -h | -\?)
-	    show_help=yes
-	    if test ":$command" = ":" ; then command=none ; fi
-	    ;;
+	    show_help=yes ; if test ":$command" = ":" ; then command=none ; fi ;;
 	--version | --versio | --versi | --vers | -V)
-	    show_version=yes
-	    if test ":$command" = ":" ; then command=none ; fi
-	    ;;
+	    show_version=yes ; if test ":$command" = ":" ; then command=none ; fi ;;
 	--copying | --copyin | --copyi | --copy | --cop | --co | --c | -C)
-	    show_copying=yes
-	    if test ":$command" = ":" ; then command=none ; fi
-	    ;;
+	    show_copying=yes ; if test ":$command" = ":" ; then command=none ; fi ;;
 	--verbose | --verbos | --verbo | --verb)
-	    prevopt="$arg"
-	    prev=verbose
-	    ;;
+	    prevopt="$arg" ; prev=verbose ;;
 	-v)
-	    ((verbose++))
-	    ;;
+	    ((verbose++)) ;;
 	--verbose=* | --verbos=* | --verbo=* | --verb=*)
-	    verbose="$optarg"
-	    ;;
+	    verbose="$optarg" ;;
 	--debug | --debu | --deb)
-	    prevopt="$arg"
-	    prev=debug
-	    ;;
+	    prevopt="$arg" ; prev=debug ;;
 	-D)
-	    $ECHO "$program: enabling shell trace mode" 1>&2
-	    set -x
-	    ;;
+	    $ECHO "$program: enabling shell trace mode" 1>&2 ; set -x ;;
 	--debug=* | --debu=* | --deb=*)
-	    debug="$optarg"
-	    ;;
+	    debug="$optarg" ;;
 	--dry-run | --dryrun | --n | -n)
-	    run=no
-	    ;;
+	    run=no ;;
 	--quiet | --silent | -q)
-	    show=no
-	    verbose=0
-	    debug=0
-	    ;;
+	    show=no ; verbose=0 ; debug=0 ;;
 	--port | --por | --po | --p | -p)
-	    prevopt=$arg
-	    prev=port
-	    ;;
+	    prevopt=$arg ; prev=port ;;
 	--port=* | --por=* | --po=* | --p=* | -p*)
-	    port="$optarg"
-	    ;;
+	    port="$optarg" ;;
 	--testtime | --testime | --testtim | --testim | --time | --t | -t)
-	    prevopt="$arg"
-	    prev=testtime
-	    ;;
+	    prevopt="$arg" ; prev=testtime ;;
 	--testtime=* | --testime=* | --testtim=* | --testim=* | --time=* | --t=* | -t*)
-	    testtime="$optarg"
-	    ;;
+	    testtime="$optarg" ;;
 	--hostname | --hostnam | --hostna | --hostn | --host | --hos | --ho | --h | -H)
-	    prevopt="$arg"
-	    prev=hostname
-	    ;;
+	    prevopt="$arg" ; prev=hostname ;;
 	--hostname=* | --hostnam=* | --hostna=* | --hostn=* | --host=* | --hos=* | --ho=* | --h=* | -H*)
-	    hostname="$optarg"
-	    ;;
+	    hostname="$optarg" ;;
 	--bufsize | --bufsiz | --bufsi | --bufs | --buf | --bu | --b | -b)
-	    prevopt="$arg"
-	    prev=bufsize
-	    ;;
+	    prevopt="$arg" ; prev=bufsize ;;
 	--bufsize=* | --bufsiz=* | --bufsi=* | --bufs=* | --buf=* | --bu=* | --b=* | -b*)
-	    bufsizes="$bufsizes${bufsizes:+ }$optarg"
-	    ;;
+	    bufsizes="$bufsizes${bufsizes:+ }$optarg" ;;
 	--bufsizes | -B)
-	    prevopt="$arg"
-	    prev=bufsizes
-	    ;;
+	    prevopt="$arg" ; prev=bufsizes ;;
 	--bufsizes=* | -B*)
-	    bufsizes="$optarg"
-	    ;;
+	    bufsizes="$optarg" ;;
 	--start | --star | --sta | --st | --s | -s)
-	    prevopt="$arg"
-	    prev=sndstart
-	    ;;
+	    prevopt="$arg" ; prev=sndstart ;;
 	--start=* | --star=* | --sta=* | --st=* | --s=* | -s*)
-	    sndstart="$optarg"
-	    ;;
+	    sndstart="$optarg" ;;
 	--end | --en | --e | -e)
-	    prevopt="$arg"
-	    prev=sndend
-	    ;;
+	    prevopt="$arg" ; prev=sndend ;;
 	--end=* | --en=* | --e=* | -e*)
-	    sndend="$optarg"
-	    ;;
+	    sndend="$optarg" ;;
 	--add | --ad | --a | -a)
-	    prevopt="$arg"
-	    prev=sndadd
-	    ;;
+	    prevopt="$arg" ; prev=sndadd ;;
 	--add=* | --ad=* | --a=* | -a*)
-	    sndadd="$optarg"
-	    ;;
+	    sndadd="$optarg" ;;
 	--mult | --mul | --mu | --m | -m)
-	    prevopt="$arg"
-	    prev=sndmult
-	    ;;
+	    prevopt="$arg" ; prev=sndmult ;;
 	--mult=* | --mul=* | --mu=* | --m=* | -m*)
-	    sndmult="$optarg"
-	    ;;
+	    sndmult="$optarg" ;;
 	--calibrate | --calibrat | --calibra | --calibr | --calib | --cali | --cal | --ca | --c | -c)
-	    calibrate=yes
-	    ;;
+	    calibrate=yes ;;
 	--xti | --xt | --x | -x)
-	    xti=yes
-	    prevopt="$arg"
-	    prev=device
-	    ;;
+	    xti=yes ; prevopt="$arg" ; prev=device ;;
 	--xti=* | --xt=* | --x=* | -x*)
-	    xti=yes
-	    device="$optarg"
-	    ;;
-	--)
-	    # end of options
-	    more_options=no
-	    ;;
+	    xti=yes ; device="$optarg" ;;
+	--) # end of options
+	    more_options=no ;;
 	-* | \+*)
-	    option_unrec $arg
-	    ;;
-	*)
-	    # permute all non-options to the end
-	    nonopt="${nonopt}${nonopt:+ }$arg"
-	    ;;
+	    option_unrec $arg ;;
+	*)  # permute all non-options to the end
+	    nonopt="${nonopt}${nonopt:+ }$arg" ;;
     esac
 done
 
@@ -629,6 +574,8 @@ for def in $defaults ; do
     val=`eval 'echo $'"$def"`
     if test :${val:+set} != :set ; then
 	eval "$def=\$default_$def"
+    else
+	eval "$def=\"\$val\""
     fi
 done
 
@@ -645,6 +592,32 @@ function netperf_options()
 	done
 	$ECHO
     fi
+}
+
+function scls_find()
+{
+    scls=`which scls 2>/dev/null`
+    pname=`$ECHO "$scls" | $SED -e 's%^.*/%%'`
+    if test ":$pname" = ":scls" ; then
+	return
+    fi
+    if test -x "$scls" ; then
+	return
+    fi
+    # scls is not in our path, check elsewhere
+    scls=`whereis scls 2>/dev/null`
+    scls=`$ECHO "$scls" | $SED -e 's%^scls:[[:space:]]*%%;s%[[:space:]].*%%'`
+    pname=`$ECHO "$scls" | $SED -e 's%^.*/%%'`
+    if test ":$pname" = ":scls" ; then
+	return
+    fi
+    if test -x "$scls" ; then
+	return
+    fi
+    if test ${verbose:-1} -gt 0 ; then
+	$ECHO "$program: warning -- cannot find scls executable" >&2
+    fi
+    scls=scls
 }
 
 function netperf_find()
@@ -736,6 +709,37 @@ function netperf_calibrate()
     fi
 }
 
+function scls_show()
+{
+    if test ${verbose:-1} -le 1 ; then
+	return
+    fi
+    if test :${xti:-no} = :no ; then
+	return
+    fi
+    scls_modules="sth timod"
+    if test :${device:-/dev/sctp} = :/dev/sctp ; then
+	scls_modules="$scls_modules sctp"
+    fi
+    if test ${verbose:-1} -gt 2 ; then
+	scls_options="-b -a"
+    else
+	scls_options="-c -a"
+    fi
+    if test ${verbose:-1} -gt 2 ; then
+	$ECHO "STREAMS statistics"
+	$ECHO
+	$ECHO "------------------------------------"
+    fi
+    if test ${verbose:-1} -gt 1 ; then
+	$ECHO "$scls $scls_options $scls_modules"
+    fi
+    if test :${run:-yes} != :no ; then
+	$scls $scls_options $scls_modules
+    fi
+    $ECHO
+}
+
 function netperf_sctp_test()
 {
     if test :${xti:-no} = :no ; then
@@ -760,6 +764,7 @@ function netperf_sctp_test()
 	    if test ${verbose:-1} -gt 0 ; then
 		$ECHO
 	    fi
+	    scls_show
 	    if test "$sndadd" -le 0 -a "$sndmult" -le 0 ; then
 		break
 	    fi
@@ -776,6 +781,7 @@ function netperf_test()
 	$ECHO
     fi
     netperf_calibrate
+    scls_show
     netperf_sctp_test
     if test ${verbose:-1} -gt 0 ; then
 	$ECHO "Tests completed at `date`"
@@ -799,6 +805,7 @@ function run_command()
     netperf_copying
     netperf_options
     netperf_find
+    scls_find
     if test "${verbose:-1}" -gt 1 ; then
 	((verb=$verbose-1))
 	verb="-v $verb"
diff --git a/netperf/netperf_sctp_rr b/netperf/netperf_sctp_rr
--- a/netperf/netperf_sctp_rr
+++ b/netperf/netperf_sctp_rr
@@ -181,6 +181,7 @@ default_verbose=1
 default_run=yes
 
 default_netperf=${NETPERF_CMD:=netperf}
+default_calibrate=no
 default_testtime=${NETPERF_TIME:=60}
 default_port=${NETPERF_PORT:=}
 default_bufsizes=${NETPERF_SKTS:='32768'}
@@ -192,7 +193,7 @@ default_headers='-P 0'
 default_calibrate=no
 default_rrsizes='1,1 64,64 100,200 128,8192'
 
-defaults='command debug verbose run netperf testtime port hostname device xti stats headers calibrate bufsizes rrsizes'
+defaults='command debug verbose run netperf calibrate testtime port hostname device xti stats headers calibrate bufsizes rrsizes'
 
 function version()
 {
@@ -226,60 +227,60 @@ EOF
 function help()
 {
     if test :${show:-yes} = :no ; then
-        return
+	return
     fi
     version
     usage
     cat <<EOF
 Arguments:
     HOSTNAME
-        name of remote host [Default: $default_hostname]
+	name of remote host [Default: $default_hostname]
     CPU
-        calibrate CPU [Default: $default_calibrate]
+	calibrate CPU [Default: $default_calibrate]
 Options:
     -c, --calibrate
-        calibrate CPU [Default: $default_calibrate]
+	calibrate CPU [Default: $default_calibrate]
     -H, --hostname=HOSTNAME
-        name or address of netserver host [Default: $default_hostname]
+	name or address of netserver host [Default: $default_hostname]
     -p, --port=PORTNUM
-        netserver port number [Default: ${default_port:-12865}]
+	netserver port number [Default: ${default_port:-12865}]
     -t, --testtime=SECONDS
-        duration of each test in seconds [Default: $default_testtime]
+	duration of each test in seconds [Default: $default_testtime]
     -b, --bufsize=SIZE
-        add an additional buffer size to the list
+	add an additional buffer size to the list
     -B, --bufsizes='SIZE[ SIZE]*'
-        specify the list of buffer sizes to test [Default: '$default_bufsizes']
+	specify the list of buffer sizes to test [Default: '$default_bufsizes']
     -r, --rrsize=REQSIZE,RSPSIZE
-        add an additional request/response size to the list
+	add an additional request/response size to the list
     -R, --rrsizes='REQSIZE,RSPSIZE[ REQSIZE,RSPSIZE]*'
-        specify the list of r/r sizes to test [Default: '$default_rrsizes']
+	specify the list of r/r sizes to test [Default: '$default_rrsizes']
     -x, --xti=[DEVICE]
-        use XTI interface instead of Sockets [Default: $default_xti:$default_device]
+	use XTI interface instead of Sockets [Default: $default_xti:$default_device]
     -n, --dry-run
-        do not execute but verify actions [Default: run]
+	do not execute but verify actions [Default: run]
     -q, --quiet
-        supress normal output
+	supress normal output
     -D, --debug [LEVEL]
-        increase or set debugging verbosity [Default: $default_debug]
+	increase or set debugging verbosity [Default: $default_debug]
     -v, --verbose [LEVEL]
-        increase or set output verbosity [Default: $default_verbose]
+	increase or set output verbosity [Default: $default_verbose]
     -h, --help
-        prints this usage information and exits
+	prints this usage information and exits
     -V, --version
-        prints the version information and exits
+	prints the version information and exits
     -C, --copying
-        prints copying permissions and exits
+	prints copying permissions and exits
 Environment:
     NETPERF_CMD
-        default netperf command [Default: $default_netperf]
+	default netperf command [Default: $default_netperf]
     NETPERF_TIME
-        default test case duration [Default: $default_testtime]
+	default test case duration [Default: $default_testtime]
     NETPERF_PORT
-        default netserver port number [Default: ${default_port:-12865}]
+	default netserver port number [Default: ${default_port:-12865}]
     NETPERF_SKTS
-        default buffer sizes [Default: \`$default_bufsizes']
+	default buffer sizes [Default: \`$default_bufsizes']
     NETPERF_STATS
-        default statistics options [Default: \`$default_stats']
+	default statistics options [Default: \`$default_stats']
 EOF
 }
 
@@ -407,6 +408,7 @@ do
 	--debug=* | --debu=* | --deb=* | --de=* | --d=* | \
 	--verbose=* | --verbos=* | --verbo=* | --verb=* | \
 	--port=* | --por=* | --po=* | --p=* | \
+	--xti=* | --xt=* | --x=* | \
 	--hostname=* | --hostnam=* | --hostna=* | --hostn=* | --host=* | --hos=* | --ho=* | --h=* | \
 	--testtime=* | --testime=* | --testtim=* | --testim=* | --time=* | --t=* | \
 	--bufsizes=* | --bufsize=* | --bufsiz=* | --bufsi=* | --bufs=* | --buf=* | --bu=* | --b=* | \
@@ -458,118 +460,67 @@ do
     # Have we seen a non-optional argument yet?
     case $arg in
 	--help | --h | --\? | -h | -\?)
-	    show_help=yes
-	    if test ":$command" = ":" ; then command=none ; fi
-	    ;;
+	    show_help=yes ; if test ":$command" = ":" ; then command=none ; fi ;;
 	--version | --versio | --versi | --vers | -V)
-	    show_version=yes
-	    if test ":$command" = ":" ; then command=none ; fi
-	    ;;
+	    show_version=yes ; if test ":$command" = ":" ; then command=none ; fi ;;
 	--copying | --copyin | --copyi | --copy | --cop | --co | --c | -C)
-	    show_copying=yes
-	    if test ":$command" = ":" ; then command=none ; fi
-	    ;;
+	    show_copying=yes ; if test ":$command" = ":" ; then command=none ; fi ;;
 	--verbose | --verbos | --verbo | --verb)
-	    prevopt="$arg"
-	    prev=verbose
-	    ;;
+	    prevopt="$arg" ; prev=verbose ;;
 	-v)
-	    ((verbose++))
-	    ;;
+	    ((verbose++)) ;;
 	--verbose=* | --verbos=* | --verbo=* | --verb=*)
-	    verbose="$optarg"
-	    ;;
+	    verbose="$optarg" ;;
 	--debug | --debu | --deb)
-	    prevopt="$arg"
-	    prev=debug
-	    ;;
+	    prevopt="$arg" ; prev=debug ;;
 	-D)
-	    $ECHO "$program: enabling shell trace mode" 1>&2
-	    set -x
-	    ;;
+	    $ECHO "$program: enabling shell trace mode" 1>&2 ; set -x ;;
 	--debug=* | --debu=* | --deb=*)
-	    debug="$optarg"
-	    ;;
+	    debug="$optarg" ;;
 	--dry-run | --dryrun | --n | -n)
-	    run=no
-	    ;;
+	    run=no ;;
 	--quiet | --silent | -q)
-	    show=no
-	    verbose=0
-	    debug=0
-	    ;;
+	    show=no ; verbose=0 ; debug=0 ;;
 	--port | --por | --po | --p | -p)
-	    prevopt=$arg
-	    prev=port
-	    ;;
+	    prevopt=$arg ; prev=port ;;
 	--port=* | --por=* | --po=* | --p=* | -p*)
-	    port="$optarg"
-	    ;;
+	    port="$optarg" ;;
 	--testtime | --testime | --testtim | --testim | --time | --t | -t)
-	    prevopt="$arg"
-	    prev=testtime
-	    ;;
+	    prevopt="$arg" ; prev=testtime ;;
 	--testtime=* | --testime=* | --testtim=* | --testim=* | --time=* | --t=* | -t*)
-	    testtime="$optarg"
-	    ;;
+	    testtime="$optarg" ;;
 	--hostname | --hostnam | --hostna | --hostn | --host | --hos | --ho | --h | -H)
-	    prevopt="$arg"
-	    prev=hostname
-	    ;;
+	    prevopt="$arg" ; prev=hostname ;;
 	--hostname=* | --hostnam=* | --hostna=* | --hostn=* | --host=* | --hos=* | --ho=* | --h=* | -H*)
-	    hostname="$optarg"
-	    ;;
+	    hostname="$optarg" ;;
 	--bufsize | --bufsiz | --bufsi | --bufs | --buf | --bu | --b | -b)
-	    prevopt="$arg"
-	    prev=bufsize
-	    ;;
+	    prevopt="$arg" ; prev=bufsize ;;
 	--bufsize=* | --bufsiz=* | --bufsi=* | --bufs=* | --buf=* | --bu=* | --b=* | -b*)
-	    bufsizes="$bufsizes${bufsizes:+ }$optarg"
-	    ;;
+	    bufsizes="$bufsizes${bufsizes:+ }$optarg" ;;
 	--bufsizes | -B)
-	    prevopt="$arg"
-	    prev=bufsizes
-	    ;;
+	    prevopt="$arg" ; prev=bufsizes ;;
 	--bufsizes=* | -B*)
-	    bufsizes="$optarg"
-	    ;;
+	    bufsizes="$optarg" ;;
 	--rrsize | --rrsiz | --rrsi | --rrs | --rr | --r | -r)
-	    prevopt="$arg"
-	    prev=rrsize
-	    ;;
+	    prevopt="$arg" ; prev=rrsize ;;
 	--rrsize=* | --rrsiz=* | --rrsi=* | --rrs=* | --rr=* | --r=* | -r*)
-	    rrsizes="$rrsizes${rrsizes:+ }$optarg"
-	    ;;
+	    rrsizes="$rrsizes${rrsizes:+ }$optarg" ;;
 	--rrsizes | -R)
-	    prevopt="$arg"
-	    prev=rrsizes
-	    ;;
+	    prevopt="$arg" ; prev=rrsizes ;;
 	--rrsizes=* | -R*)
-	    rrsizes="$optarg"
-	    ;;
+	    rrsizes="$optarg" ;;
 	--calibrate | --calibrat | --calibra | --calibr | --calib | --cali | --cal | --ca | --c | -c)
-	    calibrate=yes
-	    ;;
+	    calibrate=yes ;;
 	--xti | --xt | --x | -x)
-	    xti=yes
-	    prevopt="$arg"
-	    prev=device
-	    ;;
+	    xti=yes ; prevopt="$arg" ; prev=device ;;
 	--xti=* | --xt=* | --x=* | -x*)
-	    xti=yes
-	    device="$optarg"
-	    ;;
-	--)
-	    # end of options
-	    more_options=no
-	    ;;
+	    xti=yes ; device="$optarg" ;;
+	--) # end of options
+	    more_options=no ;;
 	-* | \+*)
-	    option_unrec $arg
-	    ;;
-	*)
-	    # permute all non-options to the end
-	    nonopt="${nonopt}${nonopt:+ }$arg"
-	    ;;
+	    option_unrec $arg ;;
+	*)  # permute all non-options to the end
+	    nonopt="${nonopt}${nonopt:+ }$arg" ;;
     esac
 done
 
@@ -604,6 +555,8 @@ for def in $defaults ; do
     val=`eval 'echo $'"$def"`
     if test :${val:+set} != :set ; then
 	eval "$def=\$default_$def"
+    else
+	eval "$def=\"\$val\""
     fi
 done
 
@@ -620,6 +573,32 @@ function netperf_options()
 	done
 	$ECHO
     fi
+}
+
+function scls_find()
+{
+    scls=`which scls 2>/dev/null`
+    pname=`$ECHO "$scls" | $SED -e 's%^.*/%%'`
+    if test ":$pname" = ":scls" ; then
+	return
+    fi
+    if test -x "$scls" ; then
+	return
+    fi
+    # scls is not in our path, check elsewhere
+    scls=`whereis scls 2>/dev/null`
+    scls=`$ECHO "$scls" | $SED -e 's%^scls:[[:space:]]*%%;s%[[:space:]].*%%'`
+    pname=`$ECHO "$scls" | $SED -e 's%^.*/%%'`
+    if test ":$pname" = ":scls" ; then
+	return
+    fi
+    if test -x "$scls" ; then
+	return
+    fi
+    if test ${verbose:-1} -gt 0 ; then
+	$ECHO "$program: warning -- cannot find scls executable" >&2
+    fi
+    scls=scls
 }
 
 function netperf_find()
@@ -711,6 +690,40 @@ function netperf_calibrate()
     fi
 }
 
+function scls_show()
+{
+    if test ${verbose:-1} -le 1 ; then
+	return
+    fi
+    if test :${xti:-no} = :no ; then
+	return
+    fi
+    scls_modules="sth timod"
+    if test :${device:-/dev/sctp} = :/dev/sctp ; then
+	scls_modules="$scls_modules sctp"
+    fi
+    if test :${device:-/dev/sctp} = :/dev/sctp2 ; then
+	scls_modules="$scls_modules sctp2"
+    fi
+    if test ${verbose:-1} -gt 2 ; then
+	scls_options="-b -a"
+    else
+	scls_options="-c -a"
+    fi
+    if test ${verbose:-1} -gt 2 ; then
+	$ECHO "STREAMS statistics"
+	$ECHO
+	$ECHO "------------------------------------"
+    fi
+    if test ${verbose:-1} -gt 1 ; then
+	$ECHO "$scls $scls_options $scls_modules"
+    fi
+    if test :${run:-yes} != :no ; then
+	$scls $scls_options $scls_modules
+    fi
+    $ECHO
+}
+
 function netperf_sctp_test()
 {
     if test :${xti:-no} = :no ; then
@@ -734,6 +747,7 @@ function netperf_sctp_test()
 	    if test ${verbose:-1} -gt 0 ; then
 		$ECHO
 	    fi
+	    scls_show
 	done
     done
 }
@@ -745,6 +759,7 @@ function netperf_test()
 	$ECHO
     fi
     netperf_calibrate
+    scls_show
     netperf_sctp_test
     if test ${verbose:-1} -gt 0 ; then
 	$ECHO "Tests completed at `date`"
@@ -768,6 +783,7 @@ function run_command()
     netperf_copying
     netperf_options
     netperf_find
+    scls_find
     if test "${verbose:-1}" -gt 1 ; then
 	((verb=$verbose-1))
 	verb="-v $verb"
diff --git a/netperf/netperf_sctp_stream b/netperf/netperf_sctp_stream
--- a/netperf/netperf_sctp_stream
+++ b/netperf/netperf_sctp_stream
@@ -184,10 +184,11 @@ default_verbose=1
 default_run=yes
 
 default_netperf=${NETPERF_CMD:=netperf}
+default_calibrate=no
 default_testtime=${NETPERF_TIME:=60}
 default_port=${NETPERF_PORT:=}
-default_stats=${NETPERF_STATS:='-i 10,2 -I 99,5'}
 default_bufsizes=${NETPERF_SKTS:='57344 32768 8192'}
+default_stats=${NETPERF_STATS:='-i 10,2 -I 99,5'}
 default_hostname='localhost'
 default_device='/dev/sctp'
 default_xti=no
@@ -195,7 +196,7 @@ default_headers='-P 0'
 default_calibrate=no
 default_sndsizes='4096 8192 32768'
 
-defaults='command debug verbose run netperf testtime port hostname device xti stats headers calibrate bufsizes sndsizes'
+defaults='command debug verbose run netperf calibrate testtime port hostname device xti stats headers calibrate bufsizes sndsizes'
 
 function version()
 {
@@ -236,22 +237,22 @@ function help()
     cat <<EOF
 Arguments:
     HOSTNAME
-        name of remote host [Default: $default_hostname]
+	name of remote host [Default: $default_hostname]
     CPU
 	calibrate CPU [Default: $default_calibrate]
 Options:
     -c, --calibrate
 	calibrate CPU [Default: $default_calibrate]
     -H, --hostname=HOSTNAME
-        name or address of netserver host [Default: $default_hostname]
+	name or address of netserver host [Default: $default_hostname]
     -p, --port=PORTNUM
-        netserver port number [Default: ${default_port:-12865}]
+	netserver port number [Default: ${default_port:-12865}]
     -t, --testtime=SECONDS
 	duration of each test in seconds [Default: $default_testtime]
     -b, --bufsize=SIZE
 	add an additional buffer size to the list
     -B, --bufsizes='SIZE[ SIZE]*'
-        specify the list of buffer sizes to test [Default: '$default_bufsizes']
+	specify the list of buffer sizes to test [Default: '$default_bufsizes']
     -s, --sendsize=SIZE
 	add an additional send size to the list
     -S, --sendsizes='SIZE[ SIZE]*'
@@ -410,6 +411,7 @@ do
 	--debug=* | --debu=* | --deb=* | --de=* | --d=* | \
 	--verbose=* | --verbos=* | --verbo=* | --verb=* | \
 	--port=* | --por=* | --po=* | --p=* | \
+	--xti=* | --xt=* | --x=* | \
 	--hostname=* | --hostnam=* | --hostna=* | --hostn=* | --host=* | --hos=* | --ho=* | --h=* | \
 	--testtime=* | --testime=* | --testtim=* | --testim=* | --time=* | --t=* | \
 	--bufsizes=* | --bufsize=* | --bufsiz=* | --bufsi=* | --bufs=* | --buf=* | --bu=* | --b=* | \
@@ -461,118 +463,67 @@ do
     # Have we seen a non-optional argument yet?
     case $arg in
 	--help | --h | --\? | -h | -\?)
-	    show_help=yes
-	    if test ":$command" = ":" ; then command=none ; fi
-	    ;;
+	    show_help=yes ; if test ":$command" = ":" ; then command=none ; fi ;;
 	--version | --versio | --versi | --vers | -V)
-	    show_version=yes
-	    if test ":$command" = ":" ; then command=none ; fi
-	    ;;
+	    show_version=yes ; if test ":$command" = ":" ; then command=none ; fi ;;
 	--copying | --copyin | --copyi | --copy | --cop | --co | --c | -C)
-	    show_copying=yes
-	    if test ":$command" = ":" ; then command=none ; fi
-	    ;;
+	    show_copying=yes ; if test ":$command" = ":" ; then command=none ; fi ;;
 	--verbose | --verbos | --verbo | --verb)
-	    prevopt="$arg"
-	    prev=verbose
-	    ;;
+	    prevopt="$arg" ; prev=verbose ;;
 	-v)
-	    ((verbose++))
-	    ;;
+	    ((verbose++)) ;;
 	--verbose=* | --verbos=* | --verbo=* | --verb=*)
-	    verbose="$optarg"
-	    ;;
+	    verbose="$optarg" ;;
 	--debug | --debu | --deb)
-	    prevopt="$arg"
-	    prev=debug
-	    ;;
+	    prevopt="$arg" ; prev=debug ;;
 	-D)
-	    $ECHO "$program: enabling shell trace mode" 1>&2
-	    set -x
-	    ;;
+	    $ECHO "$program: enabling shell trace mode" 1>&2 ; set -x ;;
 	--debug=* | --debu=* | --deb=*)
-	    debug="$optarg"
-	    ;;
+	    debug="$optarg" ;;
 	--dry-run | --dryrun | --n | -n)
-	    run=no
-	    ;;
+	    run=no ;;
 	--quiet | --silent | -q)
-	    show=no
-	    verbose=0
-	    debug=0
-	    ;;
+	    show=no ; verbose=0 ; debug=0 ;;
 	--port | --por | --po | --p | -p)
-	    prevopt=$arg
-	    prev=port
-	    ;;
+	    prevopt=$arg ; prev=port ;;
 	--port=* | --por=* | --po=* | --p=* | -p*)
-	    port="$optarg"
-	    ;;
+	    port="$optarg" ;;
 	--testtime | --testime | --testtim | --testim | --time | --t | -t)
-	    prevopt="$arg"
-	    prev=testtime
-	    ;;
+	    prevopt="$arg" ; prev=testtime ;;
 	--testtime=* | --testime=* | --testtim=* | --testim=* | --time=* | --t=* | -t*)
-	    testtime="$optarg"
-	    ;;
+	    testtime="$optarg" ;;
 	--hostname | --hostnam | --hostna | --hostn | --host | --hos | --ho | --h | -H)
-	    prevopt="$arg"
-	    prev=hostname
-	    ;;
+	    prevopt="$arg" ; prev=hostname ;;
 	--hostname=* | --hostnam=* | --hostna=* | --hostn=* | --host=* | --hos=* | --ho=* | --h=* | -H*)
-	    hostname="$optarg"
-	    ;;
+	    hostname="$optarg" ;;
 	--bufsize | --bufsiz | --bufsi | --bufs | --buf | --bu | --b | -b)
-	    prevopt="$arg"
-	    prev=bufsize
-	    ;;
+	    prevopt="$arg" ; prev=bufsize ;;
 	--bufsize=* | --bufsiz=* | --bufsi=* | --bufs=* | --buf=* | --bu=* | --b=* | -b*)
-	    bufsizes="$bufsizes${bufsizes:+ }$optarg"
-	    ;;
+	    bufsizes="$bufsizes${bufsizes:+ }$optarg" ;;
 	--bufsizes | -B)
-	    prevopt="$arg"
-	    prev=bufsizes
-	    ;;
+	    prevopt="$arg" ; prev=bufsizes ;;
 	--bufsizes=* | -B*)
-	    bufsizes="$optarg"
-	    ;;
+	    bufsizes="$optarg" ;;
 	--sndsize | --sndsiz | --sndsi | --snds | --snd | --sn | --s | -s)
-	    prevopt="$arg"
-	    prev=sndsize
-	    ;;
+	    prevopt="$arg" ; prev=sndsize ;;
 	--sndsize=* | --sndsiz=* | --sndsi=* | --snds=* | --snd=* | --sn=* | --s=* | -s*)
-	    sndsizes="$sndsizes${sndsizes:+ }$optarg"
-	    ;;
+	    sndsizes="$sndsizes${sndsizes:+ }$optarg" ;;
 	--sndsizes | -S)
-	    prevopt="$arg"
-	    prev=sndsizes
-	    ;;
+	    prevopt="$arg" ; prev=sndsizes ;;
 	--sndsizes=* | -S*)
-	    sndsizes="$optarg"
-	    ;;
+	    sndsizes="$optarg" ;;
 	--calibrate | --calibrat | --calibra | --calibr | --calib | --cali | --cal | --ca | --c | -c)
-	    calibrate=yes
-	    ;;
+	    calibrate=yes ;;
 	--xti | --xt | --x | -x)
-	    xti=yes
-	    prevopt="$arg"
-	    prev=device
-	    ;;
+	    xti=yes ; prevopt="$arg" ; prev=device ;;
 	--xti=* | --xt=* | --x=* | -x*)
-	    xti=yes
-	    device="$optarg"
-	    ;;
-	--)
-	    # end of options
-	    more_options=no
-	    ;;
+	    xti=yes ; device="$optarg" ;;
+	--) # end of options
+	    more_options=no ;;
 	-* | \+*)
-	    option_unrec $arg
-	    ;;
-	*)
-	    # permute all non-options to the end
-	    nonopt="${nonopt}${nonopt:+ }$arg"
-	    ;;
+	    option_unrec $arg ;;
+	*)  # permute all non-options to the end
+	    nonopt="${nonopt}${nonopt:+ }$arg" ;;
     esac
 done
 
@@ -607,6 +558,8 @@ for def in $defaults ; do
     val=`eval 'echo $'"$def"`
     if test :${val:+set} != :set ; then
 	eval "$def=\$default_$def"
+    else
+	eval "$def=\"\$val\""
     fi
 done
 
@@ -623,6 +576,32 @@ function netperf_options()
 	done
 	$ECHO
     fi
+}
+
+function scls_find()
+{
+    scls=`which scls 2>/dev/null`
+    pname=`$ECHO "$scls" | $SED -e 's%^.*/%%'`
+    if test ":$pname" = ":scls" ; then
+	return
+    fi
+    if test -x "$scls" ; then
+	return
+    fi
+    # scls is not in our path, check elsewhere
+    scls=`whereis scls 2>/dev/null`
+    scls=`$ECHO "$scls" | $SED -e 's%^scls:[[:space:]]*%%;s%[[:space:]].*%%'`
+    pname=`$ECHO "$scls" | $SED -e 's%^.*/%%'`
+    if test ":$pname" = ":scls" ; then
+	return
+    fi
+    if test -x "$scls" ; then
+	return
+    fi
+    if test ${verbose:-1} -gt 0 ; then
+	$ECHO "$program: warning -- cannot find scls executable" >&2
+    fi
+    scls=scls
 }
 
 function netperf_find()
@@ -714,6 +693,40 @@ function netperf_calibrate()
     fi
 }
 
+function scls_show()
+{
+    if test ${verbose:-1} -le 1 ; then
+	return
+    fi
+    if test :${xti:-no} = :no ; then
+	return
+    fi
+    scls_modules="sth timod"
+    if test :${device:-/dev/sctp} = :/dev/sctp ; then
+	scls_modules="$scls_modules sctp"
+    fi
+    if test :${device:-/dev/sctp} = :/dev/sctp2 ; then
+	scls_modules="$scls_modules sctp2"
+    fi
+    if test ${verbose:-1} -gt 2 ; then
+	scls_options="-b -a"
+    else
+	scls_options="-c -a"
+    fi
+    if test ${verbose:-1} -gt 2 ; then
+	$ECHO "STREAMS statistics"
+	$ECHO
+	$ECHO "------------------------------------"
+    fi
+    if test ${verbose:-1} -gt 1 ; then
+	$ECHO "$scls $scls_options $scls_modules"
+    fi
+    if test :${run:-yes} != :no ; then
+	$scls $scls_options $scls_modules
+    fi
+    $ECHO
+}
+
 function netperf_sctp_test()
 {
     if test :${xti:-no} = :no ; then
@@ -737,6 +750,7 @@ function netperf_sctp_test()
 	    if test ${verbose:-1} -gt 0 ; then
 		$ECHO
 	    fi
+	    scls_show
 	done
     done
 }
@@ -748,6 +762,7 @@ function netperf_test()
 	$ECHO
     fi
     netperf_calibrate
+    scls_show
     netperf_sctp_test
     if test ${verbose:-1} -gt 0 ; then
 	$ECHO "Tests completed at `date`"
@@ -771,6 +786,7 @@ function run_command()
     netperf_copying
     netperf_options
     netperf_find
+    scls_find
     if test "${verbose:-1}" -gt 1 ; then
 	((verb=$verbose-1))
 	verb="-v $verb"
diff --git a/netperf/netperf_snapshot b/netperf/netperf_snapshot
--- a/netperf/netperf_snapshot
+++ b/netperf/netperf_snapshot
@@ -181,6 +181,7 @@ default_verbose=1
 default_run=yes
 
 default_netperf=${NETPERF_CMD:=netperf}
+default_calibrate=no
 default_testtime=${NETPERF_TIME:=60}
 default_port=${NETPERF_PORT:=}
 default_stats=${NETPERF_STATS:='-i 10,3 -I 99,5'}
@@ -197,7 +198,7 @@ default_xti=no
 default_headers='-P 0'
 default_calibrate=no
 
-defaults='command debug verbose run netperf testtime port warmtime hostname bufsize sctp tcp udp sctpdev tcpdev udpdev xti stats headers calibrate'
+defaults='command debug verbose run netperf calibrate testtime port warmtime hostname bufsize sctp tcp udp sctpdev tcpdev udpdev xti stats headers calibrate'
 
 function version()
 {
@@ -238,16 +239,16 @@ function help()
     cat <<EOF
 Arguments:
     HOSTNAME
-        name of remote host [Default: $default_hostname]
+	name of remote host [Default: $default_hostname]
     CPU
 	calibrate CPU [Default: $default_calibrate]
 Options:
     -c, --calibrate
 	calibrate CPU [Default: $default_calibrate]
     -H, --hostname=HOSTNAME
-        name or address of netserver host [Default: $default_hostname]
+	name or address of netserver host [Default: $default_hostname]
     -p, --port=PORTNUM
-        netserver port number [Default: ${default_port:-12865}]
+	netserver port number [Default: ${default_port:-12865}]
     -t, --testtime=SECONDS
 	duration of each test in seconds [Default: $default_testtime]
     -w, --warmtime=SECONDS
@@ -407,12 +408,12 @@ do
     if test x"$more_options" = xno ; then nonopt="$arg" ; break ; fi
     # check for attached option argument
     case $arg in
-	--port=* | --por=* | --po=* | --p=* | \
-	--hostname=* | --hostnam=* | --hostna=* | --hostn=* | --host=* | --hos=* | --ho=* | --h=* | \
 	--debug=* | --debu=* | --deb=* | --de=* | --d=* | \
 	--verbose=* | --verbos=* | --verbo=* | --verb=* | \
-	--warmtime=* | --warmtim=* | --warmti=* | --warmt=* | --warm=* | --war=* | --wa=* | --w=* | \
+	--port=* | --por=* | --po=* | --p=* | \
+	--hostname=* | --hostnam=* | --hostna=* | --hostn=* | --host=* | --hos=* | --ho=* | --h=* | \
 	--testtime=* | --testime=* | --testtim=* | --testim=* | --time=* | --t=* | \
+	--warmtime=* | --warmtim=* | --warmti=* | --warmt=* | --warm=* | --war=* | --wa=* | --w=* | \
 	--bufsize=* | --bufsiz=* | --bufsi=* | --bufs=* | --buf=* | --bu=* | --b=* | \
 	--sctp=* | --sct=* | --sc=* | --s=* | --tcp=* | --tc=* | --udp=* | --ud=*)
 	    optarg=`$ECHO "X$arg" | $Xsed -e 's/[-_a-zA-Z0-9]*=//'` ;;
@@ -460,137 +461,75 @@ do
     # Have we seen a non-optional argument yet?
     case $arg in
 	--help | --h | --\? | -h | -\?)
-	    show_help=yes
-	    if test ":$command" = ":" ; then command=none ; fi
-	    ;;
+	    show_help=yes ; if test ":$command" = ":" ; then command=none ; fi ;;
 	--version | --versio | --versi | --vers | -V)
-	    show_version=yes
-	    if test ":$command" = ":" ; then command=none ; fi
-	    ;;
+	    show_version=yes ; if test ":$command" = ":" ; then command=none ; fi ;;
 	--copying | --copyin | --copyi | --copy | --cop | --co | --c | -C)
-	    show_copying=yes
-	    if test ":$command" = ":" ; then command=none ; fi
-	    ;;
+	    show_copying=yes ; if test ":$command" = ":" ; then command=none ; fi ;;
 	--verbose | --verbos | --verbo | --verb)
-	    prevopt="$arg"
-	    prev=verbose
-	    ;;
+	    prevopt="$arg" ; prev=verbose ;;
 	-v)
-	    ((verbose++))
-	    ;;
+	    ((verbose++)) ;;
 	--verbose=* | --verbos=* | --verbo=* | --verb=*)
-	    verbose="$optarg"
-	    ;;
+	    verbose="$optarg" ;;
 	--debug | --debu | --deb)
-	    prevopt="$arg"
-	    prev=debug
-	    ;;
+	    prevopt="$arg" ; prev=debug ;;
 	-D)
-	    $ECHO "$program: enabling shell trace mode" 1>&2
-	    set -x
-	    ;;
+	    $ECHO "$program: enabling shell trace mode" 1>&2 ; set -x ;;
 	--debug=* | --debu=* | --deb=*)
-	    debug="$optarg"
-	    ;;
+	    debug="$optarg" ;;
 	--dry-run | --dryrun | --n | -n)
-	    run=no
-	    ;;
+	    run=no ;;
 	--quiet | --silent | -q)
-	    show=no
-	    verbose=0
-	    debug=0
-	    ;;
+	    show=no ; verbose=0 ; debug=0 ;;
 	--port | --por | --po | --p | -p)
-	    prevopt=$arg
-	    prev=port
-	    ;;
+	    prevopt=$arg ; prev=port ;;
 	--port=* | --por=* | --po=* | --p=* | -p*)
-	    port="$optarg"
-	    ;;
+	    port="$optarg" ;;
 	--warmtime | --warmtim | --warmti | --warmt | --warm | --war | --wa | --w | -w)
-	    prevopt="$arg"
-	    prev=warmtime
-	    ;;
+	    prevopt="$arg" ; prev=warmtime ;;
 	--warmtime=* | --warmtim=* | --warmti=* | --warmt=* | --warm=* | --war=* | --wa=* | --w=* | -w*)
-	    warmtime="$optarg"
-	    ;;
+	    warmtime="$optarg" ;;
 	--testtime | --testime | --testtim | --testim | --time | --t | -t)
-	    prevopt="$arg"
-	    prev=testtime
-	    ;;
+	    prevopt="$arg" ; prev=testtime ;;
 	--testtime=* | --testime=* | --testtim=* | --testim=* | --time=* | --t=* | -t*)
-	    testtime="$optarg"
-	    ;;
+	    testtime="$optarg" ;;
 	--hostname | --hostnam | --hostna | --hostn | --host | --hos | --ho | --h | -H)
-	    prevopt="$arg"
-	    prev=hostname
-	    ;;
+	    prevopt="$arg" ; prev=hostname ;;
 	--hostname=* | --hostnam=* | --hostna=* | --hostn=* | --host=* | --hos=* | --ho=* | --h=* | -H*)
-	    hostname="$optarg"
-	    ;;
+	    hostname="$optarg" ;;
 	--bufsize | --bufsiz | --bufsi | --bufs | --buf | --bu | --b | -b)
-	    prevopt="$arg"
-	    prev=bufsizes
-	    ;;
+	    prevopt="$arg" ; prev=bufsizes ;;
 	--bufsize=* | --bufsiz=* | --bufsi=* | --bufs=* | --buf=* | --bu=* | --b=* | -b*)
-	    bufsize="$optarg"
-	    ;;
+	    bufsizes="$optarg" ;;
 	--calibrate | --calibrat | --calibra | --calibr | --calib | --cali | --cal | --ca | --c | -c)
-	    calibrate=yes
-	    ;;
+	    calibrate=yes ;;
 	--sctp | --sct | --sc | --s | \+S)
-	    sctp=yes
-	    prevopt="$arg"
-	    prev=sctpdev
-	    ;;
+	    sctp=yes ; prevopt="$arg" ; prev=sctpdev ;;
 	--sctp=* | --sct=* | --sc=* | --s=* | \+S*)
-	    sctp=yes
-	    sctpdev="$optarg"
-	    ;;
+	    sctp=yes ; sctpdev="$optarg" ;;
 	--tcp | --tc | \+T)
-	    tcp=yes
-	    prevopt="$arg"
-	    prev=tcpdev
-	    ;;
+	    tcp=yes ; prevopt="$arg" ; prev=tcpdev ;;
 	--tcp=* | --tc=* | \+T*)
-	    tcp=yes
-	    tcpdev="$optarg"
-	    ;;
+	    tcp=yes ; tcpdev="$optarg" ;;
 	--udp | --ud | \+U)
-	    udp=yes
-	    prevopt="$arg"
-	    prev=udpdev
-	    ;;
+	    udp=yes ; prevopt="$arg" ; prev=udpdev ;;
 	--udp=* | --ud=* | \+U*)
-	    udp=yes
-	    udpdev="$optarg"
-	    ;;
+	    udp=yes ; udpdev="$optarg" ;;
 	--nosctp | --nosct | --nosc | --nos | -S)
-	    sctp=no
-	    sctpdev=
-	    ;;
+	    sctp=no ; sctpdev= ;;
 	--notcp | --notc | -T)
-	    tcp=no
-	    tcpdev=
-	    ;;
+	    tcp=no ; tcpdev= ;;
 	--noudp | --noud | -U)
-	    udp=no
-	    udpdev=
-	    ;;
+	    udp=no ; udpdev= ;;
 	--xti | --xt | --x | -x)
-	    xti=yes
-	    ;;
-	--)
-	    # end of options
-	    more_options=no
-	    ;;
+	    xti=yes ;;
+	--) # end of options
+	    more_options=no ;;
 	-* | \+*)
-	    option_unrec $arg
-	    ;;
-	*)
-	    # permute all non-options to the end
-	    nonopt="${nonopt}${nonopt:+ }$arg"
-	    ;;
+	    option_unrec $arg ;;
+	*)  # permute all non-options to the end
+	    nonopt="${nonopt}${nonopt:+ }$arg" ;;
     esac
 done
 
@@ -606,7 +545,7 @@ esac
 
 args=($nonopt${nonopt:+ }${1+$@})
 
-if test "$verbose" -gt 2 ; then
+if test "$verbose" -gt 3 ; then
     $ECHO "Nonoption arguments: ${args[@]}"
 fi
 
@@ -636,12 +575,39 @@ fi
 
 function netperf_options()
 {
-    if test ${verbose:-1} -gt 2 ; then
+    if test ${verbose:-1} -gt 3 ; then
 	for arg in $defaults ; do
 	    val=`eval 'echo $'"$arg"`
 	    $ECHO "Option $arg is \`$val'"
 	done
+	$ECHO
     fi
+}
+
+function scls_find()
+{
+    scls=`which scls 2>/dev/null`
+    pname=`$ECHO "$scls" | $SED -e 's%^.*/%%'`
+    if test ":$pname" = ":scls" ; then
+	return
+    fi
+    if test -x "$scls" ; then
+	return
+    fi
+    # scls is not in our path, check elsewhere
+    scls=`whereis scls 2>/dev/null`
+    scls=`$ECHO "$scls" | $SED -e 's%^scls:[[:space:]]*%%;s%[[:space:]].*%%'`
+    pname=`$ECHO "$scls" | $SED -e 's%^.*/%%'`
+    if test ":$pname" = ":scls" ; then
+	return
+    fi
+    if test -x "$scls" ; then
+	return
+    fi
+    if test ${verbose:-1} -gt 0 ; then
+	$ECHO "$program: warning -- cannot find scls executable" >&2
+    fi
+    scls=scls
 }
 
 function netperf_find()
@@ -733,6 +699,52 @@ function netperf_calibrate()
     fi
 }
 
+function scls_show()
+{
+    if test ${verbose:-1} -le 1 ; then
+	return
+    fi
+    if test :${xti:-no} = :no ; then
+	return
+    fi
+    scls_modules="sth timod"
+    if test :${device:-/dev/udp} = :/dev/udp ; then
+	scls_modules="$scls_modules inet"
+    fi
+    if test :${device:-/dev/udp} = :/dev/udp2 ; then
+	scls_modules="$scls_modules udp2"
+    fi
+    if test :${device:-/dev/tcp} = :/dev/tcp ; then
+	scls_modules="$scls_modules inet"
+    fi
+    if test :${device:-/dev/tcp} = :/dev/tcp2 ; then
+	scls_modules="$scls_modules tcp2"
+    fi
+    if test :${device:-/dev/sctp} = :/dev/sctp ; then
+	scls_modules="$scls_modules sctp"
+    fi
+    if test :${device:-/dev/sctp} = :/dev/sctp2 ; then
+	scls_modules="$scls_modules sctp2"
+    fi
+    if test ${verbose:-1} -gt 2 ; then
+	scls_options="-b -a"
+    else
+	scls_options="-c -a"
+    fi
+    if test ${verbose:-1} -gt 2 ; then
+	$ECHO "STREAMS statistics"
+	$ECHO
+	$ECHO "------------------------------------"
+    fi
+    if test ${verbose:-1} -gt 1 ; then
+	$ECHO "$scls $scls_options $scls_modules"
+    fi
+    if test :${run:-yes} != :no ; then
+	$scls $scls_options $scls_modules
+    fi
+    $ECHO
+}
+
 function netperf_sctp_warmup()
 {
 	return
@@ -754,6 +766,7 @@ function netperf_tcp_warmup()
     if test :${run:-yes} != :no ; then
 	$netperf ${port:+-p }$port -P 0 -l $warmtime -t $testcase -H $hostname $calibration -- -s 32768 -S 32768 -m 4096 $device 2>&1 >/dev/null
     fi
+    scls_show
     if test ${verbose:-1} -gt 1 ; then
 	$ECHO
 	$ECHO
@@ -768,6 +781,7 @@ function netperf_tcp_warmup()
     if test :${run:-yes} != :no ; then
 	$netperf ${port:+-p }$port -P 0 -l $warmtime -t $testcase -H $hostname $calibration -- -s 32768 -S 32768 -m   96 $device 2>&1 >/dev/null
     fi
+    scls_show
     if test ${verbose:-1} -gt 1 ; then
 	$ECHO
 	$ECHO
@@ -783,6 +797,7 @@ function netperf_tcp_warmup()
     if test :${run:-yes} != :no ; then
 	$netperf ${port:+-p }$port -P 0 -l $warmtime -t $testcase -H $hostname $calibration -- -r 1,1                    $device 2>&1 >/dev/null
     fi
+    scls_show
     if test ${verbose:-1} -gt 1 ; then
 	$ECHO
 	$ECHO
@@ -812,6 +827,7 @@ function netperf_sctp_tests()
     if test :${run:-yes} != :no ; then
 	$netperf ${port:+-p }$port $stats $headers -l $testtime -t $testcase -H $hostname $calibration -- -s 57344 -S 57344 -m 4096 $device
     fi
+    scls_show
     if test ${verbose:-1} -gt 0 ; then
 	$ECHO
 	$ECHO
@@ -827,6 +843,7 @@ function netperf_sctp_tests()
     if test :${run:-yes} != :no ; then
 	$netperf ${port:+-p }$port $stats $headers -l $testtime -t $testcase -H $hostname $calibration -- -s 32768 -S 32768 -m 4096 $device
     fi
+    scls_show
     if test ${verbose:-1} -gt 0 ; then
 	$ECHO
 	$ECHO
@@ -843,6 +860,7 @@ function netperf_sctp_tests()
     if test :${run:-yes} != :no ; then
 	$netperf ${port:+-p }$port $stats $headers -l $testtime -t $testcase -H $hostname $calibration -- -r 1,1 $device
     fi
+    scls_show
     if test ${verbose:-1} -gt 0 ; then
 	$ECHO
 	$ECHO
@@ -867,6 +885,7 @@ function netperf_tcp_tests()
     if test :${run:-yes} != :no ; then
 	$netperf ${port:+-p }$port $stats $headers -l $testtime -t $testcase -H $hostname $calibration -- -s 57344 -S 57344 -m 4096 $device
     fi
+    scls_show
     if test ${verbose:-1} -gt 0 ; then
 	$ECHO
 	$ECHO
@@ -882,6 +901,7 @@ function netperf_tcp_tests()
     if test :${run:-yes} != :no ; then
 	$netperf ${port:+-p }$port $stats $headers -l $testtime -t $testcase -H $hostname $calibration -- -s 32768 -S 32768 -m 4096 $device
     fi
+    scls_show
     if test ${verbose:-1} -gt 0 ; then
 	$ECHO
 	$ECHO
@@ -898,6 +918,7 @@ function netperf_tcp_tests()
     if test :${run:-yes} != :no ; then
 	$netperf ${port:+-p }$port $stats $headers -l $testtime -t $testcase -H $hostname $calibration -- -r 1,1 $device
     fi
+    scls_show
     if test ${verbose:-1} -gt 0 ; then
 	$ECHO
 	$ECHO
@@ -922,6 +943,7 @@ function netperf_udp_tests()
     if test :${run:-yes} != :no ; then
 	$netperf ${port:+-p }$port $stats $headers -l $testtime -t $testcase -H $hostname $calibration -- -r 1,1 $device
     fi
+    scls_show
     if test ${verbose:-1} -gt 0 ; then
 	$ECHO
 	$ECHO
@@ -937,6 +959,7 @@ function netperf_udp_tests()
     if test :${run:-yes} != :no ; then
 	$netperf ${port:+-p }$port $stats $headers -l $testtime -t $testcase -H $hostname $calibration -- -r 516,4 $device
     fi
+    scls_show
     if test ${verbose:-1} -gt 0 ; then
 	$ECHO
 	$ECHO
@@ -953,6 +976,7 @@ function netperf_udp_tests()
     if test :${run:-yes} != :no ; then
 	$netperf ${port:+-p }$port $stats $headers -l $testtime -t $testcase -H $hostname $calibration -- -s 32768 -S 32768 -m 4096 $device
     fi
+    scls_show
     if test ${verbose:-1} -gt 0 ; then
 	$ECHO
 	$ECHO
@@ -968,6 +992,7 @@ function netperf_udp_tests()
     if test :${run:-yes} != :no ; then
 	$netperf ${port:+-p }$port $stats $headers -l $testtime -t $testcase -H $hostname $calibration -- -s 32768 -S 32768 -m 1024 $device
     fi
+    scls_show
     if test ${verbose:-1} -gt 0 ; then
 	$ECHO
 	$ECHO
@@ -981,6 +1006,7 @@ function netperf_test()
 	$ECHO
     fi
     netperf_calibrate
+    scls_show
     netperf_sctp_tests
     netperf_tcp_tests
     netperf_udp_tests
@@ -1006,6 +1032,7 @@ function run_command()
     netperf_copying
     netperf_options
     netperf_find
+    scls_find
     if test "${verbose:-1}" -gt 1 ; then
 	((verb=$verbose-1))
 	verb="-v $verb"
diff --git a/netperf/netperf_tcp_stream b/netperf/netperf_tcp_stream
--- a/netperf/netperf_tcp_stream
+++ b/netperf/netperf_tcp_stream
@@ -184,10 +184,11 @@ default_verbose=1
 default_run=yes
 
 default_netperf=${NETPERF_CMD:=netperf}
+default_calibrate=no
 default_testtime=${NETPERF_TIME:=60}
 default_port=${NETPERF_PORT:=}
-default_stats=${NETPERF_STATS:='-i 10,2 -I 99,5'}
 default_bufsizes=${NETPERF_SKTS:='57344 32768 8192'}
+default_stats=${NETPERF_STATS:='-i 10,2 -I 99,5'}
 default_hostname='localhost'
 default_device='/dev/tcp'
 default_xti=no
@@ -195,7 +196,7 @@ default_headers='-P 0'
 default_calibrate=no
 default_sndsizes='4096 8192 32768'
 
-defaults='command debug verbose run netperf testtime port hostname device xti stats headers calibrate bufsizes sndsizes'
+defaults='command debug verbose run netperf calibrate testtime port hostname device xti stats headers calibrate bufsizes sndsizes'
 
 function version()
 {
@@ -236,22 +237,22 @@ function help()
     cat <<EOF
 Arguments:
     HOSTNAME
-        name of remote host [Default: $default_hostname]
+	name of remote host [Default: $default_hostname]
     CPU
 	calibrate CPU [Default: $default_calibrate]
 Options:
     -c, --calibrate
 	calibrate CPU [Default: $default_calibrate]
     -H, --hostname=HOSTNAME
-        name or address of netserver host [Default: $default_hostname]
+	name or address of netserver host [Default: $default_hostname]
     -p, --port=PORTNUM
-        netserver port number [Default: ${default_port:-12865}]
+	netserver port number [Default: ${default_port:-12865}]
     -t, --testtime=SECONDS
 	duration of each test in seconds [Default: $default_testtime]
     -b, --bufsize=SIZE
 	add an additional buffer size to the list
     -B, --bufsizes='SIZE[ SIZE]*'
-        specify the list of buffer sizes to test [Default: '$default_bufsizes']
+	specify the list of buffer sizes to test [Default: '$default_bufsizes']
     -s, --sendsize=SIZE
 	add an additional send size to the list
     -S, --sendsizes='SIZE[ SIZE]*'
@@ -557,6 +558,8 @@ for def in $defaults ; do
     val=`eval 'echo $'"$def"`
     if test :${val:+set} != :set ; then
 	eval "$def=\$default_$def"
+    else
+	eval "$def=\"\$val\""
     fi
 done
 
@@ -573,6 +576,32 @@ function netperf_options()
 	done
 	$ECHO
     fi
+}
+
+function scls_find()
+{
+    scls=`which scls 2>/dev/null`
+    pname=`$ECHO "$scls" | $SED -e 's%^.*/%%'`
+    if test ":$pname" = ":scls" ; then
+	return
+    fi
+    if test -x "$scls" ; then
+	return
+    fi
+    # scls is not in our path, check elsewhere
+    scls=`whereis scls 2>/dev/null`
+    scls=`$ECHO "$scls" | $SED -e 's%^scls:[[:space:]]*%%;s%[[:space:]].*%%'`
+    pname=`$ECHO "$scls" | $SED -e 's%^.*/%%'`
+    if test ":$pname" = ":scls" ; then
+	return
+    fi
+    if test -x "$scls" ; then
+	return
+    fi
+    if test ${verbose:-1} -gt 0 ; then
+	$ECHO "$program: warning -- cannot find scls executable" >&2
+    fi
+    scls=scls
 }
 
 function netperf_find()
@@ -664,6 +693,40 @@ function netperf_calibrate()
     fi
 }
 
+function scls_show()
+{
+    if test ${verbose:-1} -le 1 ; then
+	return
+    fi
+    if test :${xti:-no} = :no ; then
+	return
+    fi
+    scls_modules="sth timod"
+    if test :${device:-/dev/tcp} = :/dev/tcp ; then
+	scls_modules="$scls_modules inet"
+    fi
+    if test :${device:-/dev/tcp} = :/dev/tcp2 ; then
+	scls_modules="$scls_modules tcp2"
+    fi
+    if test ${verbose:-1} -gt 2 ; then
+	scls_options="-b -a"
+    else
+	scls_options="-c -a"
+    fi
+    if test ${verbose:-1} -gt 2 ; then
+	$ECHO "STREAMS statistics"
+	$ECHO
+	$ECHO "------------------------------------"
+    fi
+    if test ${verbose:-1} -gt 1 ; then
+	$ECHO "$scls $scls_options $scls_modules"
+    fi
+    if test :${run:-yes} != :no ; then
+	$scls $scls_options $scls_modules
+    fi
+    $ECHO
+}
+
 function netperf_tcp_test()
 {
     if test :${xti:-no} = :no ; then
@@ -687,6 +750,7 @@ function netperf_tcp_test()
 	    if test ${verbose:-1} -gt 0 ; then
 		$ECHO
 	    fi
+	    scls_show
 	done
     done
 }
@@ -698,6 +762,7 @@ function netperf_test()
 	$ECHO
     fi
     netperf_calibrate
+    scls_show
     netperf_tcp_test
     if test ${verbose:-1} -gt 0 ; then
 	$ECHO "Tests completed at `date`"
@@ -721,6 +786,7 @@ function run_command()
     netperf_copying
     netperf_options
     netperf_find
+    scls_find
     if test "${verbose:-1}" -gt 1 ; then
 	((verb=$verbose-1))
 	verb="-v $verb"
