Import from CVS Fri Dec 16 10:19:48 2005 -0600
- updated to support SuSE/UL and LSB init scripts
- correct echo test
- minor correction
- stupid echo check error
- stupid echo test error

diff --git a/LiS/util/init/strace b/LiS/util/init/strace
--- a/LiS/util/init/strace
+++ b/LiS/util/init/strace
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 #
-# @(#) $RCSfile: strace,v $ $Name:  $($Revision: 1.1.2.1 $) $Date: 2005/03/13 06:28:07 $
+# @(#) $RCSfile: strace,v $ $Name:  $($Revision: 1.1.2.2 $) $Date: 2005/12/16 09:26:07 $
 # Copyright (c) 2001-2005  OpenSS7 Corporation <http://www.openss7.com>
 # Copyright (c) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>
 # All Rights Reserved.
@@ -11,7 +11,7 @@
 # Redhat chkconfig init script conventions
 #
 # strace:	start and stop strace facility
-# chkconfig:	- 55 88
+# chkconfig:	- 04 95
 # lockfile:	/var/lock/subsys/strace
 # config:	/etc/default/strace
 # processname:	strace
@@ -31,8 +31,11 @@
 # Provides: strace
 # Required-Start: streams
 # Required-Stop: streams
+# Should-Start: strerr
+# Should-Stop: strerr
 # Default-Start: 
 # Default-Stop: 0 1 2 3 4 5 6
+# X-UnitedLinux-Default-Enabled: no
 # Short-Description: start and stop strace
 # License: GPL
 # Description:	This STREAMS init script is part of Linux Fast-STREAMS.  It is
@@ -42,7 +45,104 @@
 ### END INIT INFO
 
 # Source init script functions library
-[ -f /etc/init.d/functions ] && . /etc/init.d/functions
+init_mode="standalone"
+if [ -r /lib/lsb/init-functions ] ; then . /lib/lsb/init-functions ; init_mode="lsb" ;
+if [ -r /etc/init.d/functions   ] ; then init_mode="chkconfig-lsb" ; fi
+if [ -r /etc/rc.status          ] ; then init_mode="insserv-lsb"   ; fi
+else
+if [ -r /etc/init.d/functions   ] ; then . /etc/init.d/functions ; init_mode="chkconfig" ; else
+if [ -r /etc/rc.status          ] ; then . /etc/rc.status        ; init_mode="insserv"   ; fi ; fi
+fi
+
+case "$init_mode" in
+    (chkconfig)
+	start_daemon() {
+	    local force= nicelevel=
+	    while [ "$1" != "${1##[-+]}" ] ; do
+		case $1 in
+		    (-f) force="--force" ; shift 1 ;;
+		    (-n) nicelevel="$2"  ; shift 2 ;;
+		esac
+	    done
+	    daemon $force $nicelevel $*
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$1
+	    return $RETVAL
+	}
+	;;
+    (chkconfig-lsb)
+	;;
+    (insserv|insserv-lsb)
+	action() {
+	    echo -en "$1"
+	    shift 1
+	    ${1+"$@"}
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] || rc_failed $RETVAL
+	    rc_status -v
+	    return $RETVAL
+	}
+	;;
+    (lsb)
+	action() {
+	    echo -en "$1"
+	    shift 1
+	    ${1+"$@"}
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] && log_success_msg || log_failure_msg
+	    return $?
+	}
+	;;
+    (standalone|*)
+	start_daemon() {
+	    local force= nicecmd=
+	    while [ "$1" != "${1##[-+]}" ] ; do
+		case $1 in
+		    (-f) force="--force"       ; shift 1 ;;
+		    (-n) nicecmd="nice -n $2"  ; shift 2 ;;
+		esac
+	    done
+	    ( $* >/dev/null 2>&1 </dev/null & )
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$1
+	    return $RETVAL
+	}
+	action() {
+	    echo -en "$1"
+	    shift 1
+	    ${1+"$@"}
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] && echo -e "\t...SUCCESS" || echo -e "\t....FAILED"
+	    return $?
+	}
+	if [ -x /sbin/pidof ] ; then
+	    pidofproc() {
+		/sbin/pidof $@
+	    }
+	elif [ -x /sbin/pidofproc ] ; then
+	    pidofproc() {
+		/sbin/pidofproc $@
+	    }
+	else
+	    pidofproc() {
+		[ -r $pidfile ] && cat $pidfile
+	    }
+	fi
+	if [ -x /sbin/killproc ] ; then
+	    killproc() {
+		/sbin/killproc $@
+	    }
+	elif [ -x /usr/bin/killall ] ; then
+	    killproc() {
+		/usr/bin/killall $@
+	    }
+	else
+	    killproc() {
+		[ -r $pidfile ] && kill "$2" `cat $pidfile`
+	    }
+	fi
+	;;
+esac
 
 name='strace'
 lockfile="/var/lock/subsys/$name"
@@ -51,7 +151,11 @@ processname="$name"
 pidfile="/var/run/$processname.pid"
 execfile="/usr/sbin/$processname"
 
-[ -x $execfile ] || exit 0
+if [ ! -x $execfile ] ; then if [ "$1" = "stop" ] ; then exit 0 ; else exit 5 ; fi ; fi
+
+# Disable for the moment
+
+if [ "$1" = "stop" ] ; then exit 0 ; else exit 5 ; fi
 
 # Specify defaults
 
@@ -73,8 +177,28 @@ RETVAL=0
 
 umask 077
 
+build_options() {
+    # Build up the options string
+    STRACE_OPTIONS="-p $pidfile"
+    [ -n "$STRACEOPTIONS" ] && \
+	STRACE_OPTIONS="${STRACE_OPTIONS:+ }${STRACEOPTIONS}"
+    [ -n "$STRACE_DIRECTORY" ] && \
+	STRACE_OPTIONS="${STRACE_OPTIONS:+ }-d ${STRACE_DIRECTORY}"
+    [ -n "$STRACE_BASENAME" ] && \
+	STRACE_OPTIONS="${STRACE_OPTIONS:+ }-b ${STRACE_BASENAME}"
+    [ -n "$STRACE_OUTFILE" ] && \
+	STRACE_OPTIONS="${STRACE_OPTIONS:+ }-o ${STRACE_OUTFILE}"
+    [ -n "$STRACE_ERRFILE" ] && \
+	STRACE_OPTIONS="${STRACE_OPTIONS:+ }-e ${STRACE_ERRFILE}"
+    [ -n "$STRACE_LOGDEVICE" ] && \
+	STRACE_OPTIONS="${STRACE_OPTIONS:+ }-l ${STRACE_LOGDEVICE}"
+    [ -n "$STRACE_MODULES" ] && \
+	STRACE_OPTIONS="${STRACE_OPTIONS:+ }${STRACE_MODULES}"
+}
+
 start() {
-    daemon $processname $STRACE_OPTIONS
+    build_options
+    start_daemon $processname $STRACE_OPTIONS
     RETVAL=$?
     [ $RETVAL -eq 0 ] && touch $lockfile
     RETVAL=$?
@@ -101,41 +225,20 @@ reload() {
     return $?
 }
 
-build_options() {
-    # Build up the options string
-    STRACE_OPTIONS="-p $pidfile"
-    [ -n "$STRACEOPTIONS" ] && \
-	STRACE_OPTIONS="${STRACE_OPTIONS:+ }${STRACEOPTIONS}"
-    [ -n "$STRACE_DIRECTORY" ] && \
-	STRACE_OPTIONS="${STRACE_OPTIONS:+ }-d ${STRACE_DIRECTORY}"
-    [ -n "$STRACE_BASENAME" ] && \
-	STRACE_OPTIONS="${STRACE_OPTIONS:+ }-b ${STRACE_BASENAME}"
-    [ -n "$STRACE_OUTFILE" ] && \
-	STRACE_OPTIONS="${STRACE_OPTIONS:+ }-o ${STRACE_OUTFILE}"
-    [ -n "$STRACE_ERRFILE" ] && \
-	STRACE_OPTIONS="${STRACE_OPTIONS:+ }-e ${STRACE_ERRFILE}"
-    [ -n "$STRACE_LOGDEVICE" ] && \
-	STRACE_OPTIONS="${STRACE_OPTIONS:+ }-l ${STRACE_LOGDEVICE}"
-    [ -n "$STRACE_MODULES" ] && \
-	STRACE_OPTIONS="${STRACE_OPTIONS:+ }${STRACE_MODULES}"
-}
-
 case "$1" in
     (start|stop|reload|restart)
-	build_options
 	$1 || RETVAL=$?
 	;;
     (status)
 	$1 $name || RETVAL=$?
 	;;
     (condrestart)
-	build_options
 	[ -f $lockfile ] && restart || RETVAL=$?
 	;;
     (probe)
-	if /sbin/pidof $processname >/dev/null 2>&1 ; then
+	if pidofproc $processname >/dev/null 2>&1 ; then
 	    # running
-	    if [ "`/sbin/pidof $processname`" -eq "`cat $pidfile`" ] ; then
+	    if [ "`pidofproc $processname`" -eq "`cat $pidfile`" ] ; then
 		# running with the right pid
 		if [ ! -f $lockfile ] ; then
 		    # running but subsystem unlocked, need to reload
@@ -176,7 +279,7 @@ esac
 
 # =============================================================================
 # 
-# @(#) $RCSfile: strace,v $ $Name:  $($Revision: 1.1.2.1 $) $Date: 2005/03/13 06:28:07 $
+# @(#) $RCSfile: strace,v $ $Name:  $($Revision: 1.1.2.2 $) $Date: 2005/12/16 09:26:07 $
 #
 # -----------------------------------------------------------------------------
 #
@@ -222,7 +325,7 @@ esac
 #
 # -----------------------------------------------------------------------------
 #
-# Last Modified $Date: 2005/03/13 06:28:07 $ by $Author: brian $
+# Last Modified $Date: 2005/12/16 09:26:07 $ by $Author: brian $
 #
 # =============================================================================
 
diff --git a/LiS/util/init/streams b/LiS/util/init/streams
--- a/LiS/util/init/streams
+++ b/LiS/util/init/streams
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 #
-# @(#) $RCSfile: streams,v $ $Name:  $($Revision: 1.1.2.6 $) $Date: 2005/06/28 03:17:24 $
+# @(#) $RCSfile: streams,v $ $Name:  $($Revision: 1.1.2.7 $) $Date: 2005/12/16 09:26:07 $
 # Copyright (c) 2001-2005  OpenSS7 Corporation <http://www.openss7.com>
 # Copyright (c) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>
 # All Rights Reserved.
@@ -28,25 +28,70 @@
 #
 ### BEGIN INIT INFO
 # Provides: streams
+# Required-Start: $local_fs
+# Required-Stop: $local_fs
 # Default-Start: 2 3 4 5
 # Default-Stop: 0 1 6
+# X-UnitedLinux-Default-Enabled: yes
 # Short-Description: start and stop streams subsystem
 # License: GPL
 # Description:	This STREAMS init script is part of Linux Fast-STREAMS.  It is
 #	reponsible for ensuring that the necessary STREAMS character devices are
 #	present in the /dev directory and that the STREAMS subsystem is
-#	configured and loaded.  It is also responsible for starting the STREAMS
-#	log and trace facilities.
+#	configured and loaded.
 ### END INIT INFO
 
 # Source init script functions library.
-. /etc/init.d/functions
+init_mode="standalone"
+if [ -r /lib/lsb/init-functions ] ; then . /lib/lsb/init-functions ; init_mode="lsb" ;
+if [ -r /etc/init.d/functions   ] ; then init_mode="chkconfig" ; fi
+if [ -r /etc/rc.status          ] ; then init_mode="insserv"   ; fi
+else
+if [ -r /etc/init.d/functions   ] ; then . /etc/init.d/functions ; init_mode="chkconfig" ; else
+if [ -r /etc/rc.status          ] ; then . /etc/rc.status        ; init_mode="insserv"   ; fi ; fi
+fi
+
+case "$init_mode" in
+    (chkconfig)
+	;;
+    (insserv)
+	action() {
+	    echo -en "$1"
+	    shift 1
+	    ${1+"$@"}
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] || rc_failed $RETVAL
+	    rc_status -v
+	    return $RETVAL
+	}
+	;;
+    (lsb)
+	action() {
+	    echo -en "$1"
+	    shift 1
+	    ${1+"$@"}
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] && log_success_msg || log_failure_msg
+	    return $?
+	}
+	;;
+    (standalone|*)
+	action() {
+	    echo -en "$1"
+	    shift 1
+	    ${1+"$@"}
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] && echo -e "\t...SUCCESS" || echo -e "\t....FAILED"
+	    return $?
+	}
+	;;
+esac
 
 name='streams'
 lockfile="/var/lock/subsys/$name"
 config="/etc/sysconfig/$name"
 
-[ -f /proc/modules ] || exit 0
+if [ ! -e /proc/modules ] ; then if [ "$1" = "stop" ] ; then exit 0 ; else exit 5 ; fi ; fi
 
 for STREAMS_MKNOD in /sbin/strmakenodes /usr/sbin/strmakenodes /bin/strmakenodes /usr/bin/strmakenodes ; do
     if [ -x $STREAMS_MKNOD ] ; then
@@ -58,6 +103,8 @@ done
 
 # Specify defaults
 
+#STREAMS_MODULES="streams streams-liskmod streams-mtdrv streams-pipemod"
+STREAMS_MODULES="streams"
 STREAMS_MAKEDEVICES="no"
 STREAMS_REMOVEDEVICES="no"
 STREAMS_MOUNTSPECFS="yes"
@@ -76,7 +123,7 @@ RETVAL=0
 umask 077
 
 start() {
-    for module in streams streams-liskmod streams-mtdrv streams-pipemod ; do
+    for module in $STREAMS_MODULES ; do
 	if ! grep "^$module"'[[:space:]]' /proc/modules >/dev/null 2>&1 ; then
 	    action $"Loading kernel module $module: " \
 		modprobe -k -q -- $module
@@ -88,9 +135,9 @@ start() {
 	action $"Reconfiguring kernel parameters: " \
 	    sysctl -e -p /etc/sysctl.conf || :
     fi
-    if [ -f /etc/streams.conf ] ; then
+    if [ -f /etc/${name}.conf ] ; then
 	action $"Configuring STREAMS parameters: " \
-	    sysctl -e -p /etc/streams.conf || :
+	    sysctl -e -p /etc/${name}.conf || :
     fi
     if [ -n "$STREAMS_MKNOD" -a ":$STREAMS_MAKEDEVICES" = ":yes" ] ; then
 	action $"Making STREAMS devices: " \
@@ -112,6 +159,7 @@ remove_modules() {
 		rmmod $modules
 	RETVAL=$?
     fi
+    RETVAL=0
     return $RETVAL
 }
 
@@ -146,7 +194,7 @@ case "$1" in
 	;;
     (status)
 	LOADED='yes'
-	for module in streams streams-liskmod streams-mtdrv streams-pipemod ; do
+	for module in $STREAMS_MODULES ; do
 	    if ! grep "^$module"'[[:space:]]' /proc/modules >/dev/null 2>&1 ; then
 		LOADED='no'
 		break
@@ -167,12 +215,12 @@ case "$1" in
 	    fi
 	fi
 	;;
-    (condrestart)
+    (force-reload|try-restart|condrestart)
 	[ -f $lockfile ] && restart || RETVAL=$?
 	;;
     (probe)
 	LOADED='yes'
-	for module in streams streams-liskmod streams-mtdrv streams-pipemod ; do
+	for module in $STREAMS_MODULES ; do
 	    if ! grep "^$module"'[[:space:]]' /proc/modules >/dev/null 2>&1 ; then
 		LOADED='no'
 		break
@@ -214,7 +262,7 @@ case "$1" in
 	RETVAL=$?
 	;;
     (*)
-	echo "Usage: $0 (start|stop|status|restart|condrestart|probe)"
+	echo "Usage: $0 (start|stop|status|restart|try-restart|condrestart|force-reload|reload|probe)"
 	;;
 esac
 
@@ -222,7 +270,7 @@ esac
 
 # =============================================================================
 # 
-# @(#) $RCSfile: streams,v $ $Name:  $($Revision: 1.1.2.6 $) $Date: 2005/06/28 03:17:24 $
+# @(#) $RCSfile: streams,v $ $Name:  $($Revision: 1.1.2.7 $) $Date: 2005/12/16 09:26:07 $
 #
 # -----------------------------------------------------------------------------
 #
@@ -268,7 +316,7 @@ esac
 #
 # -----------------------------------------------------------------------------
 #
-# Last Modified $Date: 2005/06/28 03:17:24 $ by $Author: brian $
+# Last Modified $Date: 2005/12/16 09:26:07 $ by $Author: brian $
 #
 # =============================================================================
 
diff --git a/strbcm/scripts/install_initd b/strbcm/scripts/install_initd
--- a/strbcm/scripts/install_initd
+++ b/strbcm/scripts/install_initd
@@ -1,7 +1,7 @@
 #!/bin/bash
 # =============================================================================
 # 
-# @(#) $RCSfile: install_initd,v $ $Name:  $($Revision: 0.9.2.4 $) $Date: 2005/02/16 09:51:34 $
+# @(#) $RCSfile: install_initd,v $ $Name:  $($Revision: 0.9.2.5 $) $Date: 2005/12/16 09:24:55 $
 #
 # -----------------------------------------------------------------------------
 #
@@ -47,11 +47,11 @@
 #
 # -----------------------------------------------------------------------------
 #
-# Last Modified $Date: 2005/02/16 09:51:34 $ by $Author: brian $
+# Last Modified $Date: 2005/12/16 09:24:55 $ by $Author: brian $
 #
 # =============================================================================
 
-ident='@(#) $RCSfile: install_initd,v $ $Name:  $($Revision: 0.9.2.4 $) $Date: 2005/02/16 09:51:34 $'
+ident='@(#) $RCSfile: install_initd,v $ $Name:  $($Revision: 0.9.2.5 $) $Date: 2005/12/16 09:24:55 $'
 
 ECHO='echo'
 SHELL='/bin/bash'
@@ -61,7 +61,7 @@ SED='sed'
 if test "X$1" = X--no-reexec; then
     # Discard the --no-reexec flag, and continue
     shift
-elif test "X`($ECHO '\t')` 2>/dev/null " = 'X\t'; then
+elif test "X`($ECHO '\t') 2>/dev/null`" = 'X\t'; then
     :
 else
     exec $SHELL "$0" --no-reexec ${1+"$@"}
@@ -445,7 +445,7 @@ initname="$(basename $filename)"
 initrddir="$(dirname $filename)"
 
 if [ ! -d "${initrddir:-.}" ] ; then
-    $ECHO "error: directory '${initrddir:-.}' does not exist"
+    $ECHO "error: directory '${initrddir:-.}' does not exist" >&2
     exit 1
 fi
 
@@ -453,7 +453,7 @@ initrddir=`(cd $initrddir ; pwd)`
 filename="$initrddir/$initname"
 
 if [ ! -f "$filename" ] ; then
-    $ECHO "error: file '${filename}' does not exist"
+    $ECHO "error: file '${filename}' does not exist" >&2
     exit 1
 fi
 
@@ -463,7 +463,71 @@ if [ "$basedir" != init.d ] ; then
     $ECHO "warning: path to init.d file should have init.d as its last component instead of $basedir" >&2
 fi
 
-initroot=$(dirname $initrddir)
+rootdir="${initrddir}"
+rootdir=${rootdir//\/rc.d/}
+rootdir=${rootdir//\/init.d/}
+rootdir=${rootdir//\/etc/}
+
+# If we are installing on the host, we might as well use the host's
+# own install function, if one exists
+
+if [ -z "$rootdir" ] ; then
+    if [ -x /usr/lib/lsb/install_initd ] ; then
+	$ECHO " /usr/lib/lsb/install_initd $filename"
+	/usr/lib/lsb/install_initd $filename
+	exit $?
+    fi
+    if [ -x /sbin/insserv ] ; then
+	$ECHO " /sbin/insserv -v $filename"
+	/sbin/insserv -v $filename
+	exit $?
+    fi
+    if [ -x /sbin/chkconfig ] ; then
+	$ECHO " /sbin/chkconfig --add $initname"
+	/sbin/chkconfig --add $initname
+	RETVAL=$?
+	[ $RETVAL -eq 0 ] && /sbin/chkconfig --list $initname
+	exit $RETVAL
+    fi
+fi
+
+sysconfdir="${rootdir}/etc"
+
+#
+# There are three situations here:
+#
+# RedHat-like system shave a real /etc/rc.d/init.d directory and a symbolic link from /etc/init.d
+# Debian systems have no rc.d, place all the rcX.d directories in /etc, and /etc/init.d is real.
+# SuSE/UL systems have a real /etc/init.d directory and a symbolic link from /etc/rc.d to /etc/init.d
+#
+# This means
+# - symbolic links for RedHat  from an rcX.d directory go to ../init.d/scriptname.
+# - symbolic links for Debian  from an rcX.d directory go to ../init.d/scriptname.
+# - symbolic links for SuSE/UL from an rcX.d directory go to ../scriptname
+#
+# Now, for
+# - Redhat,  rcX.d directories are in /etc/rc.d
+# - Debian,  rcX.d directories are in /etc
+# - SuSE/UL, rcX.d directories are in /etc/init.d
+#
+# so that is how we detect which system we are installing for.
+#
+if [ -d $sysconfdir/rc0.d ] ; then
+    rcdir="${sysconfdir}"
+    basedir="init.d"
+    flavor="update-rc.d"
+elif [ -d $sysconfdir/init.d/rc0.d ] ; then
+    rcdir="${sysconfdir}/init.d"
+    basedir=""
+    flavor="insserv"
+elif [ -d $sysconfdir/rc.d/rc0.d ] ; then
+    rcdir="${sysconfdir}/rc.d"
+    basedir="init.d"
+    flavor="chkconfig"
+else
+    $ECHO "error: $program cannot grok SysV init for $initname" >&2
+    exit 1
+fi
 
 install_links() {
     while [ -n "$1" ] ; do
@@ -472,24 +536,24 @@ install_links() {
 	shift 2
 	while [ -n "$1" ] ; do
 	    if [ "$1" = '.' ] ; then shift ; break ; fi
-	    [ -d $initroot/rc${1}.d ] || {
-		[ $verbose -gt 1 ] && echo " mkdir -p -- $initroot/rc${1}.d"
-		mkdir -p -- $initroot/rc${1}.d
+	    [ -d $rcdir/rc${1}.d ] || {
+		[ $verbose -gt 1 ] && echo " mkdir -p -- $rcdir/rc${1}.d"
+		mkdir -p -- $rcdir/rc${1}.d
 	    }
-	    pushd $initroot/rc${1}.d >/dev/null
+	    pushd $rcdir/rc${1}.d >/dev/null
 	    case "$cmd" in
 		(start)
-		    [ -L S${prio}${initname} -a "$(readlink S${prio}${initname})" = ../$basedir/$initname ] \
+		    [ -L S${prio}${initname} -a "$(readlink S${prio}${initname})" = ../${basedir:+$basedir/}$initname ] \
 		    || {
-			[ $verbose -gt 1 ] && echo " cd `pwd` ; rm -f -- S${prio}${initname} ; ln -sf ../$basedir/$initname S${prio}${initname}"
-			rm -f -- S${prio}${initname} ; ln -sf ../$basedir/$initname S${prio}${initname}
+			[ $verbose -gt 1 ] && echo " cd `pwd` ; rm -f -- S${prio}${initname} ; ln -sf ../${basedir:+$basedir/}$initname S${prio}${initname}"
+			rm -f -- S${prio}${initname} ; ln -sf ../${basedir:+$basedir/}$initname S${prio}${initname}
 		    }
 		    ;;
 		(stop)
-		    [ -L K${prio}${initname} -a "$(readlink K${prio}${initname})" = ../$basedir/$initname ] \
+		    [ -L K${prio}${initname} -a "$(readlink K${prio}${initname})" = ../${basedir:+$basedir/}$initname ] \
 		    || {
-			[ $verbose -gt 1 ] && echo " cd `pwd` ; rm -f -- K${prio}${initname} ; ln -sf ../$basedir/$initname K${prio}${initname}"
-			rm -f -- K${prio}${initname} ; ln -sf ../$basedir/$initname K${prio}${initname}
+			[ $verbose -gt 1 ] && echo " cd `pwd` ; rm -f -- K${prio}${initname} ; ln -sf ../${basedir:+$basedir/}$initname K${prio}${initname}"
+			rm -f -- K${prio}${initname} ; ln -sf ../${basedir:+$basedir/}$initname K${prio}${initname}
 		    }
 		    ;;
 	    esac
@@ -528,32 +592,38 @@ install_from_lsbconfig() {
     install_links start $sprio $slevs . stop $kprio $klevs .
 }
 
-debsearch='^#[[:space:]][[:space:]]*update-rc\.d:\([[:space:]][[:space:]]*\(start\|stop\)[[:space:]][[:space:]]*[0-9][0-9]\([[:space:]][[:space:]]*[0-6S]\)*[[:space:]][[:space:]]*\.\)*[[:space:]]*$'
-if grep "$debsearch" $filename >/dev/null 2>&1 ; then
-    cat $filename | sed -e "\,$debsearch,!d" | \
-    while read line ; do
-	install_from_debconfig $line
-    done
-    exit $?
+if [ $flavor = "update-rc.d" -o $flavor = "none" ] ; then
+    debsearch='^#[[:space:]][[:space:]]*update-rc\.d:\([[:space:]][[:space:]]*\(start\|stop\)[[:space:]][[:space:]]*[0-9][0-9]\([[:space:]][[:space:]]*[0-6S]\)*[[:space:]][[:space:]]*\.\)*[[:space:]]*$'
+    if grep "$debsearch" $filename >/dev/null 2>&1 ; then
+	cat $filename | sed -e "\,$debsearch,!d" | \
+	while read line ; do
+	    install_from_debconfig $line
+	done
+	exit $?
+    fi
 fi
 
-chksearch='#[[:space:]][[:space:]]*chkconfig:[[:space:]][[:space:]]*[-0-7][0-7]*[[:space:]][[:space:]]*[0-9][0-9][[:space:]][[:space:]]*[0-9][0-9][[:space:]]*$'
-if grep "$chksearch" $filename >/dev/null 2>&1
-then
-    cat $filename | sed -e "\,$chksearch,!d" | \
-    while read line ; do
-	install_from_chkconfig $line
-    done
-    exit $?
+if [ $flavor = "chkconfig" -o $flavor = "none" ] ; then
+    chksearch='#[[:space:]][[:space:]]*chkconfig:[[:space:]][[:space:]]*[-0-7][0-7]*[[:space:]][[:space:]]*[0-9][0-9][[:space:]][[:space:]]*[0-9][0-9][[:space:]]*$'
+    if grep "$chksearch" $filename >/dev/null 2>&1
+    then
+	cat $filename | sed -e "\,$chksearch,!d" | \
+	while read line ; do
+	    install_from_chkconfig $line
+	done
+	exit $?
+    fi
 fi
 
-if grep '^### BEGIN INIT INFO[[:space:]]*$' $filename >/dev/null 2>&1
-then
-    install_from_lsbconfig "$(cat $filename | sed -e '\,^### BEGIN INIT INFO[[:space:]]*$,,\,^### END INIT INFO[[:space:]]*$,!d')"
-    exit $?
+if [ $flavor = "insserv" -o $flavor = "none" ] ; then
+    if grep '^### BEGIN INIT INFO[[:space:]]*$' $filename >/dev/null 2>&1
+    then
+	install_from_lsbconfig "$(cat $filename | sed -e '\,^### BEGIN INIT INFO[[:space:]]*$,,\,^### END INIT INFO[[:space:]]*$,!d')"
+	exit $?
+    fi
 fi
 
-$ECHO "service $initname does not support $program" >&2
+$ECHO "error: service $initname does not support $program" >&2
 exit 1
 
 # vim: ft=sh sw=4
diff --git a/strcompat/src/util/init/strcompat b/strcompat/src/util/init/strcompat
--- a/strcompat/src/util/init/strcompat
+++ b/strcompat/src/util/init/strcompat
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# @(#) $RCSfile: strcompat,v $ $Name:  $($Revision: 0.9.2.1 $) $Date: 2005/07/04 19:29:20 $
+# @(#) $RCSfile: strcompat,v $ $Name:  $($Revision: 0.9.2.2 $) $Date: 2005/12/16 09:26:08 $
 # Copyright (c) 2001-2005  OpenSS7 Corporation <http://www.openss7.com>
 # Copyright (c) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>
 # All Rights Reserved.
@@ -32,23 +32,66 @@
 # Required-Stop: streams
 # Default-Start: 2 3 4 5
 # Default-Stop: 0 1 6
+# X-UnitedLinux-Default-Enabled: yes
 # Short-Description: start and stop strcompat subsystem
 # License: GPL
 # Description:	This STREAMS init script is part of Linux Fast-STREAMS.  It is
 #	reponsible for ensuring that the necessary STREAMS character devices are
-#	present in the /dev directory and that the STREAMS subsystem is
-#	configured and loaded.  It is also responsible for starting the STREAMS
-#	log and trace facilities.
+#	present in the /dev directory and that the compatibility subsystem is
+#	configured and loaded.
 ### END INIT INFO
 
 # Source init script functions library.
-. /etc/init.d/functions
+init_mode="standalone"
+if [ -r /lib/lsb/init-functions ] ; then . /lib/lsb/init-functions ; init_mode="lsb" ;
+if [ -r /etc/init.d/functions   ] ; then init_mode="chkconfig" ; fi
+if [ -r /etc/rc.status          ] ; then init_mode="insserv"   ; fi
+else
+if [ -r /etc/init.d/functions   ] ; then . /etc/init.d/functions ; init_mode="chkconfig" ; else
+if [ -r /etc/rc.status          ] ; then . /etc/rc.status        ; init_mode="insserv"   ; fi ; fi
+fi
+
+case "$init_mode" in
+    (chkconfig)
+	;;
+    (insserv)
+	action() {
+	    echo -en "$1"
+	    shift 1
+	    ${1+"$@"}
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] || rc_failed $RETVAL
+	    rc_status -v
+	    return $RETVAL
+	}
+	;;
+    (lsb)
+	action() {
+	    echo -en "$1"
+	    shift 1
+	    ${1+"$@"}
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] && log_success_msg || log_failure_msg
+	    return $?
+	}
+	;;
+    (standalone|*)
+	action() {
+	    echo -en "$1"
+	    shift 1
+	    ${1+"$@"}
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] && echo -e "\t...SUCCESS" || echo -e "\t....FAILED"
+	    return $?
+	}
+	;;
+esac
 
 name='strcompat'
 lockfile="/var/lock/subsys/$name"
 config="/etc/sysconfig/$name"
 
-[ -f /proc/modules ] || exit 0
+if [ ! -e /proc/modules ] ; then if [ "$1" = "stop" ] ; then exit 0 ; else exit 5 ; fi ; fi
 
 for STRCOMPAT_MKNOD in /sbin/strcompat_mknod /usr/sbin/strcompat_mknod /bin/strcompat_mknod /usr/bin/strcompat_mknod ; do
     if [ -x $STRCOMPAT_MKNOD ] ; then
@@ -165,7 +208,7 @@ stop() {
 	    $STRCOMPAT_MKNOD --remove
 	RETVAL=$?
     fi
-    [ $RETVAL -eq 0 ] && egrep '^streams[-]?' /proc/modules 2>/dev/null | remove_modules
+    [ $RETVAL -eq 0 ] && egrep '^streams[-_]?' /proc/modules 2>/dev/null | remove_modules
     RETVAL=$?
     [ $RETVAL -eq 0 ] && rm -f -- $lockfile
     RETVAL=$?
@@ -211,7 +254,7 @@ case "$1" in
 	    fi
 	fi
 	;;
-    (condrestart)
+    (force-reload|try-restart|condrestart)
 	[ -f $lockfile ] && restart || RETVAL=$?
 	;;
     (probe)
@@ -258,7 +301,7 @@ case "$1" in
 	RETVAL=$?
 	;;
     (*)
-	echo "Usage: $0 (start|stop|status|restart|condrestart|probe)"
+	echo "Usage: $0 (start|stop|status|restart|try-restart|condrestart|force-reload|reload|probe)"
 	;;
 esac
 
@@ -266,7 +309,7 @@ esac
 
 # =============================================================================
 # 
-# @(#) $RCSfile: strcompat,v $ $Name:  $($Revision: 0.9.2.1 $) $Date: 2005/07/04 19:29:20 $
+# @(#) $RCSfile: strcompat,v $ $Name:  $($Revision: 0.9.2.2 $) $Date: 2005/12/16 09:26:08 $
 #
 # -----------------------------------------------------------------------------
 #
@@ -312,7 +355,7 @@ esac
 #
 # -----------------------------------------------------------------------------
 #
-# Last Modified $Date: 2005/07/04 19:29:20 $ by $Author: brian $
+# Last Modified $Date: 2005/12/16 09:26:08 $ by $Author: brian $
 #
 # =============================================================================
 
diff --git a/strinet/src/util/init/strinet b/strinet/src/util/init/strinet
--- a/strinet/src/util/init/strinet
+++ b/strinet/src/util/init/strinet
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 #
-# @(#) $RCSfile: strinet,v $ $Name:  $($Revision: 0.9.2.2 $) $Date: 2005/06/22 09:44:17 $
+# @(#) $RCSfile: strinet,v $ $Name:  $($Revision: 0.9.2.3 $) $Date: 2005/12/16 09:26:09 $
 # Copyright (c) 2001-2005  OpenSS7 Corporation <http://www.openss7.com>
 # Copyright (c) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>
 # All Rights Reserved.
@@ -26,10 +26,11 @@
 #
 ### BEGIN INIT INFO
 # Provides: strinet
-# Required-Start: streams
-# Required-Stop: streams
+# Required-Start: streams $network
+# Required-Stop: streams $network
 # Default-Start: 3 4 5
 # Default-Stop: 0 1 2 6
+# X-UnitedLinux-Default-Enabled: yes
 # Short-Description: start and stop STREAMS INET subsystem
 # License: GPL
 # Description:	This STREAMS INET init script is part of Linux Fast-STREAMS.
@@ -39,13 +40,56 @@
 ### END INIT INFO
 
 # Source init script functions library.
-. /etc/init.d/functions
+init_mode="standalone"
+if [ -r /lib/lsb/init-functions ] ; then . /lib/lsb/init-functions ; init_mode="lsb" ;
+if [ -r /etc/init.d/functions   ] ; then init_mode="chkconfig" ; fi
+if [ -r /etc/rc.status          ] ; then init_mode="insserv"   ; fi
+else
+if [ -r /etc/init.d/functions   ] ; then . /etc/init.d/functions ; init_mode="chkconfig" ; else
+if [ -r /etc/rc.status          ] ; then . /etc/rc.status        ; init_mode="insserv"   ; fi ; fi
+fi
+
+case "$init_mode" in
+    (chkconfig)
+	;;
+    (insserv)
+	action() {
+	    echo -en "$1"
+	    shift 1
+	    ${1+"$@"}
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] || rc_failed $RETVAL
+	    rc_status -v
+	    return $RETVAL
+	}
+	;;
+    (lsb)
+	action() {
+	    echo -en "$1"
+	    shift 1
+	    ${1+"$@"}
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] && log_success_msg || log_failure_msg
+	    return $?
+	}
+	;;
+    (standalone|*)
+	action() {
+	    echo -en "$1"
+	    shift 1
+	    ${1+"$@"}
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] && echo -e "\t...SUCCESS" || echo -e "\t....FAILED"
+	    return $?
+	}
+	;;
+esac
 
 name='strinet'
 lockfile="/var/lock/subsys/$name"
 config="/etc/sysconfig/$name"
 
-[ -f /proc/modules ] || exit 0
+if [ ! -e /proc/modules ] ; then if [ "$1" = "stop" ] ; then exit 0 ; else exit 5 ; fi ; fi
 
 for STRINET_MKNOD in /sbin/${name}_mknod /usr/sbin/${name}_mknod /bin/${name}_mknod /usr/bin/${name}_mknod ; do
     if [ -x $STRINET_MKNOD ] ; then
@@ -73,6 +117,7 @@ done
 
 # Specify defaults
 
+STRINET_MODULES="streams-inet"
 STRINET_MAKEDEVICES="no"
 STRINET_REMOVEDEVICES="no"
 
@@ -89,7 +134,7 @@ RETVAL=0
 umask 077
 
 start() {
-    for module in streams-inet ; do
+    for module in $STRINET_MODULES ; do
 	if ! grep "^$module"'[[:space:]]' /proc/modules >/dev/null 2>&1 ; then
 	    action $"Loading kernel module $module: " \
 		modprobe -k -q -- $module
@@ -97,13 +142,13 @@ start() {
 	    [ $RETVAL -eq 0 ] || return $RETVAL
 	fi
     done
-    if grep '^[[:space:]]*'$name'[/.]' /etc/sysctl.conf >/dev/null 2>&1 ; then
+    if grep '^[[:space:]]*'${name}'[/.]' /etc/sysctl.conf >/dev/null 2>&1 ; then
 	action $"Reconfiguring kernel parameters: " \
 	    sysctl -e -p /etc/sysctl.conf || :
     fi
-    if [ -f /etc/$name.conf ] ; then
+    if [ -f /etc/${name}.conf ] ; then
 	action $"Configuring STREAMS INET parameters: " \
-	    sysctl -e -p /etc/$name.conf || :
+	    sysctl -e -p /etc/${name}.conf || :
     fi
     if [ -n "$STRINET_MKNOD" -o -n "$INET_MKDEV" ] ; then
 	if [ ":$STRINET_MAKEDEVICES" = ":yes" ] ; then
@@ -178,7 +223,7 @@ case "$1" in
 	;;
     (status)
 	LOADED='yes'
-	for module in streams-inet ; do
+	for module in $STRINET_MODULES ; do
 	    if ! grep "^$module"'[[:space:]]' /proc/modules >/dev/null 2>&1 ; then
 		LOADED='no'
 		break
@@ -199,12 +244,12 @@ case "$1" in
 	    fi
 	fi
 	;;
-    (condrestart)
+    (force-reload|try-restart|condrestart)
 	[ -f $lockfile ] && restart || RETVAL=$?
 	;;
     (probe)
 	LOADED='yes'
-	for module in streams-inet ; do
+	for module in $STRINET_MODULES ; do
 	    if ! grep "^$module"'[[:space:]]' /proc/modules >/dev/null 2>&1 ; then
 		LOADED='no'
 		break
@@ -246,7 +291,7 @@ case "$1" in
 	RETVAL=$?
 	;;
     (*)
-	echo "Usage: $0 (start|stop|status|restart|condrestart|probe)"
+	echo "Usage: $0 (start|stop|status|restart|try-restart|condrestart|force-reload|reload|probe)"
 	;;
 esac
 
@@ -254,7 +299,7 @@ esac
 
 # =============================================================================
 # 
-# @(#) $RCSfile: strinet,v $ $Name:  $($Revision: 0.9.2.2 $) $Date: 2005/06/22 09:44:17 $
+# @(#) $RCSfile: strinet,v $ $Name:  $($Revision: 0.9.2.3 $) $Date: 2005/12/16 09:26:09 $
 #
 # -----------------------------------------------------------------------------
 #
@@ -300,7 +345,7 @@ esac
 #
 # -----------------------------------------------------------------------------
 #
-# Last Modified $Date: 2005/06/22 09:44:17 $ by $Author: brian $
+# Last Modified $Date: 2005/12/16 09:26:09 $ by $Author: brian $
 #
 # =============================================================================
 
diff --git a/strutil/src/util/init/strerr b/strutil/src/util/init/strerr
--- a/strutil/src/util/init/strerr
+++ b/strutil/src/util/init/strerr
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 #
-# @(#) $RCSfile: strerr,v $ $Name:  $($Revision: 0.9.2.6 $) $Date: 2005/02/18 01:36:07 $
+# @(#) $RCSfile: strerr,v $ $Name:  $($Revision: 0.9.2.7 $) $Date: 2005/12/16 09:26:10 $
 # Copyright (c) 2001-2005  OpenSS7 Corporation <http://www.openss7.com>
 # Copyright (c) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>
 # All Rights Reserved.
@@ -11,7 +11,7 @@
 # Redhat chkconfig init script conventions
 #
 # strerr:	start and stop strerr facility
-# chkconfig:	- 55 55
+# chkconfig:	- 03 96
 # lockfile:	/var/lock/subsys/strerr
 # config:	/etc/default/strerr
 # processname:	strerr
@@ -33,6 +33,7 @@
 # Required-Stop: streams
 # Default-Start: 
 # Default-Stop: 0 1 2 3 4 5 6
+# X-UnitedLinux-Default-Enabled: no
 # Short-Description: start and stop strerr
 # License: GPL
 # Description:	This STREAMS init script is part of Linux Fast-STREAMS.  It is
@@ -42,15 +43,117 @@
 ### END INIT INFO
 
 # Source init script functions library
-[ -f /etc/init.d/functions ] && . /etc/init.d/functions
+init_mode="standalone"
+if [ -r /lib/lsb/init-functions ] ; then . /lib/lsb/init-functions ; init_mode="lsb" ;
+if [ -r /etc/init.d/functions   ] ; then init_mode="chkconfig-lsb" ; fi
+if [ -r /etc/rc.status          ] ; then init_mode="insserv-lsb"   ; fi
+else
+if [ -r /etc/init.d/functions   ] ; then . /etc/init.d/functions ; init_mode="chkconfig" ; else
+if [ -r /etc/rc.status          ] ; then . /etc/rc.status        ; init_mode="insserv"   ; fi ; fi
+fi
+
+case "$init_mode" in
+    (chkconfig)
+	start_daemon() {
+	    local force= nicelevel=
+	    while [ "$1" != "${1##[-+]}" ] ; do
+		case $1 in
+		    (-f) force="--force" ; shift 1 ;;
+		    (-n) nicelevel="$2"  ; shift 2 ;;
+		esac
+	    done
+	    daemon $force $nicelevel $*
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$1
+	    return $RETVAL
+	}
+	;;
+    (chkconfig-lsb)
+	;;
+    (insserv|insserv-lsb)
+	action() {
+	    echo -en "$1"
+	    shift 1
+	    ${1+"$@"}
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] || rc_failed $RETVAL
+	    rc_status -v
+	    return $RETVAL
+	}
+	;;
+    (lsb)
+	action() {
+	    echo -en "$1"
+	    shift 1
+	    ${1+"$@"}
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] && log_success_msg || log_failure_msg
+	    return $?
+	}
+	;;
+    (standalone|*)
+	start_daemon() {
+	    local force= nicecmd=
+	    while [ "$1" != "${1##[-+]}" ] ; do
+		case $1 in
+		    (-f) force="--force"       ; shift 1 ;;
+		    (-n) nicecmd="nice -n $2"  ; shift 2 ;;
+		esac
+	    done
+	    ( $* >/dev/null 2>&1 </dev/null & )
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$1
+	    return $RETVAL
+	}
+	action() {
+	    echo -en "$1"
+	    shift 1
+	    ${1+"$@"}
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] && echo -e "\t...SUCCESS" || echo -e "\t....FAILED"
+	    return $?
+	}
+	if [ -x /sbin/pidof ] ; then
+	    pidofproc() {
+		/sbin/pidof $@
+	    }
+	elif [ -x /sbin/pidofproc ] ; then
+	    pidofproc() {
+		/sbin/pidofproc $@
+	    }
+	else
+	    pidofproc() {
+		[ -r $pidfile ] && cat $pidfile
+	    }
+	fi
+	if [ -x /sbin/killproc ] ; then
+	    killproc() {
+		/sbin/killproc $@
+	    }
+	elif [ -x /usr/bin/killall ] ; then
+	    killproc() {
+		/usr/bin/killall $@
+	    }
+	else
+	    killproc() {
+		[ -r $pidfile ] && kill "$2" `cat $pidfile`
+	    }
+	fi
+	;;
+esac
 
 name='strerr'
 lockfile="/var/lock/subsys/$name"
 config="/etc/sysconfig/$name"
 processname="$name"
 pidfile="/var/run/$processname.pid"
+execfile="/usr/sbin/$processname"
 
-[ -x /sbin/$processname ] || [ -x /usr/sbin/$processname ] || exit 0
+if [ ! -x $execfile ] ; then if [ "$1" = "stop" ] ; then exit 0 ; else exit 5 ; fi ; fi
+
+# Disable for the moment
+
+if [ "$1" = "stop" ] ; then exit 0 ; else exit 5 ; fi
 
 # Specify defaults
 
@@ -74,7 +177,7 @@ umask 077
 
 build_options() {
     # Build up the options string
-    STRERR_OPTIONS=
+    STRERR_OPTIONS="-p $pidfile"
     [ -n "$STRERROPTIONS" ] && \
 	STRERR_OPTIONS="${STRERR_OPTIONS:+ }${STRERROPTIONS}"
     [ -n "$STRERR_MAILUID" ] && \
@@ -93,7 +196,7 @@ build_options() {
 
 start() {
     build_options
-    daemon $processname -p $pidfile $STRERR_OPTIONS
+    start_daemon $processname $STRERR_OPTIONS
     RETVAL=$?
     [ $RETVAL -eq 0 ] && touch $lockfile
     RETVAL=$?
@@ -131,9 +234,9 @@ case "$1" in
 	[ -f $lockfile ] && restart || RETVAL=$?
 	;;
     (probe)
-	if /sbin/pidof $processname >/dev/null 2>&1 ; then
+	if pidofproc $processname >/dev/null 2>&1 ; then
 	    # running
-	    if [ "`/sbin/pidof $processname`" -eq "`cat $pidfile`" ] ; then
+	    if [ "`pidofproc $processname`" -eq "`cat $pidfile`" ] ; then
 		# running with the right pid
 		if [ ! -f $lockfile ] ; then
 		    # running but subsystem unlocked, need to reload
@@ -166,7 +269,7 @@ case "$1" in
 	RETVAL=$?
 	;;
     (*)
-	echo "Usage: $0 (start|stop|status|restart|condrestart|probe)"
+	echo "Usage: $0 (start|stop|status|reload|restart|condrestart|probe)"
 	;;
 esac
 
@@ -174,7 +277,7 @@ esac
 
 # =============================================================================
 # 
-# @(#) $RCSfile: strerr,v $ $Name:  $($Revision: 0.9.2.6 $) $Date: 2005/02/18 01:36:07 $
+# @(#) $RCSfile: strerr,v $ $Name:  $($Revision: 0.9.2.7 $) $Date: 2005/12/16 09:26:10 $
 #
 # -----------------------------------------------------------------------------
 #
@@ -220,7 +323,7 @@ esac
 #
 # -----------------------------------------------------------------------------
 #
-# Last Modified $Date: 2005/02/18 01:36:07 $ by $Author: brian $
+# Last Modified $Date: 2005/12/16 09:26:10 $ by $Author: brian $
 #
 # =============================================================================
 
diff --git a/strutil/src/util/init/strlogd b/strutil/src/util/init/strlogd
--- a/strutil/src/util/init/strlogd
+++ b/strutil/src/util/init/strlogd
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 #
-# @(#) $RCSfile: strlogd,v $ $Name:  $($Revision: 0.9.2.1 $) $Date: 2005/07/20 13:02:41 $
+# @(#) $RCSfile: strlogd,v $ $Name:  $($Revision: 0.9.2.2 $) $Date: 2005/12/16 09:26:11 $
 # Copyright (c) 2001-2005  OpenSS7 Corporation <http://www.openss7.com>
 # Copyright (c) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>
 # All Rights Reserved.
@@ -33,6 +33,7 @@
 # Required-Stop: streams
 # Default-Start: 
 # Default-Stop: 0 1 2 3 4 5 6
+# X-UnitedLinux-Default-Enabled: no
 # Short-Description: start and stop strlogd
 # License: GPL
 # Description:	This STREAMS init script is part of Linux Fast-STREAMS.  It is
@@ -42,15 +43,117 @@
 ### END INIT INFO
 
 # Source init script functions library
-[ -f /etc/init.d/functions ] && . /etc/init.d/functions
+init_mode="standalone"
+if [ -r /lib/lsb/init-functions ] ; then . /lib/lsb/init-functions ; init_mode="lsb" ;
+if [ -r /etc/init.d/functions   ] ; then init_mode="chkconfig-lsb" ; fi
+if [ -r /etc/rc.status          ] ; then init_mode="insserv-lsb"   ; fi
+else
+if [ -r /etc/init.d/functions   ] ; then . /etc/init.d/functions ; init_mode="chkconfig" ; else
+if [ -r /etc/rc.status          ] ; then . /etc/rc.status        ; init_mode="insserv"   ; fi ; fi
+fi
+
+case "$init_mode" in
+    (chkconfig)
+	start_daemon() {
+	    local force= nicelevel=
+	    while [ "$1" != "${1##[-+]}" ] ; do
+		case $1 in
+		    (-f) force="--force" ; shift 1 ;;
+		    (-n) nicelevel="$2"  ; shift 2 ;;
+		esac
+	    done
+	    daemon $force $nicelevel $*
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$1
+	    return $RETVAL
+	}
+	;;
+    (chkconfig-lsb)
+	;;
+    (insserv|insserv-lsb)
+	action() {
+	    echo -en "$1"
+	    shift 1
+	    ${1+"$@"}
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] || rc_failed $RETVAL
+	    rc_status -v
+	    return $RETVAL
+	}
+	;;
+    (lsb)
+	action() {
+	    echo -en "$1"
+	    shift 1
+	    ${1+"$@"}
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] && log_success_msg || log_failure_msg
+	    return $?
+	}
+	;;
+    (standalone|*)
+	start_daemon() {
+	    local force= nicecmd=
+	    while [ "$1" != "${1##[-+]}" ] ; do
+		case $1 in
+		    (-f) force="--force"       ; shift 1 ;;
+		    (-n) nicecmd="nice -n $2"  ; shift 2 ;;
+		esac
+	    done
+	    ( $* >/dev/null 2>&1 </dev/null & )
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$1
+	    return $RETVAL
+	}
+	action() {
+	    echo -en "$1"
+	    shift 1
+	    ${1+"$@"}
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] && echo -e "\t...SUCCESS" || echo -e "\t....FAILED"
+	    return $?
+	}
+	if [ -x /sbin/pidof ] ; then
+	    pidofproc() {
+		/sbin/pidof $@
+	    }
+	elif [ -x /sbin/pidofproc ] ; then
+	    pidofproc() {
+		/sbin/pidofproc $@
+	    }
+	else
+	    pidofproc() {
+		[ -r $pidfile ] && cat $pidfile
+	    }
+	fi
+	if [ -x /sbin/killproc ] ; then
+	    killproc() {
+		/sbin/killproc $@
+	    }
+	elif [ -x /usr/bin/killall ] ; then
+	    killproc() {
+		/usr/bin/killall $@
+	    }
+	else
+	    killproc() {
+		[ -r $pidfile ] && kill "$2" `cat $pidfile`
+	    }
+	fi
+	;;
+esac
 
 name='strlogd'
 lockfile="/var/lock/subsys/$name"
 config="/etc/sysconfig/$name"
 processname="$name"
 pidfile="/var/run/$processname.pid"
+execfile="/usr/sbin/$processname"
 
-[ -x /sbin/$processname ] || [ -x /usr/sbin/$processname ] || exit 0
+if [ ! -x $execfile ] ; then if [ "$1" = "stop" ] ; then exit 0 ; else exit 5 ; fi ; fi
+
+# Disable for the moment
+
+if [ "$1" = "stop" ] ; then exit 0 ; else exit 5 ; fi
 
 # Specify defaults
 
@@ -93,7 +196,7 @@ build_options() {
 
 start() {
     build_options
-    daemon $processname -p $pidfile $STRLOGD_OPTIONS
+    start_daemon $processname -p $pidfile $STRLOGD_OPTIONS
     RETVAL=$?
     [ $RETVAL -eq 0 ] && touch $lockfile
     RETVAL=$?
@@ -131,9 +234,9 @@ case "$1" in
 	[ -f $lockfile ] && restart || RETVAL=$?
 	;;
     (probe)
-	if /sbin/pidof $processname >/dev/null 2>&1 ; then
+	if pidofproc $processname >/dev/null 2>&1 ; then
 	    # running
-	    if [ "`/sbin/pidof $processname`" -eq "`cat $pidfile`" ] ; then
+	    if [ "`pidofproc $processname`" -eq "`cat $pidfile`" ] ; then
 		# running with the right pid
 		if [ ! -f $lockfile ] ; then
 		    # running but subsystem unlocked, need to reload
@@ -174,7 +277,7 @@ esac
 
 # =============================================================================
 # 
-# @(#) $RCSfile: strlogd,v $ $Name:  $($Revision: 0.9.2.1 $) $Date: 2005/07/20 13:02:41 $
+# @(#) $RCSfile: strlogd,v $ $Name:  $($Revision: 0.9.2.2 $) $Date: 2005/12/16 09:26:11 $
 #
 # -----------------------------------------------------------------------------
 #
@@ -220,7 +323,7 @@ esac
 #
 # -----------------------------------------------------------------------------
 #
-# Last Modified $Date: 2005/07/20 13:02:41 $ by $Author: brian $
+# Last Modified $Date: 2005/12/16 09:26:11 $ by $Author: brian $
 #
 # =============================================================================
 
