Import from CVS Wed Jul 13 01:40:39 2005 -0600
- added __LIS_INTERNAL__ to hide internal symbol in header files
file strconf.h was initially added on branch LIS-2-18-0-autoconf.
- changes for check pass

diff --git a/sctp/scripts/check_decls b/sctp/scripts/check_decls
--- a/sctp/scripts/check_decls
+++ b/sctp/scripts/check_decls
@@ -1,7 +1,7 @@
 #!/bin/bash
 # =============================================================================
 # 
-# @(#) $RCSfile: check_decls,v $ $Name:  $($Revision: 0.9.2.4 $) $Date: 2005/07/12 04:57:52 $
+# @(#) $RCSfile: check_decls,v $ $Name:  $($Revision: 0.9.2.5 $) $Date: 2005/07/13 01:37:14 $
 #
 # -----------------------------------------------------------------------------
 #
@@ -47,7 +47,7 @@
 #
 # -----------------------------------------------------------------------------
 #
-# Last Modified $Date: 2005/07/12 04:57:52 $ by $Author: brian $
+# Last Modified $Date: 2005/07/13 01:37:14 $ by $Author: brian $
 #
 # =============================================================================
 
@@ -92,6 +92,18 @@ function echo_w()
 	echo "$me:$2: W: $1" >&5
 	((warnings++))
 }
+function echo_fle()
+{
+	echo "$1:$2: error: $3" >&2
+	echo "$me:$4: E: $1:$2: error: $3" >&5
+	((errors++))
+}
+function echo_flw()
+{
+	echo "$1:$2: warning: $3" >&2
+	echo "$me:$4: E: $1:$2: warning: $3" >&5
+	((warnings++))
+}
 
 export -p | while read line
 do
@@ -132,13 +144,13 @@ then
 			esac
 			echo_t "testing ${tokens[1]} ${tokens[0]} for exported symbol"
 			case "${tokens[0]}" in
-				(_*)	on_error='echo_w' ;;
-				(*)	on_error='echo_e' ;;
+				(_*)	on_error='echo_flw' ;;
+				(*)	on_error='echo_fle' ;;
 			esac
 			case " $symbols " in
 				(*" ${tokens[0]} "*)
 					echo_s "${tokens[1]} ${tokens[0]} has exported symbol" $LINENO ;;
-				(*)	eval "$on_error \"cannot find symbol for \${tokens[1]} \${tokens[0]} line \${tokens[2]} file \${tokens[3]}\" \$LINENO" ;;
+				(*)	eval "$on_error \${tokens[3]} \${tokens[2]} \"cannot find symbol for \${tokens[1]} \${tokens[0]}\" \$LINENO" ;;
 			esac
 		done < ${top_builddir}/check_ctags.log
 	fi
diff --git a/strxnet/scripts/check_headers b/strxnet/scripts/check_headers
--- a/strxnet/scripts/check_headers
+++ b/strxnet/scripts/check_headers
@@ -1,7 +1,7 @@
 #!/bin/bash
 # =============================================================================
 # 
-# @(#) $RCSfile: check_headers,v $ $Name:  $($Revision: 0.9.2.19 $) $Date: 2005/07/12 04:57:52 $
+# @(#) $RCSfile: check_headers,v $ $Name:  $($Revision: 0.9.2.21 $) $Date: 2005/07/13 01:40:38 $
 #
 # -----------------------------------------------------------------------------
 #
@@ -47,7 +47,7 @@
 #
 # -----------------------------------------------------------------------------
 #
-# Last Modified $Date: 2005/07/12 04:57:52 $ by $Author: brian $
+# Last Modified $Date: 2005/07/13 01:40:38 $ by $Author: brian $
 #
 # =============================================================================
 
@@ -91,6 +91,22 @@ function echo_w()
 #	fi
 	echo "$me:$2: W: $1" >&5
 	((warnings++))
+}
+function echo_fls()
+{
+	echo_s $3 $4
+}
+function echo_flw()
+{
+	echo "$1:$2: warning: $3" >&2
+	echo "$me:$4: W: $3" >&5
+	((warnings++))
+}
+function echo_fle()
+{
+	echo "$1:$2: error: $3" >&2
+	echo "$me:$4: E: $3" >&5
+	((errors++))
 }
 
 export -p | while read line
@@ -136,26 +152,6 @@ done
 #
 rm -f ${top_builddir}/check_ctags.log
 
-ctagsids="-I _RP"
-ctagsids="$ctagsids -I __attribute__+"
-ctagsids="$ctagsids -I __BEGIN_DECLS"
-ctagsids="$ctagsids -I __END_DECLS"
-ctagsids="$ctagsids -I __THROW"
-ctagsids="$ctagsids -I __depr"
-ctagsids="$ctagsids -I __const=const"
-ctagsids="$ctagsids -I HEAD_DECLARATION"
-ctagsids="$ctagsids -I STR_DECLARATION"
-ctagsids="$ctagsids -I __AIX_EXTERN_INLINE=inline"
-ctagsids="$ctagsids -I __EXTERN_INLINE=inline"
-ctagsids="$ctagsids -I __HPUX_EXTERN_INLINE=inline"
-ctagsids="$ctagsids -I __IRIX_EXTERN_INLINE=inline"
-ctagsids="$ctagsids -I __LFS_EXTERN_INLINE=inline"
-ctagsids="$ctagsids -I __LIS_EXTERN_INLINE=inline"
-ctagsids="$ctagsids -I __MAC_EXTERN_INLINE=inline"
-ctagsids="$ctagsids -I __MPS_EXTERN_INLINE=inline"
-ctagsids="$ctagsids -I __OSF_EXTERN_INLINE=inline"
-ctagsids="$ctagsids -I __SUN_EXTERN_INLINE=inline"
-
 echo "$headers" | xargs ctags -x --c-kinds=dfgpstuvx $ctagsids \
 	| sed -e 's|\\$|\\ |' > ${top_builddir}/check_ctags.log
 
@@ -200,22 +196,22 @@ then
 		found=no
 		sections=
 		case ${tokens[0]} in
-		(_*)	on_error='echo_w' ; sections="3 9 7" ;;
+		(_*)	on_error='echo_flw' ; sections="3 9 7" ;;
 		(*)	case ${tokens[1]} in
-			(function)	on_error='echo_e' ; sections="2 3 9"
+			(function)	on_error='echo_fle' ; sections="2 3 9"
 					echo "${tokens[0]}" >> ${top_builddir}/check_symbols.log ;;
-			(prototype)	on_error='echo_e' ; sections="2 3 9" ;;
-			(variable)	on_error='echo_s' ; sections="2 3 9"
+			(prototype)	on_error='echo_fle' ; sections="2 3 9" ;;
+			(variable)	on_error='echo_fls' ; sections="2 3 9"
 					echo "${tokens[0]}" >> ${top_builddir}/check_symbols.log ;;
-			(externvar)	on_error='echo_s' ; sections="2 3 9" ;;
-			(macro)		on_error='echo_s' ; sections="3 9 7" ;;
-			(enumerate)	on_error='echo_s' ; sections="3 9 7" ;;
-			(enum)		on_error='echo_w' ; sections="3 9" ;;
-			(struct)	on_error='echo_w' ; sections="3 9 7" ;;
-			(union)		on_error='echo_w' ; sections="3 9 7" ;;
-			(typedef)	on_error='echo_w' ; sections="3 9 7" ;;
+			(externvar)	on_error='echo_fls' ; sections="2 3 9" ;;
+			(macro)		on_error='echo_fls' ; sections="3 9 7" ;;
+			(enumerate)	on_error='echo_fls' ; sections="3 9 7" ;;
+			(enum)		on_error='echo_flw' ; sections="3 9" ;;
+			(struct)	on_error='echo_flw' ; sections="3 9 7" ;;
+			(union)		on_error='echo_flw' ; sections="3 9 7" ;;
+			(typedef)	on_error='echo_flw' ; sections="3 9 7" ;;
 			(member)	continue ;;
-			(*)		on_error='echo_w' ; sections="3 9 7" ;;
+			(*)		on_error='echo_flw' ; sections="3 9 7" ;;
 			esac ;;
 		esac
 		string="${tokens[1]} ${tokens[0]} in sections $sections"
@@ -240,7 +236,7 @@ then
 		if test :$found = :yes ; then
 			echo_s "found $string" $LINENO
 		else
-			eval "$on_error \"cannot find \$string\" \$LINENO"
+			eval "$on_error \${tokens[3]} \${tokens[2]} \"cannot find \$string\" \$LINENO"
 		fi
 	done < ${top_builddir}/check_ctags.log
 fi
