Import from CVS Sat Mar 26 12:55:38 2005 -0600
- working up debian scripts

diff --git a/sctp/debian/mscript_postrm.in b/sctp/debian/mscript_postrm.in
--- a/sctp/debian/mscript_postrm.in
+++ b/sctp/debian/mscript_postrm.in
@@ -2,7 +2,7 @@
 ## @configure_input@
 ## =============================================================================
 ## 
-# @(#) $RCSfile: mscript_postrm.in,v $ $Name:  $($Revision: 0.9.2.1 $) $Date: 2005/03/26 03:11:23 $
+# @(#) $RCSfile: mscript_postrm.in,v $ $Name:  $($Revision: 0.9.2.2 $) $Date: 2005/03/26 12:55:35 $
 ##
 ## -----------------------------------------------------------------------------
 ##
@@ -48,13 +48,55 @@
 ##
 ## -----------------------------------------------------------------------------
 ##
-## Last Modified $Date: 2005/03/26 03:11:23 $ by $Author: brian $
+## Last Modified $Date: 2005/03/26 12:55:35 $ by $Author: brian $
 ##
 ## =============================================================================
 
 [ ":${subpkg+set}" = ":set" ] || subpkg=
 
+echo "@PACKAGE@-${subpkg}(@VERSION@-@PACKAGE_DEBRELEASE@): $*" >&2
 
+case "$1" in
+
+    (remove) :
+	# remove-postrm remove
+	eval "remove_${subpkg}_postrm"
+	;;
+
+    (purge) :
+	# remove-postrm purge
+	eval "purge_${subpkg}_postrm"
+	;;
+
+    (upgrade) :
+	# old-postrm upgrade new-version
+	eval "upgrade_${subpkg}_postrm"
+	;;
+
+    (failed-upgrade) :
+	# old-postrm upgrade new-version ... failed
+	# new-postrm failed-upgrade old-version
+	eval "failed_upgrade_${subpkg}_postrm"
+	;;
+
+    (abort-install) :
+	# new-preinst install [old-version] ... failed
+	# new-postrm abort-install [old-version]
+	echo "@PACKAGE@-${subpkg}(@VERSION@-@PACKAGE_DEBRELEASE@): $1: modules running." > &2
+	;;
+
+    (abort-upgrade) :
+	# new-preinst upgrade old-version ... failed
+	# new-postrm abort-upgrade old-version
+	echo "@PACKAGE@-${subpkg}(@VERSION@-@PACKAGE_DEBRELEASE@): $1: modules running." > &2
+	;;
+
+    (disappear) :
+	# disappear-postrm disappear overwriter overwriter-version
+	eval "disappear_${subpkg}_postrm"
+	;;
+
+esac
 
 ## =============================================================================
 ##
@@ -67,10 +109,13 @@
 ## =============================================================================
 ##
 ## $Log: mscript_postrm.in,v $
-## Revision 0.9.2.1  2005/03/26 03:11:23  brian
-## - Reworking maintainance scripts
+## Revision 0.9.2.2  2005/03/26 12:55:35  brian
+## - working up debian scripts
 ##
-## Revision 1.1  2005/03/26 03:11:23  brian
+## Revision 1.2  2005/03/26 12:55:35  brian
+## - working up debian scripts
+##
+## Revision 1.1.2.1  2005/03/26 03:11:22  brian
 ## - Reworking maintainance scripts
 ##
 ## Revision 1.1.2.1  2005/03/24 02:09:14  brian
diff --git a/stacks/debian/mscript_postinst.in b/stacks/debian/mscript_postinst.in
--- a/stacks/debian/mscript_postinst.in
+++ b/stacks/debian/mscript_postinst.in
@@ -2,7 +2,7 @@
 ## @configure_input@
 ## =============================================================================
 ## 
-# @(#) $RCSfile: mscript_postinst.in,v $ $Name:  $($Revision: 0.9.2.1 $) $Date: 2005/03/26 03:11:23 $
+# @(#) $RCSfile: mscript_postinst.in,v $ $Name:  $($Revision: 0.9.2.2 $) $Date: 2005/03/26 12:55:35 $
 ##
 ## -----------------------------------------------------------------------------
 ##
@@ -48,13 +48,41 @@
 ##
 ## -----------------------------------------------------------------------------
 ##
-## Last Modified $Date: 2005/03/26 03:11:23 $ by $Author: brian $
+## Last Modified $Date: 2005/03/26 12:55:35 $ by $Author: brian $
 ##
 ## =============================================================================
 
 [ ":${subpkg+set}" = ":set" ] || subpkg=
 
+echo "@PACKAGE@-${subpkg}(@VERSION@-@PACKAGE_DEBRELEASE@): $*" >&2
 
+case "$1" in
+
+    (configure) : # postinstallation configuration
+	# configure-postinst configure [most-recently-configured-version]
+	eval "configure_${subpkg}_postinst"
+	;;
+
+    (abort-upgrade) :
+	# old-prerm upgrade new-version ... failed
+	# new-prerm failed-upgrade new-version ... failed
+	# old-posinst abort-upgrade new-version
+	echo "@PACKAGE@-${subpkg}(@VERSION@-@PACKAGE_DEBRELEASE@): $1: modules running." > &2
+	;;
+
+    (abort-remove) :
+	# conflict-prerm remove in-favour package new-version ... failed
+	# conflict-postinst abort-remove in-favour package new-version
+	echo "@PACKAGE@-${subpkg}(@VERSION@-@PACKAGE_DEBRELEASE@): $1: modules running." > &2
+	;;
+
+    (abort-deconfigure) :
+	# deconfigure-prerm deconfigure in-favour package-being-installed version removing conflicting-package version .. failed
+	# deconfigure-postinst abort-deconfigurein-favour package-being-installed-but-failed version removing conflicting-package version
+	echo "@PACKAGE@-${subpkg}(@VERSION@-@PACKAGE_DEBRELEASE@): $1: modules running." > &2
+	;;
+
+esac
 
 ## =============================================================================
 ##
@@ -67,7 +95,10 @@
 ## =============================================================================
 ##
 ## $Log: mscript_postinst.in,v $
-## Revision 0.9.2.1  2005/03/26 03:11:23  brian
+## Revision 0.9.2.2  2005/03/26 12:55:35  brian
+## - working up debian scripts
+##
+## Revision 0.9.2.1  2005/03/26 03:11:22  brian
 ## - Reworking maintainance scripts
 ##
 ## Revision 0.9.2.1  2005/03/24 02:09:14  brian
diff --git a/strxns/debian/mscript_prerm.in b/strxns/debian/mscript_prerm.in
--- a/strxns/debian/mscript_prerm.in
+++ b/strxns/debian/mscript_prerm.in
@@ -2,7 +2,7 @@
 ## @configure_input@
 ## =============================================================================
 ## 
-# @(#) $RCSfile: mscript_prerm.in,v $ $Name:  $($Revision: 0.9.2.1 $) $Date: 2005/03/26 03:11:25 $
+# @(#) $RCSfile: mscript_prerm.in,v $ $Name:  $($Revision: 0.9.2.2 $) $Date: 2005/03/26 12:55:38 $
 ##
 ## -----------------------------------------------------------------------------
 ##
@@ -48,13 +48,42 @@
 ##
 ## -----------------------------------------------------------------------------
 ##
-## Last Modified $Date: 2005/03/26 03:11:25 $ by $Author: brian $
+## Last Modified $Date: 2005/03/26 12:55:38 $ by $Author: brian $
 ##
 ## =============================================================================
 
 [ ":${subpkg+set}" = ":set" ] || subpkg=
 
+echo "@PACKAGE@-${subpkg}(@VERSION@-@PACKAGE_DEBRELEASE@): $*" >&2
 
+case "$1" in
+
+    (remove) :
+	if [ ":${3+set}" = ":set" ]
+	then : # conflict-prerm remove in-favour package new-version
+	    eval "conflict_${subpkg}_prerm"
+	else : # remove-prerm remove
+	    eval "remove_${subpkg}_prerm"
+	fi
+	;;
+
+    (upgrade) :
+	# old-prerm upgrade new-version
+	eval "upgrade_${subpkg}_prerm"
+	;;
+
+    (failed-upgrade) :
+	# old-prerm upgrade new-version ... failed
+	# new-prerm failed-upgrade old-version
+	eval "failed_upgrade_${subpkg}_prerm"
+	;;
+
+    (deconfigure) :
+	# deconfigure-prerm deconfigure in-favour package-being-installed version removing conflicting-package version
+	eval "deconfigure_${subpkg}_prerm"
+	;;
+
+esac
 
 ## =============================================================================
 ##
@@ -67,10 +96,13 @@
 ## =============================================================================
 ##
 ## $Log: mscript_prerm.in,v $
-## Revision 0.9.2.1  2005/03/26 03:11:25  brian
+## Revision 0.9.2.2  2005/03/26 12:55:38  brian
+## - working up debian scripts
+##
+## Revision 1.1.2.1  2005/03/26 03:11:22  brian
 ## - Reworking maintainance scripts
 ##
-## Revision 0.9.2.1  2005/03/24 02:09:14  brian
+## Revision 1.1.2.1  2005/03/24 02:09:14  brian
 ## - improved debian build
 ##
 ##
