- get boot updates working

diff --git a/src/util/init/openss7 b/src/util/init/openss7
--- a/src/util/init/openss7
+++ b/src/util/init/openss7
@@ -284,14 +284,15 @@ remove_depends () {
 start_update () {
     RETVAL=0
     if [ ":$previous" = 'N' -a ":$runlevel" != ':' ] ; then
-	if [ ":$OPENSS7_KUPDATE" = ':yes' -o -e /.openss7_update ] ; then
+	marker="/.openss7_update-`uname -r`"
+	if [ ":$OPENSS7_KUPDATE" = ':yes' -a -e $marker ] ; then
 	    for command in /sbin/openss7-modules /usr/sbin/openss7-modules ; do
 		if [ -x $command ] ; then
 		    action "Updating kernel modules" \
 			$command -- -q --boot-kernel
 		    RETVAL=$?
 		    if [ $RETVAL -eq 0 ] ; then
-			rm -f -- /.openss7_update
+			rm -f -- $marker || :
 		    fi
 		    break
 		fi
@@ -307,7 +308,7 @@ start_update () {
 #   run when updates have been marked.  The existing kernel modules may have to
 #   be relinked to match a rebooting kernel with the same ABI as an overwritten
 #   kernel.  This is the case for Debian, Ubuntu, SuSE and OpenSuSE, but not, it
-#   seems, RedHat, CentOS nor Fedora.  Note that this sould really only be run
+#   seems, RedHat, CentOS nor Fedora.  Note that this should really only be run
 #   once on kernel shutdown or restart, and not any time that the Special
 #   Filesystem is stopped, so the 'runlevel' and 'previous' environment
 #   variables are consulted to ensure that we are shutting down or rebooting
@@ -315,26 +316,23 @@ start_update () {
 #
 stop_update () {
     RETVAL=0
-    if [ ":$previous" != 'N' -a \( ":$runlevel" = ':0' -o ":$runlevel" = ':6' ]
-    then
-	if [ ":$OPENSS7_KUPDATE" = ':yes' ]
-	then :
-	    if [ -e /.openss7_update-@kversion@ ]; then
-		for command in /sbin/openss7-modules /usr/sbin/openss7-modules
-		do
-		    [ -x $command ] || continue
-		    action "Updating kernel modules" \
-			$command -- -q --boot-kernel
-		    RETVAL=$?
-		    if [ $RETVAL -eq 0 ]; then
-			rm -f -- /.openss7_update-@kversion@
-		    fi
-		    break
-		done
-	    fi
+    if [ ":$previous" != 'N' -a \( ":$runlevel" = ':0' -o ":$runlevel" = ':6' ]; then
+	marker="/.openss7_update-`uname -r`"
+	if [ ":$OPENSS7_KUPDATE" = ':yes' -a -e $marker ]; then
+	    for command in /sbin/openss7-modules /usr/sbin/openss7-modules
+	    do
+		[ -x $command ] || continue
+		action "Updating kernel modules" \
+		    $command -- -q --boot-kernel
+		RETVAL=$?
+		if [ $RETVAL -eq 0 ]; then
+		    rm -f -- $marker || :
+		fi
+		break
+	    done
 	fi
     fi
-    :
+    return $RETVAL
 }
 
 #
@@ -577,11 +575,11 @@ stop_mount () {
 }
 
 #
-# start_preload() is used to insert all preload specified modules.  Typically
-# for openss7 this is some short list of modules.  These modules must be loaded
-# before sysctl parameters can be configured.
-# On some systems it is possible to identify this module as a system preloaded
-# module, but on others the module is only loaded when the initscript is run.
+# start_preload() - Used to insert all preload specified modules.  Typically for
+#   openss7 this is some short list of modules.  These modules must be loaded
+#   before sysctl parameters can be configured.  On some systems it is possible
+#   to identify this module as a system preloaded module, but on others the
+#   module is only loaded when the initscript is run.
 #
 start_preload () {
     # insert in forward order
@@ -634,10 +632,10 @@ status_preload () {
 }
 
 #
-# stop_preload() is used to remove specified preloaded modules.  Typically for
-# openss7 this would include a list of preloaded modules.  This function also
-# attempts to remove all dependent modules.  Note that for openss7 all STREAMS
-# devices must be closed and unlinked or this could fail.
+# stop_preload() - Used to remove specified preloaded modules.  Typically for
+#   openss7 this would include a list of preloaded modules.  This function also
+#   attempts to remove all dependent modules.  Note that for openss7 all STREAMS
+#   devices must be closed and unlinked or this could fail.
 #
 stop_preload () {
     # remove in reverse order
@@ -888,6 +886,7 @@ stop () {
     stop_preload	# remove preloads
     stop_specfs		# remove the specfs kernel module
     stop_mountpoint	# remove the mountpoint (usually /dev/streams)
+    stop_update		# check kernel module weak updates
     [ $RETVAL -eq 0 ] && rm -f -- $lockfile
     return $RETVAL
 }
