- finalizing init scripts

diff --git a/src/util/init/strace b/src/util/init/strace
--- a/src/util/init/strace
+++ b/src/util/init/strace
@@ -1,8 +1,8 @@
 #!/bin/bash
 #
 # @(#) $RCSfile: strace,v $ $Name:  $($Revision: 1.1.2.4 $) $Date: 2011-02-10 17:29:46 $
-# Copyright (c) 2008-2009  Monavacon Limited <http://www.monavacon.com/>
-# Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com>
+# Copyright (c) 2008-2011  Monavacon Limited <http://www.monavacon.com/>
+# Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
 # Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>
 # All Rights Reserved.
 #
@@ -12,14 +12,14 @@
 # Redhat chkconfig init script conventions
 #
 # strace:	start and stop strace facility
-# chkconfig:	- 04 95
+# chkconfig:	2345 04 95
 # lockfile:	/var/lock/subsys/strace
-# config:	/etc/default/strace
+# config:	/etc/sysconfig/strace
 # processname:	strace
 # pidfile:	/var/run/strace.pid
 # probe:	true
 # hide:		false
-# license:	GPL
+# license:	AGPL
 # description:	This STREAMS init script is part of Linux Fast-STREAMS.  It is \
 #		responsible for starting and stopping the STREAMS trace \
 #		logger.  The STREAMS trace logger should only be run under \
@@ -32,29 +32,33 @@
 # Provides: strace
 # Required-Start: streams
 # Required-Stop: streams
-# Should-Start: strerr
-# Should-Stop: strerr
-# Default-Start: 4
-# Default-Stop: 0 1 2 3 4 5 6
+# Should-Start: $syslog strerr
+# Should-Stop: $syslog strerr
+# Default-Start: 2 3 4 5
+# Default-Stop:
 # X-UnitedLinux-Default-Enabled: no
 # Short-Description: start and stop strace
-# License: GPL
+# License: AGPL
 # Description:	This STREAMS init script is part of Linux Fast-STREAMS.  It is
 #	responsible for starting and stopping the STREAMS trace logger.  The
 #	STREAMS trace logger should only be run under exceptional circumstances
 #	and this init script is not activated in any run level by default.
 ### END INIT INFO
 
-# Source init script functions library
+PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
+
+# Source init script functions library.
 init_mode="standalone"
   if [ -r /etc/init.d/functions   ] ; then . /etc/init.d/functions   ; init_mode="chkconfig" ;
 elif [ -r /etc/rc.status          ] ; then . /etc/rc.status          ; init_mode="insserv"   ;
 elif [ -r /lib/lsb/init-functions ] ; then . /lib/lsb/init-functions ; init_mode="lsb"       ;
+elif [ -r /sbin/start-stop-daemon ] ; then                             init_mode="debian"    ;
 fi
 
 case "$init_mode" in
     (chkconfig)
-	daemon_start() {
+	# RedHat's LSB support is not so good, use native functions first.
+	daemon_start () {
 	    local force= nicelevel= base=
 	    while [ "$1" != "${1##[-+]}" ] ; do
 		case $1 in
@@ -64,32 +68,33 @@ case "$init_mode" in
 	    done
 	    base=`echo $1 | sed -e 's,.*/,,'`
 	    echo -en "Starting daemon $base: "
-	    daemon $force $nicelevel $*
+	    daemon $force $nicelevel "$@"
 	    RETVAL=$?
 	    echo ""
 	    return $RETVAL
 	}
-	daemon_stop() {
+	daemon_stop () {
 	    local base=
 	    base=`echo $1 | sed -e 's,.*/,,'`; shift 1
 	    echo -en "Stopping daemon $base: "
-	    killproc $base $*
+	    killproc $base "$@"
+	    RETVAL=$?
+	    echo ""
+	    return $RETVAL
+	}
+	daemon_reload () {
+	    local base=
+	    base=`echo $1 | sed -e 's,.*/,,'`; shift 1
+	    echo -en "Reloading daemon $base: "
+	    killproc $base -HUP
 	    RETVAL=$?
 	    echo ""
 	    return $RETVAL
 	}
 	;;
     (insserv)
-	action() {
-	    echo -en "$1"
-	    shift 1
-	    ${1+"$@"} >/dev/null
-	    RETVAL=$?
-	    [ $RETVAL -eq 0 ] || rc_failed $RETVAL
-	    rc_status -v
-	    return $RETVAL
-	}
-	daemon_start() {
+	# SuSE's LSB support is not so good, use native functions first.
+	daemon_start () {
 	    local force= nicelevel= base=
 	    while [ "$1" != "${1##[-+]}" ] ; do
 		case $1 in
@@ -99,17 +104,36 @@ case "$init_mode" in
 	    done
 	    base=`echo $1 | sed -e 's,.*/,,'`
 	    echo -en "Starting daemon $base: "
-	    startproc $force $nicelevel $*
+	    startproc $force $nicelevel "$@"
 	    RETVAL=$?
 	    [ $RETVAL -eq 0 ] || rc_failed $RETVAL
 	    rc_status -v
 	    return $RETVAL
 	}
-	daemon_stop() {
+	daemon_stop () {
 	    local base=
 	    base=`echo $1 | sed -e 's,.*/,,'`; shift 1
 	    echo -en "Stopping daemon $base: "
-	    killproc $base $*
+	    killproc $base "$@"
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] || rc_failed $RETVAL
+	    rc_status -v
+	    return $RETVAL
+	}
+	daemon_reload () {
+	    local base=
+	    base=`echo $1 | sed -e 's,.*/,,'`; shift 1
+	    echo -en "Reloading daemon $base: "
+	    killproc $base -HUP
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] || rc_failed $RETVAL
+	    rc_status -v
+	    return $RETVAL
+	}
+	action () {
+	    echo -en "$1"
+	    shift 1
+	    ${1+"$@"} >/dev/null
 	    RETVAL=$?
 	    [ $RETVAL -eq 0 ] || rc_failed $RETVAL
 	    rc_status -v
@@ -117,7 +141,7 @@ case "$init_mode" in
 	}
 	;;
     (lsb)
-	daemon_start() {
+	daemon_start () {
 	    local force= nicelevel= base=
 	    while [ "$1" != "${1##[-+]}" ] ; do
 		case $1 in
@@ -127,21 +151,30 @@ case "$init_mode" in
 	    done
 	    base=`echo $1 | sed -e 's,.*/,,'`
 	    echo -en "Starting daemon $base: "
-	    start_daemon $force $nicelevel $*
+	    start_daemon $force $nicelevel "$@"
 	    RETVAL=$?
 	    [ $RETVAL -eq 0 ] && log_success_msg || log_failure_msg
 	    return $RETVAL
 	}
-	daemon_stop() {
+	daemon_stop () {
 	    local base=
 	    base=`echo $1 | sed -e 's,.*/,,'`; shift 1
 	    echo -en "Stopping daemon $base: "
-	    killproc $base $*
+	    killproc $base "$@"
 	    RETVAL=$?
 	    [ $RETVAL -eq 0 ] && log_success_msg || log_failure_msg
 	    return $RETVAL
 	}
-	action() {
+	daemon_reload () {
+	    local base=
+	    base=`echo $1 | sed -e 's,.*/,,'`; shift 1
+	    echo -en "Reloading daemon $base: "
+	    killproc $base -HUP
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] && log_success_msg || log_failure_msg
+	    return $RETVAL
+	}
+	action () {
 	    echo -en "$1"
 	    shift 1
 	    ${1+"$@"} >/dev/null
@@ -150,40 +183,93 @@ case "$init_mode" in
 	    return $RETVAL
 	}
 	;;
+    (debian)
+	# a resonably modern debian system will have LSB support
+	daemon_start () {
+	    local force= nicelevel= base=
+	    while [ "$1" != "${1##[+-]}" ] ; do
+		case $1 in
+		    (-f) force="" ; shift 1 ;;
+		    (-n) nicelevel="-N $2"  ; shift 2 ;;
+		esac
+	    done
+	    base=`echo $1 | sed -e 's,.*/,,'`
+	    echo -en "Starting daemon $base: "
+	    start-stop-daemon --start $force $nicelevel --quiet \
+		--pidfile $pidfile --exec $execfile -- "$@"
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] || echo "(failed)"; echo "."
+	    return $RETVAL
+	}
+	daemon_stop () {
+	    local base=
+	    base=`echo $1 | sed -e 's,.*/,,'`; shift 1
+	    echo -en "Stopping daemon $base: "
+	    start-stop-daemon --stop --quiet --retry=1 --oknodo \
+		--pidfile $pidfile --exec $execfile
+	    RETVAL=$?
+	      if [ $RETVAL -eq   0 ] ; then echo "."
+	    elif [ $RETVAL -eq 255 ] ; then echo "(warning)."
+	    else                            echo "failed!"
+	    fi
+	    return $RETVAL
+	}
+	daemon_reload () {
+	    local base=
+	    base=`echo $1 | sed -e 's,.*/,,'`; shift 1
+	    echo -en "Reloading daemon $base: "
+	    killproc $base -HUP
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] || echo "(failed)"; echo "."
+	    return $RETVAL
+	}
+	action () {
+	    echo -en "$1"
+	    shift 1
+	    eval "\${1+\"\$@\"} $redir"
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] || echo "(failed)"; echo "."
+	    return $RETVAL
+	}
+	;;
     (standalone|*)
-	log_success_msg() {
-	    echo -e "\t...SUCCESS\n"
-	}
-	log_failure_msg() {
-	    echo -e "\t...FAILED\n"
-	}
 	if [ -x /sbin/pidof ] ; then
-	    pidofproc() {
+	    pidofproc () {
 		/sbin/pidof $@
 	    }
 	elif [ -x /sbin/pidofproc ] ; then
-	    pidofproc() {
+	    pidofproc () {
 		/sbin/pidofproc $@
 	    }
 	else
-	    pidofproc() {
+	    pidofproc () {
 		[ -r $pidfile ] && cat $pidfile
 	    }
 	fi
-	if [ -x /sbin/killproc ] ; then
-	    killproc() {
+	if [ -x /sbin/start-stop-daemon ] ; then
+	    killproc () {
+		local base execfile
+		base=$1
+		execfile=$2
+		shift 2
+		start-stop-daemon --stop --quiet --retry=1 --oknodo \
+		    --pidfile $pidfile \
+		    --exec $execfile
+	    }
+	elif [ -x /sbin/killproc ] ; then
+	    killproc () {
 		/sbin/killproc $@
 	    }
 	elif [ -x /usr/bin/killall ] ; then
-	    killproc() {
+	    killproc () {
 		/usr/bin/killall $@
 	    }
 	else
-	    killproc() {
+	    killproc () {
 		[ -r $pidfile ] && kill "$2" `cat $pidfile`
 	    }
 	fi
-	daemon_start() {
+	daemon_start () {
 	    local force= nicecmd= base=
 	    while [ "$1" != "${1##[-+]}" ] ; do
 		case $1 in
@@ -193,25 +279,34 @@ case "$init_mode" in
 	    done
 	    base=`echo $1 | sed -e 's,.*/,,'`
 	    echo -en "Starting daemon $base: "
-	    ( $* >/dev/null 2>&1 </dev/null & )
+	    eval "( $nicecmd \"\$@\" >/dev/null 2>&1 </dev/null & )"
 	    RETVAL=$?
 	    [ $RETVAL -eq 0 ] && echo -en "\t...SUCCESS" || echo -en "\t....FAILED"
 	    return $RETVAL
 	}
-	daemon_stop() {
+	daemon_stop () {
 	    local base=
 	    base=`echo $1 | sed -e 's,.*/,,'`; shift 1
 	    echo -en "Stopping daemon $base: "
 	    if pidofproc $base >/dev/null 2>&1 ; then
 		RETVAL=0
 	    else
-		killproc $base $*
+		killproc $base "$@"
 		RETVAL=$?
 	    fi
 	    [ $RETVAL -eq 0 ] && log_success_msg || log_failure_msg
 	    return $RETVAL
 	}
-	action() {
+	daemon_reload () {
+	    local base=
+	    base=`echo $1 | sed -e 's,.*/,,'`; shift 1
+	    echo -en "Reloading daemon $base: "
+	    killproc $base -HUP
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] && echo -en "\t...SUCCESS" || echo -en "\t....FAILED"
+	    return $RETVAL
+	}
+	action () {
 	    echo -en "$1"
 	    shift 1
 	    ${1+"$@"} >/dev/null
@@ -223,11 +318,14 @@ case "$init_mode" in
 esac
 
 name='strace'
+script='strace'
+ucname="STRACE"
 lockfile="/var/lock/subsys/$name"
-config="/etc/sysconfig/$name"
+config="/etc/sysconfig/$name /etc/default/$name"
 processname="$name"
 pidfile="/var/run/$processname.pid"
 execfile="/usr/sbin/$processname"
+desc="the STREAMS trace logger"
 
 if [ ! -x $execfile ] ; then if [ "$1" = "stop" ] ; then exit 0 ; else exit 5 ; fi ; fi
 
@@ -242,7 +340,7 @@ STRACE_LOGDEVICE="/dev/streams/clone/log"
 STRACE_MODULES=
 STRACE_OPTIONS=
 
-# Source config file
+# Source redhat and/or debian config file
 for file in $config ; do
     [ -f $file ] && . $file
 done
@@ -251,26 +349,35 @@ RETVAL=0
 
 umask 077
 
-build_options() {
+case ":$VERBOSE" in
+    :no|:NO|:false|:FALSE|:0|:)
+	redir='>/dev/null 2>&1'
+	;;
+    *)
+	redir=
+	;;
+esac
+
+build_options () {
     # Build up the options string
     STRACE_OPTIONS="-n -p $pidfile"
     [ -n "$STRACEOPTIONS" ] && \
-	STRACE_OPTIONS="${STRACE_OPTIONS:+$STRACE_OPTIONS }${STRACEOPTIONS}"
+	STRACE_OPTIONS="${STRACE_OPTIONS}${STRACE_OPTIONS:+' '}${STRACEOPTIONS}"
     [ -n "$STRACE_DIRECTORY" ] && \
-	STRACE_OPTIONS="${STRACE_OPTIONS:+$STRACE_OPTIONS }-d ${STRACE_DIRECTORY}"
+	STRACE_OPTIONS="${STRACE_OPTIONS}${STRACE_OPTIONS:+' '}-d ${STRACE_DIRECTORY}"
     [ -n "$STRACE_BASENAME" ] && \
-	STRACE_OPTIONS="${STRACE_OPTIONS:+$STRACE_OPTIONS }-b ${STRACE_BASENAME}"
+	STRACE_OPTIONS="${STRACE_OPTIONS}${STRACE_OPTIONS:+' '}-b ${STRACE_BASENAME}"
     [ -n "$STRACE_OUTFILE" ] && \
-	STRACE_OPTIONS="${STRACE_OPTIONS:+$STRACE_OPTIONS }-o ${STRACE_OUTFILE}"
+	STRACE_OPTIONS="${STRACE_OPTIONS}${STRACE_OPTIONS:+' '}-o ${STRACE_OUTFILE}"
     [ -n "$STRACE_ERRFILE" ] && \
-	STRACE_OPTIONS="${STRACE_OPTIONS:+$STRACE_OPTIONS }-e ${STRACE_ERRFILE}"
+	STRACE_OPTIONS="${STRACE_OPTIONS}${STRACE_OPTIONS:+' '}-e ${STRACE_ERRFILE}"
     [ -n "$STRACE_LOGDEVICE" ] && \
-	STRACE_OPTIONS="${STRACE_OPTIONS:+$STRACE_OPTIONS }-l ${STRACE_LOGDEVICE}"
+	STRACE_OPTIONS="${STRACE_OPTIONS}${STRACE_OPTIONS:+' '}-l ${STRACE_LOGDEVICE}"
     [ -n "$STRACE_MODULES" ] && \
-	STRACE_OPTIONS="${STRACE_OPTIONS:+$STRACE_OPTIONS }${STRACE_MODULES}"
+	STRACE_OPTIONS="${STRACE_OPTIONS}${STRACE_OPTIONS:+' '}${STRACE_MODULES}"
 }
 
-start() {
+start () {
     [ -d "$STRACE_DIRECTORY" -o -z "$STRACE_DIRECTORY" ] || \
 	action $"Creating $STRACE_DIRECTORY: " \
 	    mkdir -p -- "$STRACE_DIRECTORY" \
@@ -282,33 +389,46 @@ start() {
     return $RETVAL
 }
 
-stop() {
+stop () {
     daemon_stop $execfile || RETVAL=$?
     [ $RETVAL -eq 0 ] && rm -f -- $lockfile
     return $RETVAL
 }
 
-restart() {
-    stop
-    start
-    return $?
+restart () {
+    stop  || RETVAL=$?
+    start || RETVAL=$?
+    return $RETVAL
 }
 
-reload() {
-    echo -en "Reloading $processname: "
-    killproc $processname -HUP
-    echo ""
-    return $?
+reload () {
+    daemon_reload $execfile || RETVAL=$?
+    return $RETVAL
+}
+
+show () {
+    echo "$script: show: not yet implemented." >&2
+    RETVAL=1
+    return $RETVAL
+}
+
+usage () {
+    echo "Usage: $script (start|stop|status|restart|try-restart|condrestart|force-reload|reload|probe|show)" >&2
+    RETVAL=1
+    return $RETVAL
 }
 
 case "$1" in
-    (start|stop|reload|restart)
+    (start|stop|reload|restart|show)
 	$1 || RETVAL=$?
+	;;
+    (force-reload)
+	reload || RETVAL=$?
 	;;
     (status)
 	$1 $name || RETVAL=$?
 	;;
-    (condrestart)
+    (try-restart|condrestart)
 	[ -f $lockfile ] && restart || RETVAL=$?
 	;;
     (probe)
@@ -347,11 +467,11 @@ case "$1" in
 	RETVAL=$?
 	;;
     (*)
-	echo "Usage: $0 (start|stop|status|reload|restart|condrestart|probe)"
+	usage || RETVAL=$?
 	;;
 esac
 
-[ "${0##*/}" = "$name" ] && exit $RETVAL
+[ "${0##*/}" = "$script" ] && exit $RETVAL
 
 # =============================================================================
 # 
@@ -359,7 +479,7 @@ esac
 #
 # -----------------------------------------------------------------------------
 #
-# Copyright (c) 2008-2009  Monavacon Limited <http://www.monavacon.com/>
+# Copyright (c) 2008-2011  Monavacon Limited <http://www.monavacon.com/>
 # Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
 # Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>
 #
@@ -419,4 +539,5 @@ esac
 # - added files to new distro
 #
 # =============================================================================
+
 # vim: ft=sh sw=4 tw=80
