- finalizing init scripts

diff --git a/src/util/init/strerr b/src/util/init/strerr
--- a/src/util/init/strerr
+++ b/src/util/init/strerr
@@ -1,9 +1,9 @@
 #!/bin/bash
 #
 # @(#) $RCSfile: strerr,v $ $Name:  $($Revision: 1.1.2.2 $) $Date: 2011-02-07 04:44:28 $
-# Copyright (c) 2008-2009  Monavacon Limited <http://www.monavacon.com/>
+# Copyright (c) 2008-2011  Monavacon Limited <http://www.monavacon.com/>
 # Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
-# Copyright (c) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>
+# Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>
 # All Rights Reserved.
 #
 # Distributed by OpenSS7 Corporation.  See the bottom of this script for copying
@@ -12,14 +12,14 @@
 # Redhat chkconfig init script conventions
 #
 # strerr:	start and stop strerr facility
-# chkconfig:	- 03 96
+# chkconfig:	2345 03 96
 # lockfile:	/var/lock/subsys/strerr
 # config:	/etc/default/strerr
 # processname:	strerr
 # pidfile:	/var/run/strerr.pid
 # probe:	true
 # hide:		false
-# license:	GPL
+# license:	AGPL
 # description:	This STREAMS init script is part of Linux Fast-STREAMS.  It is \
 #		responsible for starting and stopping the STREAMS error \
 #		logger.  The STREAMS error logger should only be run under \
@@ -32,27 +32,33 @@
 # Provides: strerr
 # Required-Start: streams
 # Required-Stop: streams
-# Default-Start: 4
-# Default-Stop: 0 1 2 3 4 5 6
+# Should-Start: $syslog
+# Should-Stop: $syslog
+# Default-Start: 2 3 4 5
+# Default-Stop:
 # X-UnitedLinux-Default-Enabled: yes
 # Short-Description: start and stop strerr
-# License: GPL
+# License: AGPL
 # Description:	This STREAMS init script is part of Linux Fast-STREAMS.  It is
 #	responsible for starting and stopping the STREAMS error logger.  The
 #	STREAMS error logger should only be run under exceptional circumstances
 #	and this init script is not activated in any run level by default.
 ### END INIT INFO
 
-# Source init script functions library
+PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
+
+# Source init script functions library.
 init_mode="standalone"
   if [ -r /etc/init.d/functions   ] ; then . /etc/init.d/functions   ; init_mode="chkconfig" ;
 elif [ -r /etc/rc.status          ] ; then . /etc/rc.status          ; init_mode="insserv"   ;
 elif [ -r /lib/lsb/init-functions ] ; then . /lib/lsb/init-functions ; init_mode="lsb"       ;
+elif [ -r /sbin/start-stop-daemon ] ; then                             init_mode="debian"    ;
 fi
 
 case "$init_mode" in
     (chkconfig)
-	daemon_start() {
+	# RedHat's LSB support is not so good, use native functions first.
+	daemon_start () {
 	    local force= nicelevel= base=
 	    while [ "$1" != "${1##[-+]}" ] ; do
 		case $1 in
@@ -62,32 +68,33 @@ case "$init_mode" in
 	    done
 	    base=`echo $1 | sed -e 's,.*/,,'`
 	    echo -en "Starting daemon $base: "
-	    daemon $force $nicelevel $*
+	    daemon $force $nicelevel "$@"
 	    RETVAL=$?
 	    echo ""
 	    return $RETVAL
 	}
-	daemon_stop() {
+	daemon_stop () {
 	    local base=
 	    base=`echo $1 | sed -e 's,.*/,,'`; shift 1
 	    echo -en "Stopping daemon $base: "
-	    killproc $base $*
+	    killproc $base "$@"
+	    RETVAL=$?
+	    echo ""
+	    return $RETVAL
+	}
+	daemon_reload () {
+	    local base=
+	    base=`echo $1 | sed -e 's,.*/,,'`; shift 1
+	    echo -en "Reloading daemon $base: "
+	    killproc $base -HUP
 	    RETVAL=$?
 	    echo ""
 	    return $RETVAL
 	}
 	;;
     (insserv)
-	action() {
-	    echo -en "$1"
-	    shift 1
-	    ${1+"$@"} >/dev/null
-	    RETVAL=$?
-	    [ $RETVAL -eq 0 ] || rc_failed $RETVAL
-	    rc_status -v
-	    return $RETVAL
-	}
-	daemon_start() {
+	# SuSE's LSB support is not so good, use native functions first.
+	daemon_start () {
 	    local force= nicelevel= base=
 	    while [ "$1" != "${1##[-+]}" ] ; do
 		case $1 in
@@ -97,17 +104,36 @@ case "$init_mode" in
 	    done
 	    base=`echo $1 | sed -e 's,.*/,,'`
 	    echo -en "Starting daemon $base: "
-	    startproc $force $nicelevel $*
+	    startproc $force $nicelevel "$@"
 	    RETVAL=$?
 	    [ $RETVAL -eq 0 ] || rc_failed $RETVAL
 	    rc_status -v
 	    return $RETVAL
 	}
-	daemon_stop() {
+	daemon_stop () {
 	    local base=
 	    base=`echo $1 | sed -e 's,.*/,,'`; shift 1
 	    echo -en "Stopping daemon $base: "
-	    killproc $base $*
+	    killproc $base "$@"
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] || rc_failed $RETVAL
+	    rc_status -v
+	    return $RETVAL
+	}
+	daemon_reload () {
+	    local base=
+	    base=`echo $1 | sed -e 's,.*/,,'`; shift 1
+	    echo -en "Reloading daemon $base: "
+	    killproc $base -HUP
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] || rc_failed $RETVAL
+	    rc_status -v
+	    return $RETVAL
+	}
+	action () {
+	    echo -en "$1"
+	    shift 1
+	    ${1+"$@"} >/dev/null
 	    RETVAL=$?
 	    [ $RETVAL -eq 0 ] || rc_failed $RETVAL
 	    rc_status -v
@@ -115,7 +141,7 @@ case "$init_mode" in
 	}
 	;;
     (lsb)
-	daemon_start() {
+	daemon_start () {
 	    local force= nicelevel= base=
 	    while [ "$1" != "${1##[-+]}" ] ; do
 		case $1 in
@@ -125,21 +151,30 @@ case "$init_mode" in
 	    done
 	    base=`echo $1 | sed -e 's,.*/,,'`
 	    echo -en "Starting daemon $base: "
-	    start_daemon $force $nicelevel $*
+	    start_daemon $force $nicelevel "$@"
 	    RETVAL=$?
 	    [ $RETVAL -eq 0 ] && log_success_msg || log_failure_msg
 	    return $RETVAL
 	}
-	daemon_stop() {
+	daemon_stop () {
 	    local base=
 	    base=`echo $1 | sed -e 's,.*/,,'`; shift 1
 	    echo -en "Stopping daemon $base: "
-	    killproc $base $*
+	    killproc $base "$@"
 	    RETVAL=$?
 	    [ $RETVAL -eq 0 ] && log_success_msg || log_failure_msg
 	    return $RETVAL
 	}
-	action() {
+	daemon_reload () {
+	    local base=
+	    base=`echo $1 | sed -e 's,.*/,,'`; shift 1
+	    echo -en "Reloading daemon $base: "
+	    killproc $base -HUP
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] && log_success_msg || log_failure_msg
+	    return $RETVAL
+	}
+	action () {
 	    echo -en "$1"
 	    shift 1
 	    ${1+"$@"} >/dev/null
@@ -148,40 +183,93 @@ case "$init_mode" in
 	    return $RETVAL
 	}
 	;;
+    (debian)
+	# a resonably modern debian system will have LSB support
+	daemon_start () {
+	    local force= nicelevel= base=
+	    while [ "$1" != "${1##[+-]}" ] ; do
+		case $1 in
+		    (-f) force="" ; shift 1 ;;
+		    (-n) nicelevel="-N $2"  ; shift 2 ;;
+		esac
+	    done
+	    base=`echo $1 | sed -e 's,.*/,,'`
+	    echo -en "Starting daemon $base: "
+	    start-stop-daemon --start $force $nicelevel --quiet \
+		--pidfile $pidfile --exec $execfile -- "$@"
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] || echo "(failed)"; echo "."
+	    return $RETVAL
+	}
+	daemon_stop () {
+	    local base=
+	    base=`echo $1 | sed -e 's,.*/,,'`; shift 1
+	    echo -en "Stopping daemon $base: "
+	    start-stop-daemon --stop --quiet --retry=1 --oknodo \
+		--pidfile $pidfile --exec $execfile
+	    RETVAL=$?
+	      if [ $RETVAL -eq   0 ] ; then echo "."
+	    elif [ $RETVAL -eq 255 ] ; then echo "(warning)."
+	    else                            echo "failed!"
+	    fi
+	    return $RETVAL
+	}
+	daemon_reload () {
+	    local base=
+	    base=`echo $1 | sed -e 's,.*/,,'`; shift 1
+	    echo -en "Reloading daemon $base: "
+	    killproc $base -HUP
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] || echo "(failed)"; echo "."
+	    return $RETVAL
+	}
+	action () {
+	    echo -en "$1"
+	    shift 1
+	    eval "\${1+\"\$@\"} $redir"
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] || echo "(failed)"; echo "."
+	    return $RETVAL
+	}
+	;;
     (standalone|*)
-	log_success_msg() {
-	    echo -e "\t...SUCCESS\n"
-	}
-	log_failure_msg() {
-	    echo -e "\t...FAILED\n"
-	}
 	if [ -x /sbin/pidof ] ; then
-	    pidofproc() {
+	    pidofproc () {
 		/sbin/pidof $@
 	    }
 	elif [ -x /sbin/pidofproc ] ; then
-	    pidofproc() {
+	    pidofproc () {
 		/sbin/pidofproc $@
 	    }
 	else
-	    pidofproc() {
+	    pidofproc () {
 		[ -r $pidfile ] && cat $pidfile
 	    }
 	fi
-	if [ -x /sbin/killproc ] ; then
-	    killproc() {
+	if [ -x /sbin/start-stop-daemon ] ; then
+	    killproc () {
+		local base execfile
+		base=$1
+		execfile=$2
+		shift 2
+		start-stop-daemon --stop --quiet --retry=1 --oknodo \
+		    --pidfile $pidfile \
+		    --exec $execfile
+	    }
+	elif [ -x /sbin/killproc ] ; then
+	    killproc () {
 		/sbin/killproc $@
 	    }
 	elif [ -x /usr/bin/killall ] ; then
-	    killproc() {
+	    killproc () {
 		/usr/bin/killall $@
 	    }
 	else
-	    killproc() {
+	    killproc () {
 		[ -r $pidfile ] && kill "$2" `cat $pidfile`
 	    }
 	fi
-	daemon_start() {
+	daemon_start () {
 	    local force= nicecmd= base=
 	    while [ "$1" != "${1##[-+]}" ] ; do
 		case $1 in
@@ -191,25 +279,34 @@ case "$init_mode" in
 	    done
 	    base=`echo $1 | sed -e 's,.*/,,'`
 	    echo -en "Starting daemon $base: "
-	    ( $* >/dev/null 2>&1 </dev/null & )
+	    eval "( $nicecmd \"\$@\" >/dev/null 2>&1 </dev/null & )"
 	    RETVAL=$?
 	    [ $RETVAL -eq 0 ] && echo -en "\t...SUCCESS" || echo -en "\t....FAILED"
 	    return $RETVAL
 	}
-	daemon_stop() {
+	daemon_stop () {
 	    local base=
 	    base=`echo $1 | sed -e 's,.*/,,'`; shift 1
 	    echo -en "Stopping daemon $base: "
 	    if pidofproc $base >/dev/null 2>&1 ; then
 		RETVAL=0
 	    else
-		killproc $base $*
+		killproc $base "$@"
 		RETVAL=$?
 	    fi
 	    [ $RETVAL -eq 0 ] && log_success_msg || log_failure_msg
 	    return $RETVAL
 	}
-	action() {
+	daemon_reload () {
+	    local base=
+	    base=`echo $1 | sed -e 's,.*/,,'`; shift 1
+	    echo -en "Reloading daemon $base: "
+	    killproc $base -HUP
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] && echo -en "\t...SUCCESS" || echo -en "\t....FAILED"
+	    return $RETVAL
+	}
+	action () {
 	    echo -en "$1"
 	    shift 1
 	    ${1+"$@"} >/dev/null
@@ -221,11 +318,14 @@ case "$init_mode" in
 esac
 
 name='strerr'
+script='strerr'
+ucname="STRERR"
 lockfile="/var/lock/subsys/$name"
-config="/etc/sysconfig/$name"
+config="/etc/sysconfig/$name /etc/default/$name"
 processname="$name"
 pidfile="/var/run/$processname.pid"
 execfile="/usr/sbin/$processname"
+desc="the STREAMS error logger"
 
 if [ ! -x $execfile ] ; then if [ "$1" = "stop" ] ; then exit 0 ; else exit 5 ; fi ; fi
 
@@ -249,26 +349,35 @@ RETVAL=0
 
 umask 077
 
-build_options() {
+case ":$VERBOSE" in
+    :no|:NO|:false|:FALSE|:0|:)
+	redir='>/dev/null 2>&1'
+	;;
+    *)
+	redir=
+	;;
+esac
+
+build_options () {
     # Build up the options string
     STRERR_OPTIONS="-p $pidfile"
     [ -n "$STRERROPTIONS" ] && \
-	STRERR_OPTIONS="${STRERR_OPTIONS:+$STRERR_OPTIONS }${STRERROPTIONS}"
+	STRERR_OPTIONS="${STRERR_OPTIONS}${STRERR_OPTIONS:+' '}${STRERROPTIONS}"
     [ -n "$STRERR_MAILUID" ] && \
-	STRERR_OPTIONS="${STRERR_OPTIONS:+$STRERR_OPTIONS }-a ${STRERR_MAILUID}"
+	STRERR_OPTIONS="${STRERR_OPTIONS}${STRERR_OPTIONS:+' '}-a ${STRERR_MAILUID}"
     [ -n "$STRERR_DIRECTORY" ] && \
-	STRERR_OPTIONS="${STRERR_OPTIONS:+$STRERR_OPTIONS }-d ${STRERR_DIRECTORY}"
+	STRERR_OPTIONS="${STRERR_OPTIONS}${STRERR_OPTIONS:+' '}-d ${STRERR_DIRECTORY}"
     [ -n "$STRERR_BASENAME" ] && \
-	STRERR_OPTIONS="${STRERR_OPTIONS:+$STRERR_OPTIONS }-b ${STRERR_BASENAME}"
+	STRERR_OPTIONS="${STRERR_OPTIONS}${STRERR_OPTIONS:+' '}-b ${STRERR_BASENAME}"
     [ -n "$STRERR_OUTFILE" ] && \
-	STRERR_OPTIONS="${STRERR_OPTIONS:+$STRERR_OPTIONS }-o ${STRERR_OUTFILE}"
+	STRERR_OPTIONS="${STRERR_OPTIONS}${STRERR_OPTIONS:+' '}-o ${STRERR_OUTFILE}"
     [ -n "$STRERR_ERRFILE" ] && \
-	STRERR_OPTIONS="${STRERR_OPTIONS:+$STRERR_OPTIONS }-e ${STRERR_ERRFILE}"
+	STRERR_OPTIONS="${STRERR_OPTIONS}${STRERR_OPTIONS:+' '}-e ${STRERR_ERRFILE}"
     [ -n "$STRERR_LOGDEVICE" ] && \
-	STRERR_OPTIONS="${STRERR_OPTIONS:+$STRERR_OPTIONS }-l ${STRERR_LOGDEVICE}"
+	STRERR_OPTIONS="${STRERR_OPTIONS}${STRERR_OPTIONS:+' '}-l ${STRERR_LOGDEVICE}"
 }
 
-start() {
+start () {
     [ -d "$STRERR_DIRECTORY" -o -z "$STRERR_DIRECTORY" ] || \
 	action $"Creating $STRERR_DIRECTORY: " \
 	    mkdir -p -- "$STRERR_DIRECTORY" \
@@ -280,33 +389,46 @@ start() {
     return $RETVAL
 }
 
-stop() {
+stop () {
     daemon_stop $execfile || RETVAL=$?
     [ $RETVAL -eq 0 ] && rm -f -- $lockfile
     return $RETVAL
 }
 
-restart() {
-    stop
-    start
-    return $?
+restart () {
+    stop  || RETVAL=$?
+    start || RETVAL=$?
+    return $RETVAL
 }
 
-reload() {
-    echo -en "Reloading $processname: "
-    killproc $processname -HUP
-    echo ""
-    return $?
+reload () {
+    daemon_reload $execfile || RETVAL=$?
+    return $RETVAL
+}
+
+show () {
+    echo "$script: show: not yet implemented." >&2
+    RETVAL=1
+    return $RETVAL
+}
+
+usage () {
+    echo "Usage: $script (start|stop|status|restart|try-restart|condrestart|force-reload|reload|probe|show)" >&2
+    RETVAL=1
+    return $RETVAL
 }
 
 case "$1" in
-    (start|stop|reload|restart)
+    (start|stop|reload|restart|show)
 	$1 || RETVAL=$?
+	;;
+    (force-reload)
+	reload || RETVAL=$?
 	;;
     (status)
 	$1 $name || RETVAL=$?
 	;;
-    (condrestart)
+    (try-restart|condrestart)
 	[ -f $lockfile ] && restart || RETVAL=$?
 	;;
     (probe)
@@ -345,11 +467,11 @@ case "$1" in
 	RETVAL=$?
 	;;
     (*)
-	echo "Usage: $0 (start|stop|status|reload|restart|condrestart|probe)"
+	usage || RETVAL=$?
 	;;
 esac
 
-[ "${0##*/}" = "$name" ] && exit $RETVAL
+[ "${0##*/}" = "$script" ] && exit $RETVAL
 
 # =============================================================================
 # 
@@ -357,9 +479,9 @@ esac
 #
 # -----------------------------------------------------------------------------
 #
-# Copyright (c) 2008-2009  Monavacon Limited <http://www.monavacon.com/>
+# Copyright (c) 2008-2011  Monavacon Limited <http://www.monavacon.com/>
 # Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
-# Copyright (c) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>
+# Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>
 #
 # All Rights Reserved.
 #
@@ -411,4 +533,5 @@ esac
 # - added files to new distro
 #
 # =============================================================================
+
 # vim: ft=sh sw=4 tw=80
diff --git a/src/util/openss7-update b/src/util/openss7-update
--- a/src/util/openss7-update
+++ b/src/util/openss7-update
@@ -31,14 +31,374 @@ fi
 
 update="$awk -f $script --"
 
+
+openss7_update () { :
+    return $update "$@"
+}
+
+# INSTALLING A KERNEL
+#
+#
+ou_preinst_install () { :
+}
+ou_postrm_abort_install () { :
+}
+
+# UPGRADING A KERNEL
+#
+ou_prerm_upgrade () { :
+}
+ou_prerm_failed_upgrade () { :
+}
+ou_preinst_upgrade () { :
+}
+ou_postrm_abort_upgrade () { :
+}
+ou_postrm_upgrade () { :
+}
+ou_postrm_failed_upgrade () { :
+}
+ou_preinst_abort_upgrade () { :
+}
+ou_postinst_abort_upgrade () { :
+}
+
+# REMOVING A KERNEL
+#
+ou_prerm_remove () { :
+}
+ou_postinst_abort_remove () { :
+}
+ou_postrm_remove () { :
+}
+
+# CONFIGURING A KERNEL
+#
+ou_postinst_configure () { :
+}
+
+
+# PURGING A KERNEL
+#
+ou_postrm_purge () { :
+}
+
+
+
+
+
+
+
+#
+# Note that for 'install' there is nothing really to do here.  On an 'upgrade'
+# we should preserve our relinked modules somewhere in case the upgrade is
+# aborted.  Also, for a running kernel we might want to remove the modules and
+# re-depmod with them removed so that the running kernel will not attempt to
+# load the new kernel modules being installed.  On an 'abort-upgrade' we can
+# restore the kernel modules from where we saved them.
+#
+
+# All parameters are for the linux-image-2.6.M[.REV]-ABI-FLAVOR package.
+
+# new-preinst install		[old-version]
+ou_preinst_install () { :
+    if [ "${2:+'set'}" != 'set' ]
+    then : # install fresh
+    else : # install with some configuration from old-version
+    fi
+    return 0
+}
+# new-preinst upgrade		old-version
+ou_preinst_upgrade () { :
+    # - old-prerm	upgrade new-version		...success
+    # - new-preinst	upgrade old-version		...success
+}
+# old-preinst abort-upgrade	new-version
+ou_preinst_abort_upgrade () { :
+    # The sequence here is:
+    # - old-prerm upgrade new-version		...failed
+    # - new-prerm failed-upgrade new-version	...failed
+    # * old-postinst abort-upgrade new-version
+}
+ou_preinst () { :
+    operation="$1"; shift
+    case "$operation" in
+	install)
+	    return ou_preinst_install		"$@" ;;
+	upgrade)
+	    return ou_preinst_upgrade		"$@" ;;
+	abort-upgrade)
+	    return ou_preinst_abort_upgrade		"$@" ;;
+	*)
+	    return 0 ;;
+    esac
+}
+
+#
+# Add symbolic links to the openss7 weak-updates directories.  This consists of
+# calling:
+#		openss7-modules -- -v --add-kernel $1
+#
+# Note that this step is not completely necessary because it will be run when
+# the kernel boots (if ever).
+#
+# Technically it is possible to query the user at this point for some optional
+# actions.  We can even abort the installation process for a kernel using exit
+# status because Debian is smart enough to execute hooks before updating the
+# boot-loader.
+#
+# If we are updating the running kernel and openss7 kernel modules requiring
+# relinking are installed in the running kernel's modules directory, we must
+# signal that an immediate reboot is required. --add-kernel will not relink
+# modules for the running kernel because the modules could mismatch the running
+# kernel.  It takes the --boot-kernel option to do that on reboot.
+#
+# If weak-updates for the kernel being installed are not possible (i.e. there is
+# no "solution" for the kernel being installed), then the user should be
+# prompted as to whether they want to complete configuring the kernel without
+# openss7 module support.
+#
+# If the kernel being updated uses a different ABI or a different M[.REV] and a
+# solution is possible, the user should be prompted (because weak-updates are
+# dangerous in this case).
+#
+# openss7-modules exit status codes can be used to determine this information.
+# Also, a dry-run can be performed just to get the return status.
+#
+
+# All parameters are for the linux-image-2.6.M[.REV]-ABI-FLAVOR package.
+
+# xxx-postinst configure	[most-recently-configured-version]
+ou_postinst_configure () { :
+}
+# xxx-triggered			triggering-packages ...
+ou_postinst_triggered () { :
+}
+# old-postinst abort-upgrade	new-version
+ou_postinst_abort_upgrade () { :
+}
+# con-postinst abort-remove	'in-favor' package new-version
+# xxx-postinst abort-remove
+ou_postinst_abort_remove () { :
+}
+# dec-postinst abort-deconfigure
+#				'in-favor' failed-install-package version
+#				['removing' conflicting-package version]
+ou_postinst_abort_deconfigure () { :
+}
+ou_postinst () { :
+    operation="$1"; shift
+    case "$operation" in
+	configure)
+	    return ou_postinst_configure		"$@" ;;
+	triggered)
+	    return ou_postinst_triggered		"$@" ;;
+	abort-upgrade)
+	    return ou_postinst_abort_upgrade		"$@" ;;
+	abort-remove)
+	    return ou_postinst_abort_remove		"$@" ;;
+	abort-deconfigure)
+	    return ou_postinst_abort_deconfigure	"$@" ;;
+	*)
+	    return 0 ;;
+    esac
+}
+
+# All parameters are for the linux-image-2.6.M[.REV]-ABI-FLAVOR package.
+
+# xxx-prerm remove
+# con-prerm remove		'in-favour' package new-version
+ou_prerm_remove () { :
+}
+# old-prerm upgrade		new-version
+ou_prerm_upgrade () { :
+}
+# new-prerm failed-upgrade	old-version
+ou_prerm_failed_upgrade () { :
+}
+# dec-prerm deconfigure		'in-favour' package-being-installed version
+#				['removing' conflicting-package version]
+ou_prerm_deconfigure () { :
+}
+ou_prerm () { :
+    operation="$1"; shift
+    case "$operation" in
+	remove)
+	    return ou_prerm_remove			"$@" ;;
+	upgrade)
+	    return ou_prerm_upgrade			"$@" ;;
+	failed-upgrade)
+	    return ou_prerm_failed_upgrade		"$@" ;;
+	deconfigure)
+	    return ou_prerm_deconfigure			"$@" ;;
+	*)
+	    return 0 ;;
+    esac
+}
+
+#
+# Remove symbolic links from the openss7 weak-updates directories.  This
+# consists of calling:
+#
+#	openss7-modules -- -v --remove-kernel $1
+#
+# Not that this step is not completely necessary, some symbolic links will just
+# unnecessarily hang around if it is not performed.
+#
+# Technically it is possible to query the user at this point for some optional
+# actions.  We can even abort the removal process for a kernel using exit status
+# because Debian is smart enough to execute hooks before updating the
+# boot-loader.
+#
+# For 'remove' and 'purge' removing symbolic links is fine.  However, for
+# 'upgrade', where the 'new-version' is the same as a version that is already
+# installed, and even for the running kernel, the situation is more complex.
+#
+# Another thing that can be performed here is that when a kernel is removed, if
+# no other kernels requiring a set of openss7 modules remain, we can mark the
+# corresponding openss7 package for autoclean.
+#
+
+# All parameters are for the linux-image-2.6.M[.REV]-ABI-FLAVOR package.
+
+# xxx-postrm remove
+ou_postrm_remove () { :
+}
+# xxx-postrm purge
+ou_postrm_purge () { :
+}
+# old-postrm upgrade		new-version
+ou_postrm_upgrade () { :
+}
+# new-postrm failed-upgrade	old-version
+ou_postrm_failed_upgrade () { :
+}
+# new-postrm abort-install	[old-version]
+ou_postrm_abort_install () { :
+}
+# new-postrm abort-upgrade	old-version
+ou_postrm_abort_upgrade () { :
+}
+# dis-postrm disappear		overwriter overwriter-version
+ou_postrm_disappear () { :
+}
+ou_postrm () { :
+    operation="$1"; shift
+    case "$operation" in
+	remove)
+	    return ou_postrm_remove			"$@" ;;
+	purge)
+	    return ou_postrm_purge			"$@" ;;
+	upgrade)
+	    return ou_postrm_upgrade			"$@" ;;
+	failed-upgrade)
+	    return ou_postrm_failed_upgrade		"$@" ;;
+	abort-install)
+	    return ou_postrm_abort_install		"$@" ;;
+	abort-upgrade)
+	    return ou_postrm_abort_upgrade		"$@" ;;
+	disappear)
+	    return ou_postrm_disappear			"$@" ;;
+	*)
+	    return 0 ;;
+    esac
+}
+
+#
+# All parameters are for the linux-headers-2.6.M[.REV]-ABI-FLAVOR package.
+#
+
+# xxx-postinst configure	[most-recently-configured-version]
+ou_hdr_postinst_configure () { :
+}
+# xxx-triggered			triggering-packages ...
+ou_hdr_postinst_triggered () { :
+}
+# old-postinst abort-upgrade	new-version
+ou_hdr_postinst_abort_upgrade () { :
+}
+# con-postinst abort-remove	'in-favor' package new-version
+# xxx-postinst abort-remove
+ou_hdr_postinst_abort_remove () { :
+}
+# dec-postinst abort-deconfigure
+#				'in-favor' failed-install-package version
+#				['removing' conflicting-package version]
+ou_hdr_postinst_abort_deconfigure () { :
+}
+ou_hdr_postinst () { :
+    operation="$1"; shift
+    case "$operation" in
+	configure)
+	    return ou_hdr_postinst_configure		"$@" ;;
+	triggered)
+	    return ou_hdr_postinst_triggered		"$@" ;;
+	abort-upgrade)
+	    return ou_hdr_postinst_abort_upgrade	"$@" ;;
+	abort-remove)
+	    return ou_hdr_postinst_abort_remove		"$@" ;;
+	abort-deconfigure)
+	    return ou_hdr_postinst_abort_deconfigure	"$@" ;;
+	*)
+	    return 0 ;;
+    esac
+}
+
+#
+# All parameters are for the linux-source-2.6.M[.REV] package.
+#
+
+# xxx-postinst configure	[most-recently-configured-version]
+ou_src_postinst_configure () { :
+}
+# xxx-triggered			triggering-packages ...
+ou_src_postinst_triggered () { :
+}
+# old-postinst abort-upgrade	new-version
+ou_src_postinst_abort_upgrade () { :
+}
+# con-postinst abort-remove	'in-favor' package new-version
+# xxx-postinst abort-remove
+ou_src_postinst_abort_remove () { :
+}
+# dec-postinst abort-deconfigure
+#				'in-favor' failed-install-package version
+#				['removing' conflicting-package version]
+ou_src_postinst_abort_deconfigure () { :
+}
+ou_src_postinst ()  { :
+    operation="$1"; shift
+    case "$operation" in
+	configure)
+	    return ou_src_postinst_configure		"$@" ;;
+	triggered)
+	    return ou_src_postinst_triggered		"$@" ;;
+	abort-upgrade)
+	    return ou_src_postinst_abort_upgrade	"$@" ;;
+	abort-remove)
+	    return ou_src_postinst_abort_remove		"$@" ;;
+	abort-deconfigure)
+	    return ou_src_postinst_abort_deconfigure	"$@" ;;
+	*)
+	    return 0 ;;
+    esac
+}
+
 case "$command" in
-	/sbin/openss7-update)			$update "$@" || exit $? ;;
-	/usr/sbin/openss7-update)		$update "$@" || exit $? ;;
-	/etc/kernel/preinst.d/openss7-update)	exit 0 ;;
-	/etc/kernel/postinst.d/openss7-update)	$update -q -e --add-kernel    "$1" || exit $? ;;
-	/etc/kernel/prerm.d/openss7-update)	$update -q -e --remove-kernel "$1" || exit $? ;;
-	/etc/kernel/postrm.d/openss7-update)	$update -q -e --remove-kernel "$1" || exit $? ;;
-	/etc/kernel/header_postinst.d)		exit 0 ;;
-	/etc/kernel/src_postinst.d)		exit 0 ;;
-	*)					$update "$@" || exit $? ;;
+    */etc/kernel/preinst.d/openss7-update)
+	return ou_preinst	$DEB_MAINT_PARAMS ;;
+    */etc/kernel/postinst.d/openss7-update)
+	return ou_postinst	$DEB_MAINT_PARAMS ;;
+    */etc/kernel/prerm.d/openss7-update)
+	return ou_prerm		$DEB_MAINT_PARAMS ;;
+    */etc/kernel/postrm.d/openss7-update)
+	return ou_postrm	$DEB_MAINT_PARAMS ;;
+    */etc/kernel/header_postinst.d/openss7-update)
+	return ou_hdr_postinst	$DEB_MAINT_PARAMS ;;
+    */etc/kernel/src_postinst.d/openss7-update)
+	return ou_src_postinst	$DEB_MAINT_PARAMS ;;
+    */sbin/openss7-update | */usr/sbin/openss7-update | *)
+	openss7_update || exit $? ;;
 esac
+
+# vim: tw=80 ft=sh sw=4 noet nocin nosi formatoptions+=tcqlorn
