- working up slackware repositories

diff --git a/slack/doinst.sh-openss7-doc.in b/slack/doinst.sh-openss7-doc.in
--- a/slack/doinst.sh-openss7-doc.in
+++ b/slack/doinst.sh-openss7-doc.in
@@ -2,7 +2,7 @@
 # @configure_input@
 # =============================================================================
 # 
-# @(#) $RCSfile: openss7-doc.preinst.in,v $ $Name:  $($Revision: 1.1.2.3 $) $Date: 2011-05-15 12:01:18 $
+# @(#) $RCSfile$ $Name$($Revision$) $Date$
 #
 # -----------------------------------------------------------------------------
 #
@@ -48,10 +48,9 @@
 #
 # -----------------------------------------------------------------------------
 #
-# Last Modified $Date: 2011-05-15 12:01:18 $ by $Author: brian $
+# Last Modified $Date$ by $Author$
 #
 # =============================================================================
-subpkg=doc
 @openss7_header@
 datarootdir=@datarootdir@
 # -----------------------------------------------------------------------------
@@ -84,62 +83,71 @@ preinst_manpages () { :
     fi
 }
 #
-# preinst_install() - This is an initial installation of the base subpackage.  We need to check for
-#   non-deb installations on the host and remove any entries that might later conflict with out
-#   entries.  We treat every fresh installation like an upgrade from non-deb/rpm install.
+# preinst_doc() - This is an initial installation of the base subpackage.  We
+#   need to check for non-deb installations on the host and remove any entries
+#   that might later conflict with out entries.  We treat every fresh
+#   installation like an upgrade from non-deb/rpm install.
 #
-preinst_install () { :
+preinst_doc () { :
     preinst_manpages || :
 }
+
 # -----------------------------------------------------------------------------
-# Primary functions:
+# Auxiliary functions:
 # -----------------------------------------------------------------------------
-# new-preinst install
-install_preinst () { :
-    preinst_install || :
+#
+# postinst_manpages() - Add our manual pages to the aprospros database.  One
+#   problem with doing this is that even the oldest of debian policies and
+#   debhelper implementations will implement the debhelper code to do this.
+#   Therefore, this function is shortcircuited for now.  (We install >3000
+#   manual pages and it takes forever anyway.)  Failing to do this altogether is
+#   not critical because most machines run an evening cron job to update these.
+#
+postinst_manpages () { :; return
+    if which makewhatis >/dev/null 2>&1 ; then
+	LANGUAGE= LANG= makewhatis -u @mandir@ || true
+    fi
+    if which mandb >/dev/null 2>&1 ; then
+	LANGUAGE= LANG= mandb -p @mandir@ || :true
+    fi
 }
-# new-preinst install old-version
-reinstall_preinst () { :
+#
+# postinst_infofiles() - Add our info files to the info directory.  One problem
+#   with doing this is that even the oldest of debian policies and debhelper
+#   implementations will implement the debhelper code to do this.  Therefore,
+#   this function is shorcricuited for now.  Current debian policies will use
+#   trigger directories to perform this action.
+#
+postinst_infofiles () { :; return
+    if [ -x /sbin/install-info ]; then
+#	Older policies do not compress info files.
+	for n in $manuals; do
+            if [ -f @infodir@/$n.info ] ; then
+                /sbin/install-info --info-dir=@infodir@ @infodir@/$n.info || true
+            elif [ -f @infodir@/$n.info.gz ] ; then
+                /sbin/install-info --info-dir=@infodir@ @infodir@/$n.info.gz || true
+            elif [ -f @infodir@/$n.info.bz2 ] ; then
+                /sbin/install-info --info-dir=@infodir@ @infodir@/$n.info.bz2 || true
+            fi
+        done
+    fi
 }
-# new-preinst upgrade old-version
-upgrade_preinst () { :
+#
+# postinst_doc() - Perform necessary activies for post installation of
+#   documentation files.  This is primarly handing man macros, reference
+#   database, info directories and aprospros databases.  Some of these
+#   operations are performed by debhelper code or directory trigger processing.
+#
+postinst_doc () { :
+    postinst_manpages
+    postinst_infofiles
 }
-# old-postrm upgrade new-version ...FAILED
-# new-postrm failed-upgrade old-version ...FAILED
-# old-preinst abort-upgrade new-version
-abort_upgrade_preinst () { :
-}
-@mscript_preinst@
-@mscript_debhelper@
+
+preinst_doc
+postinst_doc
+
 # =============================================================================
 #
-# $Log: openss7-doc.preinst.in,v $
-# Revision 1.1.2.3  2011-05-15 12:01:18  brian
-# - many build system refinements
-#
-# Revision 1.1.2.2  2011-05-10 13:45:29  brian
-# - weak modules workup
-#
-# Revision 0.9.2.6  2008-04-28 10:30:21  brian
-# - updated headers for release
-#
-# Revision 0.9.2.5  2007/12/15 20:19:30  brian
-# - updates
-#
-# Revision 0.9.2.4  2007/08/13 22:45:54  brian
-# - GPLv3 header updates
-#
-# Revision 0.9.2.3  2006/12/18 10:25:29  brian
-# - updated headers for release
-#
-# Revision 0.9.2.2  2005/05/14 08:34:11  brian
-# - copyright header correction
-#
-# Revision 0.9.2.1  2005/03/26 03:11:24  brian
-# - Reworking maintainance scripts
-#
-# Revision 0.9.2.1  2005/03/24 01:38:17  brian
-# - better debian build
-#
+# $Log$
 # =============================================================================
 # vim: ft=sh sw=4 noet nocin nosi formatoptions+=tcqlorn
