Import from CVS Wed Dec 21 09:59:04 2005 -0600
- corrected removal for SuSE
- shut up syscontrols
- finally shut up sysctl
- just remove links if file does not exit

diff --git a/strutil/scripts/remove_initd b/strutil/scripts/remove_initd
--- a/strutil/scripts/remove_initd
+++ b/strutil/scripts/remove_initd
@@ -1,7 +1,7 @@
 #!/bin/bash
 # =============================================================================
 # 
-# @(#) $RCSfile: remove_initd,v $ $Name:  $($Revision: 0.9.2.7 $) $Date: 2005/12/19 12:44:59 $
+# @(#) $RCSfile: remove_initd,v $ $Name:  $($Revision: 0.9.2.9 $) $Date: 2005/12/21 09:59:04 $
 #
 # -----------------------------------------------------------------------------
 #
@@ -47,11 +47,11 @@
 #
 # -----------------------------------------------------------------------------
 #
-# Last Modified $Date: 2005/12/19 12:44:59 $ by $Author: brian $
+# Last Modified $Date: 2005/12/21 09:59:04 $ by $Author: brian $
 #
 # =============================================================================
 
-ident='@(#) $RCSfile: remove_initd,v $ $Name:  $($Revision: 0.9.2.7 $) $Date: 2005/12/19 12:44:59 $'
+ident='@(#) $RCSfile: remove_initd,v $ $Name:  $($Revision: 0.9.2.9 $) $Date: 2005/12/21 09:59:04 $'
 
 ECHO='echo'
 SHELL='/bin/bash'
@@ -454,14 +454,14 @@ filename="$initrddir/$initname"
 
 just_remove_all=
 if [ ! -f "$filename" ] ; then
-    $ECHO "warning: file '${filename}' does not exist"
+    [ $verbose -gt 1 ] && $ECHO "warning: file '${filename}' does not exist"
     just_remove_all=yes
 fi
 
 basedir=$(basename $initrddir)
 
 if [ "$basedir" != init.d ] ; then
-    $ECHO "warning: path to init.d file should have init.d as its last component instead of $basedir" >&2
+    [ $verbose -gt 1 ] && $ECHO "warning: path to init.d file should have init.d as its last component instead of $basedir" >&2
 fi
 
 rootdir="${initrddir}"
@@ -469,30 +469,33 @@ rootdir=${rootdir//\/rc.d/}
 rootdir=${rootdir//\/init.d/}
 rootdir=${rootdir//\/etc/}
 
-# If we are installing on the host, we might as well use the host's
-# own removal function, it one exists
-if [ -z "$rootdir" ] ; then
-    if [ -x /usr/lib/lsb/install_initd ] ; then
-	$ECHO " /usr/lib/lsb/remove_initd $filename"
-	/usr/lib/lsb/remove_initd $filename
-	RETVAL=$?
-	[ $RETVAL -eq 0 ] && exit 0
-    fi
-    if [ -x /sbin/insserv ] ; then
-	$ECHO " /sbin/insserv -r $filename"
-	/sbin/insserv -r $filename
-	RETVAL=$?
-	[ $RETVAL -eq 0 ] && exit 0
-    fi
-    if [ -x /sbin/chkconfig ] ; then
-	$ECHO " /sbin/chkconfig --del $initname"
-	/sbin/chkconfig --del $initname
-	RETVAL=$?
-	[ $RETVAL -eq 0 ] && exit 0
+if [ x${just_remove_all} != xyes ] ; then
+    # If we are installing on the host, we might as well use the host's
+    # own removal function, it one exists (and the file exists).
+    if [ -z "$rootdir" ] ; then
+	if [ -x /usr/lib/lsb/install_initd ] ; then
+	    [ $verbose -gt 1 ] && $ECHO " /usr/lib/lsb/remove_initd $filename"
+	    /usr/lib/lsb/remove_initd $filename
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] && exit 0
+	fi
+	if [ -x /sbin/insserv ] ; then
+	    [ $verbose -gt 1 ] && $ECHO " /sbin/insserv -r $filename"
+	    /sbin/insserv -r $filename
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] && exit 0
+	elif [ -x /sbin/chkconfig ] ; then
+	# careful, the reason for the elif here is that SuSE chkconfig returns 0 on error
+	    [ $verbose -gt 1 ] && $ECHO " /sbin/chkconfig --del $initname"
+	    /sbin/chkconfig --del $initname
+	    RETVAL=$?
+	    [ $RETVAL -eq 0 ] && exit 0
+	fi
     fi
 fi
 
 # Fall back to doing it ourselves
+[ $verbose -gt 1 ] && $ECHO "warning: $program falling back to manual removal"
 
 sysconfdir="${rootdir}/etc"
 
@@ -528,7 +531,7 @@ elif [ -d $sysconfdir/rc.d/rc0.d ] ; then
     basedir="init.d"
     flavor="chkconfig"
 else
-    $ECHO "warning: $program cannot grok SysV init for $initname" >&2
+    [ $verbose -gt 1 ] && $ECHO "warning: $program cannot grok SysV init for $initname" >&2
     exit 1
 fi
 
