Import from CVS Fri Mar 11 22:19:36 2005 -0600
- Changes to add qlock to strconf and correct 2.6 CFLAGS CPPFLAGS problem.

diff --git a/strutil/scripts/strconf-sh b/strutil/scripts/strconf-sh
--- a/strutil/scripts/strconf-sh
+++ b/strutil/scripts/strconf-sh
@@ -1,7 +1,7 @@
 #!/bin/bash
 # =============================================================================
 # 
-# @(#) $RCSfile: strconf-sh,v $ $Name:  $($Revision: 0.9.2.14 $) $Date: 2005/03/07 06:13:41 $
+# @(#) $RCSfile: strconf-sh,v $ $Name:  $($Revision: 0.9.2.15 $) $Date: 2005/03/11 22:19:36 $
 #
 # -----------------------------------------------------------------------------
 #
@@ -47,7 +47,7 @@
 #
 # -----------------------------------------------------------------------------
 #
-# Last Modified $Date: 2005/03/07 06:13:41 $ by $Author: brian $
+# Last Modified $Date: 2005/03/11 22:19:36 $ by $Author: brian $
 #
 # =============================================================================
 
@@ -178,8 +178,8 @@ do
             optarg=`$echo "X$arg" | $Xsed -e 's/[-_a-zA-Z0-9]*=//'` ;;
         --*=*)
             opt=`$echo -n "X$1" | $Xsed -e 's|=.*||'`
-            $echo "$program: syntax error -- \`$opt' does not accept an argument" 1>&2
-            $echo "$help" 1>&2
+            $echo "$program: syntax error -- \`$opt' does not accept an argument" >&2
+            $echo "$help" >&2
             exit 2 ;;
         -[bhomHprlLsSOk])
             optarg= ;;
@@ -202,8 +202,8 @@ do
                         ;;
                     # the rest have required arguments
                     *)
-                        $echo "$progname: syntax error -- \`$prevopt' requires an argument" 1>&2
-                        $echo "$help" 1>&2
+                        $echo "$progname: syntax error -- \`$prevopt' requires an argument" >&2
+                        $echo "$help" >&2
                         exit 2
                         ;;
                 esac
@@ -292,8 +292,8 @@ do
             more_options=no
             ;;
         -*)
-            $echo "$progname: syntax error -- unrecognized option \`$arg'" 1>&2
-            $echo "$help" 1>&2
+            $echo "$progname: syntax error -- unrecognized option \`$arg'" >&2
+            $echo "$help" >&2
             exit 2
             ;;
         *) # permute all non-options to the end
@@ -311,15 +311,15 @@ if test -n "$prev" ; then
             ;;
         # the rest have required arguments
         *)
-            $echo "$progname: stynax error -- option \`$prevopt' requires an argument" 1>&2
-            $echo "$help" 1>&2
+            $echo "$progname: stynax error -- option \`$prevopt' requires an argument" >&2
+            $echo "$help" >&2
             exit 1
             ;;
     esac
 fi
 
 if test X"$show_version" = Xyes ; then
-    $echo "$progname:"' Version $Name:  $($Revision: 0.9.2.14 $) $Date: 2005/03/07 06:13:41 $' 1>&2
+    $echo "$progname:"' Version $Name:  $($Revision: 0.9.2.15 $) $Date: 2005/03/11 22:19:36 $'
 fi
 
 if test X"$show_help" = Xyes ; then
@@ -453,8 +453,13 @@ do
         continue
     fi
     case ":${tokens[0]}" in
-        :driver)
+        (:driver)
             token=`$echo -n ${tokens[1]} | $strconf_tokenize`
+            eval "otherno=\"\$strconf_driver_lineno_$token\""
+            if test -n "$otherno" ; then
+                $echo "$progname: error: ${infile:-(stdin)} +$lineno : driver \`${tokens[1]}' already defined at line $otherno" >&2
+                continue
+            fi
             major=${tokens[3]}
             case "x$major" in
                 x | x#* | x[-*]*)
@@ -480,7 +485,7 @@ do
                     ((inmajors=(nminors+255)/256))
                     ;;
                 *)  $echo "$progname: syntax error: ${infile:-(stdin)} +$lineno : bad nminors field \`$nminors'" >&2
-                    continue;
+                    continue
                     ;;
             esac
             nmajors=${tokens[5]}
@@ -491,9 +496,10 @@ do
                 x[0-9]*)
                     ;;
                 *)  $echo "$progname: syntax error: ${infile:-(stdin)} +$lineno : bad nmajors field \`$nmajors'" >&2
-                    continue;
+                    continue
                     ;;
             esac
+            eval "strconf_driver_lineno_$token=\"\$lineno\""
             eval "strconf_driver_$token='${tokens[*]}'"
             strconf_driver_names="$strconf_driver_names $token"
             eval "strconf_realname_$token='${tokens[1]}'"
@@ -507,6 +513,12 @@ do
             ;;
         :module)
             token=`$echo -n ${tokens[1]} | $strconf_tokenize`
+            eval "otherno=\"\$strconf_module_lineno_$token\""
+            if test -n "$otherno" ; then
+                $echo "$progname: error: ${infile:-(stdin)} +$lineno : module \`${tokens[1]}' already defined at line $otherno" >&2
+                continue
+            fi
+            eval "strconf_module_lineno_$token=\"\$lineno\""
             eval "strconf_module_$token='${tokens[*]}'"
             strconf_module_names="$strconf_module_names $token"
             eval "strconf_realname_$token='${tokens[1]}'"
@@ -518,7 +530,13 @@ do
             case ":${tokens[1]}" in
                 :driver)
                     token=`$echo -n ${tokens[2]} | $strconf_tokenize`
+                    eval "otherno=\"\$strconf_objname_driver_lineno_$token\""
+                    if test -n "$otherno" ; then
+                        $echo "$progname: error: ${infile:-(stdin)} +$lineno : driver object name \`${tokens[2]}' already defined at line $otherno" >&2
+                        continue
+                    fi
                     object=`$echo -n ${tokens[3]} | $strconf_tokenize`
+                    eval "strconf_objname_driver_lineno_$token=\"\$lineno\""
                     eval "strconf_objname_driver_$token='${tokens[*]}'"
                     eval "strconf_objname_$token=\"$object\""
                     eval "strconf_name_$object=\"$token\""
@@ -527,7 +545,13 @@ do
                     ;;
                 :module)
                     token=`$echo -n ${tokens[2]} | $strconf_tokenize`
+                    eval "otherno=\"\$strconf_objname_module_lineno_$token\""
+                    if test -n "$otherno" ; then
+                        $echo "$progname: error: ${infile:-(stdin)} +$lineno : module object name \`${tokens[2]}' already defined at line $otherno" >&2
+                        continue
+                    fi
                     object=`$echo -n ${tokens[3]} | $strconf_tokenize`
+                    eval "strconf_objname_module_lineno_$token=\"\$lineno\""
                     eval "strconf_objname_module_$token='${tokens[*]}'"
                     eval "strconf_objname_$token=\"$object\""
                     eval "strconf_name_$object=\"$token\""
@@ -536,12 +560,18 @@ do
                     ;;
                 :*)
                     $echo "$progname: syntax error: ${infile:-(stdin)} +$lineno : unknown object name \`${tokens[1]}'" >&2
-                    continue;
+                    continue
                     ;;
             esac
             ;;
         :autopush)
             token=`$echo -n ${tokens[1]} | $strconf_tokenize`
+            eval "otherno=\"\$strconf_autopush_lineno_$token\""
+            if test -n "$otherno" ; then
+                $echo "$progname: error: ${infile:-(stdin)} +$lineno : autopush \`${tokens[1]}' already defined at line $otherno" >&2
+                continue
+            fi
+            eval "strconf_autopush_lineno_$token=\"\$lineno\""
             eval "strconf_autopush_$token='${tokens[*]}'"
             eval "strconf_minor_$token='${tokens[2]}'"
             eval "strconf_lastminor_$token='${tokens[3]}'"
@@ -553,18 +583,42 @@ ${tokens[19]}'"
             ;;
         :loadable)
             token=`$echo -n ${tokens[1]} | $strconf_tokenize`
+            eval "otherno=\"\$strconf_loadable_lineno_$token\""
+            if test -n "$otherno" ; then
+                $echo "$progname: error: ${infile:-(stdin)} +$lineno : loadable \`${tokens[1]}' already defined at line $otherno" >&2
+                continue
+            fi
+            eval "strconf_loadable_lineno_$token=\"\$lineno\""
             eval "strconf_loadable_$token='yes'"
             ;;
         :initialize)
             token=`$echo -n ${tokens[1]} | $strconf_tokenize`
+            eval "otherno=\"\$strconf_initialize_lineno_$token\""
+            if test -n "$otherno" ; then
+                $echo "$progname: error: ${infile:-(stdin)} +$lineno : initialize \`${tokens[1]}' already defined at line $otherno" >&2
+                continue
+            fi
+            eval "strconf_initialize_lineno_$token=\"\$lineno\""
             eval "strconf_initialize_$token='yes'"
             ;;
         :terminate)
             token=`$echo -n ${tokens[1]} | $strconf_tokenize`
+            eval "otherno=\"\$strconf_terminate_lineno_$token\""
+            if test -n "$otherno" ; then
+                $echo "$progname: error: ${infile:-(stdin)} +$lineno : terminate \`${tokens[1]}' already defined at line $otherno" >&2
+                continue
+            fi
+            eval "strconf_terminate_lineno_$token=\"\$lineno\""
             eval "strconf_terminate_$token='yes'"
             ;;
         :node)
             token=`$echo -n ${tokens[1]} | $strconf_tokenize`
+            eval "otherno=\"\$strconf_node_lineno_$token\""
+            if test -n "$otherno" ; then
+                $echo "$progname: error: ${infile:-(stdin)} +$lineno : node \`${tokens[1]}' already defined at line $otherno" >&2
+                continue
+            fi
+            eval "strconf_node_lineno_$token=\"\$lineno\""
             eval "strconf_node_$token='${tokens[*]}'"
             eval "strconf_devname_$token='${tokens[1]}'"
             eval "strconf_devtype_$token='${tokens[2]}'"
@@ -581,14 +635,64 @@ ${tokens[19]}'"
             ;;
         :device)
             token=`$echo -n ${tokens[1]} | $strconf_tokenize`
+            eval "otherno=\"\$strconf_device_lineno_$token\""
+            if test -n "$otherno" ; then
+                $echo "$progname: error: ${infile:-(stdin)} +$lineno : device \`${tokens[1]}' already defined at line $otherno" >&2
+                continue
+            fi
+            eval "strconf_device_lineno_$token=\"\$lineno\""
             eval "strconf_device_$token='${tokens[*]}'"
+            ;;
+        :qlock)
+            case ":${tokens[1]}" in
+                (:driver|:module) ;;
+                (:*) $echo "$progname: syntax error ${infile:-(stdin)} +$lineno : unknown object type \`${tokens[1]}'" >&2
+                    continue ;;
+            esac
+            token=`echo -n ${tokens[2]} | $strconf_tokenize`
+            qlock=`echo -n ${tokens[3]} | $strconf_uppercase`
+            case ":$qlock" in
+                (:0|:NONE)   qlock=0 ;;
+                (:1|:QUEUE)  qlock=1 ;;
+                (:2|:QPAIR)  qlock=2 ;;
+                (:3|:GLOBAL) qlock=3 ;;
+                (:*)
+                    $echo "$progname: syntax error ${infile:-(stdin)} +$lineno : unknown qlock type \`${tokens[3]}'" >&2
+                    continue
+                    ;;
+            esac
+            case ":${tokens[1]}" in
+                :driver)
+                    eval "otherno=\"\$strconf_qlock_driver_lineno_$token\""
+                    if test -n "$otherno" ; then
+                        $echo "$progname: error: ${infile:-(stdin)} +$lineno : qlock for driver \`${tokens[2]}' already defined at line $otherno" >&2
+                        continue
+                    fi
+                    eval "strconf_qlock_driver_lineno_$token=\"\$lineno\""
+                    eval "strconf_qlock_driver_$token='${tokens[*]}'"
+                    eval "strconf_qlock_$token=\"$qlock\""
+                    ;;
+                :module)
+                    eval "otherno=\"\$strconf_qlock_module_lineno_$token\""
+                    if test -n "$otherno" ; then
+                        $echo "$progname: error: ${infile:-(stdin)} +$lineno : qlock for module \`${tokens[2]}' already defined at line $otherno" >&2
+                        continue
+                    fi
+                    eval "strconf_qlock_module_lineno_$token=\"\$lineno\""
+                    eval "strconf_qlock_module_$token='${tokens[*]}'"
+                    eval "strconf_qlock_$token=\"$qlock\""
+                    ;;
+                :*)
+                    $echo "$progname: syntax error ${infile:-(stdin)} +$lineno : unknown object type \`${tokens[1]}'" >&2
+                    continue
+            esac
             ;;
         :#*)
             continue
             ;;
         :*)
             $echo "$progname: syntax error: ${infile:-(stdin)} +$lineno : unknown command name \`${tokens[0]}'" >&2
-            continue;
+            continue
             ;;
     esac
 done
@@ -966,6 +1070,7 @@ do
         eval "realname=\"\$strconf_realname_$name\""
         eval "init=\"\$strconf_initialize_$name\""
         eval "term=\"\$strconf_terminate_$name\""
+        eval "qlock=\"\$strconf_qlock_$name\""
         if test x"$init" = "xyes"; then
             init="${prefix}init"
         else
@@ -976,7 +1081,7 @@ do
         else
             term='NULL'
         fi
-        $echo -n "$mysep	{\"${realname}\", &${prefix}info, ${prefix}_0_majors, ${nmajors}, ${nminors}, ${init}, ${term}}" >>$modconf
+        $echo -n "$mysep	{\"${realname}\", &${prefix}info, ${prefix}_0_majors, ${nmajors}, ${nminors}, ${init}, ${term}, ${qlock}}" >>$modconf
         mysep=",
 "
     fi
@@ -1007,11 +1112,12 @@ do
     eval "objname=\"\$strconf_objname_$name\""
     eval "loadable=\"\$strconf_loadable_$objname\""
     eval "realname=\"\$strconf_realname_$name\""
+    eval "qlock=\"\$strconf_qlock_$name\""
     if test x"$loadable" != xyes; then
         eval "prefix=\"\$strconf_prefix_$name\""
-        $echo -n "$mysep	{\"${realname}\", &${prefix}info, \"\"}" >>$modconf
+        $echo -n "$mysep	{\"${realname}\", &${prefix}info, \"\", ${qlock}}" >>$modconf
     else
-        $echo -n "$mysep	{\"${realname}\", NULL, \"${objname}\"}" >>$modconf
+        $echo -n "$mysep	{\"${realname}\", NULL, \"${objname}\", ${qlock}}" >>$modconf
     fi
     mysep=",
 "
