Import from CVS Mon Feb 14 23:46:48 2005 -0600
- Got these where I want them.
- Avoid namespace polution.
- System controls file.
file streams.conf was initially added on branch OpenSS7-0_9_2.

diff --git a/streams/src/util/init/strerr b/streams/src/util/init/strerr
--- a/streams/src/util/init/strerr
+++ b/streams/src/util/init/strerr
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# @(#) $RCSfile: strerr,v $ $Name:  $($Revision: 0.9.2.4 $) $Date: 2005/02/14 06:47:18 $
+# @(#) $RCSfile: strerr,v $ $Name:  $($Revision: 0.9.2.5 $) $Date: 2005/02/14 23:39:04 $
 # Copyright (c) 2001-2005  OpenSS7 Corporation <http://www.openss7.com>
 # Copyright (c) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>
 # All Rights Reserved.
@@ -12,10 +12,10 @@
 #
 # strerr:	start and stop strerr facility
 # chkconfig:	- 55 55
-# processname:	strerr
-# pidfile:	/var/run/strerr.pid
 # lockfile:	/var/lock/subsys/strerr
 # config:	/etc/sysconfig/strerr
+# processname:	strerr
+# pidfile:	/var/run/strerr.pid
 # probe:	true
 # hide:		false
 # license:	GPL
@@ -41,128 +41,136 @@
 #	and this init script is not activated in any run level by default.
 ### END INIT INFO
 
-# Source init script functions library.
+# Source init script functions library
 . /etc/init.d/functions
 
-[ -f /sbin/strerr ] || [ -f /usr/sbin/strerr ] || exit 0
+name='strerr'
+lockfile="/var/lock/subsys/$name"
+config="/etc/sysconfig/$name"
+processname="$name"
+pidfile="/var/run/$processname.pid"
+
+[ -x /sbin/$processname ] || [ -x /usr/sbin/$processname ] || exit 0
 
 # Specify defaults
 
-STRERROPTIONS=""
-MAILUID=""
-DIRECTORY="/var/log/streams"
-BASENAME="error"
-OUTFILE=""
-ERRFILE=""
-LOGDEVICE="/dev/streams/log"
+STRERROPTIONS=
+STRERR_MAILUID=
+STRERR_DIRECTORY="/var/log/streams"
+STRERR_BASENAME="error"
+STRERR_OUTFILE=
+STRERR_ERRFILE=
+STRERR_LOGDEVICE="/dev/streams/log"
+STRERR_OPTIONS=
 
 # Source redhat and/or debian config file
-[ -f /etc/strerr.conf ] && . /etc/strerr.conf
-[ -f /etc/default/strerr ] && . /etc/default/strerr
-[ -f /etc/sysconfig/strerr.conf ] && . /etc/sysconfig/strerr
-
-STRERR_OPTIONS="-n\
-${STRERROPTIONS:+ $STRERROPTIONS}\
-${MAILUID:+ -a $MAILID}\
-${DIRECTORY:+ -d $DIRECTORY}\
-${BASENAME:+ -b $BASENAME}\
-${OUTFILE:+ -o $OUTFILE}\
-${ERRFILE:+ -e $ERRFILE}\
-${LOGDEVICE:+ -l $LOGDEVICE}"
+for file in $config ; do
+    [ -f $file ] && . $file
+done
 
 RETVAL=0
 
 umask 077
 
 start() {
-    echo "Starting STREAMS error logger: "
     daemon strerr $STRERR_OPTIONS
     RETVAL=$?
-    echo ""
-    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/strerr
+    [ $RETVAL -eq 0 ] && touch $lockfile
+    RETVAL=$?
     return $RETVAL
 }
 
 stop() {
-    echo "Shutting down STREAMS error logger: "
-    killproc strerr
+    killproc $processname
     RETVAL=$?
-    echo ""
-    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/strerr
+    [ $RETVAL -eq 0 ] && rm -f -- $lockfile
+    RETVAL=$?
     return $RETVAL
-}
-
-rhstatus() {
-    status strerr
-}
-
-reload() {
-    echo "Reloading the STREAMS error logger: "
-    killproc strerr -HUP
 }
 
 restart() {
     stop
     start
+    return $?
 }
 
-probe() {
-#
-#   subsystem unlocked, need to start
-#
-    [ ! -f /var/log/subsys/strerr ] && { echo 'start' ; return 0 }
-#
-#   strerr dead but subsystem locked, need to restart
-#
-    /sbin/pidof strerr >/dev/null 2>&1 || { echo 'restart' ; return 0 }
-#
-#   configuration files updated, need to reload
-#
-    [ -f /etc/sysconfig/strerr -a /etc/sysconfig/strerr -nt /var/lock/subsys/strerr ] \
-    && { echo 'reload' ; return 0 }
-    [ -f /etc/default/strerr   -a /etc/default/strerr   -nt /var/lock/subsys/strerr ] \
-    && { echo 'reload' ; return 0 }
-    [ -f /etc/strerr.conf      -a /etc/strerr.conf      -nt /var/lock/subsys/strerr ] \
-    && { echo 'reload' ; return 0 }
-#
-#   do not need to do anything
-#
+reload() {
+    echo "Reloading the STREAMS error logger: "
+    killproc $processname -HUP
     return $?
 }
 
 case "$1" in
-    (start)
-	start
-	;;
-    (stop)
-	stop
+    (start|stop|reload|restart)
+	# Build up the options string
+	STRERR_OPTIONS="-n"
+	[ -n "$STRERROPTIONS" ] && \
+	    STRERR_OPTIONS="${STRERR_OPTIONS:+ }${STRERROPTIONS}"
+	[ -n "$STRERR_MAILUID" ] && \
+	    STRERR_OPTIONS="${STRERR_OPTIONS:+ }-a ${STRERR_MAILUID}"
+	[ -n "$STRERR_DIRECTORY" ] && \
+	    STRERR_OPTIONS="${STRERR_OPTIONS:+ }-d ${STRERR_DIRECTORY}"
+	[ -n "$STRERR_BASENAME" ] && \
+	    STRERR_OPTIONS="${STRERR_OPTIONS:+ }-b ${STRERR_BASENAME}"
+	[ -n "$STRERR_OUTFILE" ] && \
+	    STRERR_OPTIONS="${STRERR_OPTIONS:+ }-o ${STRERR_OUTFILE}"
+	[ -n "$STRERR_ERRFILE" ] && \
+	    STRERR_OPTIONS="${STRERR_OPTIONS:+ }-e ${STRERR_ERRFILE}"
+	[ -n "$STRERR_LOGDEVICE" ] && \
+	    STRERR_OPTIONS="${STRERR_OPTIONS:+ }-l ${STRERR_LOGDEVICE}"
+	$1 || RETVAL=$?
 	;;
     (status)
-	rhstatus
-	;;
-    (restart)
-	restart
-	;;
-    (reload)
-	reload
+	$1 $name || RETVAL=$?
 	;;
     (condrestart)
-	[ -f /var/lock/subsys/strerr ] && restart || :
+	[ -f $lockfile ] && restart || RETVAL=$?
 	;;
     (probe)
-	probe
+	if /sbin/pidof $processname >/dev/null 2>&1 ; then
+	    # running
+	    if [ "`/sbin/pidof $processname`" -eq "`cat $pidfile`" ] ; then
+		# running with the right pid
+		if [ ! -f $lockfile ] ; then
+		    # running but subsystem unlocked, need to reload
+		    echo 'reload'
+		else
+		    # subsystem locked
+		    for file in $config ; do
+			if [ -f $file -a $file -nt $lockfile ] ; then
+			    # configuration file updated, need to reload
+			    echo 'reload'
+			    break
+			fi
+		    done
+		fi
+	    else
+		# running, but with the wrong pid, need to restart
+		echo 'restart'
+	    fi
+	else
+	    # not running
+	    if [ ! -f $lockfile ] ; then
+		# subsystem unlocked, need to start
+		echo 'start'
+	    else
+		# dead but subsystem locked, need to restart
+		echo 'restart'
+	    fi
+	fi
+	# do not need to do anything
+	RETVAL=$?
 	;;
     (*)
-	echo "Usage: $0 (start|stop|status|restart|condrestart|probe)\n"
+	echo "Usage: $0 (start|stop|status|restart|condrestart|probe)"
 	;;
 esac
 
-exit $?
+[ "${0##*/}" = "$name" ] && exit $RETVAL
 
-
 # =============================================================================
 # 
-# @(#) $RCSfile: strerr,v $ $Name:  $($Revision: 0.9.2.4 $) $Date: 2005/02/14 06:47:18 $
+# @(#) $RCSfile: strerr,v $ $Name:  $($Revision: 0.9.2.5 $) $Date: 2005/02/14 23:39:04 $
 #
 # -----------------------------------------------------------------------------
 #
@@ -208,7 +216,8 @@ exit $?
 #
 # -----------------------------------------------------------------------------
 #
-# Last Modified $Date: 2005/02/14 06:47:18 $ by $Author: brian $
+# Last Modified $Date: 2005/02/14 23:39:04 $ by $Author: brian $
 #
 # =============================================================================
-# vim: sw=4 tw=80
+
+# vim: ft=sh sw=4 tw=80
