- working up maintainer scripts

diff --git a/debian/openss7-kernel.preinst.in b/debian/openss7-kernel.preinst.in
--- a/debian/openss7-kernel.preinst.in
+++ b/debian/openss7-kernel.preinst.in
@@ -58,73 +58,73 @@ remove_depmods () {
     [ $# -gt 0 ] || return 0
     echo "$*"
     for t in $@ ; do
-        prereq=prereq_`echo $t | sed -r -e 's|^.*/||;s|\.(k)?o(\.gz)?(:)?$||;s|[^a-zA-Z0-9_]|_|g'`
-        eval "remove_depmods \$$prereq"
+	prereq=prereq_`echo $t | sed -r -e 's|^.*/||;s|\.(k)?o(\.gz)?(:)?$||;s|[^a-zA-Z0-9_]|_|g'`
+	eval "remove_depmods \$$prereq"
     done
 }
-remove_depends() {
+remove_depends () {
     local modrex depend depends
     modrex=`echo $1 | sed -e 's,[-_],[-_],g'`
     depends=`grep "^$modrex[[:space:]]" /proc/modules 2>/dev/null | cut -f4 '-d ' | sed -e 's|^-$||;s|,$||;s|,| |g'`
     for depend in $depends ; do
-        remove_depends $depend || return $?
+	remove_depends $depend || return $?
     done
     if grep "^$modrex[[:space:]]" /proc/modules >/dev/null 2>&1 ; then
-        rmmod $1 >/dev/null 2>&1 || return $?
+	rmmod $1 >/dev/null 2>&1 || return $?
     fi
     return 0
 }
 
-install_kernel_preinst_modules() { :
+kernel_preinst_modules () { :
     local list m b modl_mods line dep
     # This is a fresh install of this version of kernel module.  Make sure that
     # there are no tarball installed kernel modules hanging around for this
     # kernel version.
     list="${modules}" ; modl_mods=
     if [ -d ${kmoduledir} ] ; then
-        for m in `find ${kmoduledir} \( -name 'streams*.o' -o -name 'streams*.ko' -o -name 'streams*.o.gz' -o -name 'streams*.ko.gz' \) 2>/dev/null` ; do
-                b=`echo $m | sed -r -e 's|^.*/||;s|\.(k)?o(\.gz)?||'`
-                case " $list " in (*" $b "*) ;; (*) continue ;; esac
-                echo "$m"
+	for m in `find ${kmoduledir} \( -name 'streams*.o' -o -name 'streams*.ko' -o -name 'streams*.o.gz' -o -name 'streams*.ko.gz' \) 2>/dev/null` ; do
+		b=`echo $m | sed -r -e 's|^.*/||;s|\.(k)?o(\.gz)?||'`
+		case " $list " in (*" $b "*) ;; (*) continue ;; esac
+		echo "$m"
 		modl_mods="$modl_mods${modl_mods:+' '}$m"
-        done
-        if [ -n "$modl_mods" -a -f ${kmoduledir}/modules.dep ] ; then
-            # First we can build a dependency tree from every dependency
-            # expression that can be found in the modules.dep file.
+	done
+	if [ -n "$modl_mods" -a -f ${kmoduledir}/modules.dep ] ; then
+	    # First we can build a dependency tree from every dependency
+	    # expression that can be found in the modules.dep file.
 	    xtrace=`set -o | sed -n 's,xtrace[[:space:]]*on,set +o xtrace,p;t;s,xtrace[[:space:]]*off,set -o xtrace,p;t'`
 	    set +x
-            dep= ; while read line ; do
-                case $line in
-                    (*\\)   line="`echo $line | sed -e 's|\\$||'`"
+	    dep= ; while read line ; do
+		case $line in
+		    (*\\)   line="`echo $line | sed -e 's|\\$||'`"
 			    dep="$dep${dep:+' '}$line"; continue ;;
-                    (*)     dep="$dep${dep:+' '}$line" ;;
-                esac
-                [ -n "$dep" ] || continue;
-                set dummy $dep
+		    (*)     dep="$dep${dep:+' '}$line" ;;
+		esac
+		[ -n "$dep" ] || continue;
+		set dummy $dep
 		if [ $# -gt 3 ] ; then
-                    t=`echo $2 | sed -e 's|:$||'`
-                    target=target_`echo $t | sed -r -e 's|^.*/||;s|\.(k)?o(\.gz)?(:)?$||;s|[^a-zA-Z0-9_]|_|g'`
-                    shift 2
-                    for p in $@ ; do
-                        prereq=prereq_`echo $p | sed -r -e 's|^.*/||;s|\.(k)?o(\.gz)?(:)?$||;s|[^a-zA-Z0-9_]|_|g'`
-                        eval "$prereq=\"\$$prereq\${$prereq:+' '}$t\""
-                        eval "$target=\"\$$target\${$target:+' '}$p\""
-                    done
-                fi
-                dep=
-            done < ${kmoduledir}/modules.dep
-            eval "$xtrace"
-        fi
+		    t=`echo $2 | sed -e 's|:$||'`
+		    target=target_`echo $t | sed -r -e 's|^.*/||;s|\.(k)?o(\.gz)?(:)?$||;s|[^a-zA-Z0-9_]|_|g'`
+		    shift 2
+		    for p in $@ ; do
+			prereq=prereq_`echo $p | sed -r -e 's|^.*/||;s|\.(k)?o(\.gz)?(:)?$||;s|[^a-zA-Z0-9_]|_|g'`
+			eval "$prereq=\"\$$prereq\${$prereq:+' '}$t\""
+			eval "$target=\"\$$target\${$target:+' '}$p\""
+		    done
+		fi
+		dep=
+	    done < ${kmoduledir}/modules.dep
+	    eval "$xtrace"
+	fi
     fi
     # remove conflicting and dependent modules
     if [ -n "$modl_mods" ] ; then
-        rm -f -- $modl_mods
-        for m in $list ; do
-            prereq=prereq_`echo $m | sed -r -e 's|^.*/||;s|\.(k)?o(\.gz)?(:)?$||;s|[^a-zA-Z0-9_]|_|g'`
-            eval "modl_deps=\"\`remove_depmods \$$prereq\`\""
-            [ -n "$modl_deps" ] || continue
-            rm -f -- $modl_deps
-        done
+	rm -f -- $modl_mods
+	for m in $list ; do
+	    prereq=prereq_`echo $m | sed -r -e 's|^.*/||;s|\.(k)?o(\.gz)?(:)?$||;s|[^a-zA-Z0-9_]|_|g'`
+	    eval "modl_deps=\"\`remove_depmods \$$prereq\`\""
+	    [ -n "$modl_deps" ] || continue
+	    rm -f -- $modl_deps
+	done
     fi
     :
 }
@@ -132,37 +132,42 @@ install_kernel_preinst_modules() { :
 #
 # FIXME: there is a way in debian to indicate that a reboot is required (use it)
 #
-install_kernel_preinst_running() {
+kernel_preinst_running () {
     local fields ind val signal reboot
     if [ ":%{kernel_version}" = ":`uname -r`" ] ; then
-        # If we are upgrading and the upgrade is for the running kernel, or we
-        # are installing new on the running kernel, we have to worry about
-        # previous loaded modules for the old version or a non-rpm version.
-        if lsof | grep '\<STR\>' >/dev/null 2>&1 ; then
-            if [ -x /usr/sbin/fdetach ] ; then
-                /usr/sbin/fdetach -a 2>/dev/null || :
-            fi
-            for signal in TERM KILL ; do
-                if lsof | grep '\<STR\>' >/dev/null 2>&1 ; then
-                    lsof | grep '\<STR\>' | \
-                    while read fields ; do
-                        set dummy $fields
-                        if [ ":$6" != ':CHR' ] ; then continue; fi
-                        ind=`expr $# - 1`
-                        eval "val=\"\${$ind}\""
-                        if [ ":$val" != ':STR' ] ; then continue; fi
-                        kill -$signal $3 >/dev/null 2>&1 || :
-                    done
-                    sleep 5
-                fi
-            done
-        fi
-        lsof | grep '\<STR\>' >/dev/null 2>&1 && reboot='yes'
-        remove_depends streams || reboot='yes'
-        remove_depends specfs  || reboot='yes'
-        [ ":$reboot" != ':yes' ] || echo "Reboot required." >&2
+	# If we are upgrading and the upgrade is for the running kernel, or we
+	# are installing new on the running kernel, we have to worry about
+	# previous loaded modules for the old version or a non-rpm version.
+	if lsof | grep '\<STR\>' >/dev/null 2>&1 ; then
+	    if [ -x /usr/sbin/fdetach ] ; then
+		/usr/sbin/fdetach -a 2>/dev/null || :
+	    fi
+	    for signal in TERM KILL ; do
+		if lsof | grep '\<STR\>' >/dev/null 2>&1 ; then
+		    lsof | grep '\<STR\>' | \
+		    while read fields ; do
+			set dummy $fields
+			if [ ":$6" != ':CHR' ] ; then continue; fi
+			ind=`expr $# - 1`
+			eval "val=\"\${$ind}\""
+			if [ ":$val" != ':STR' ] ; then continue; fi
+			kill -$signal $3 >/dev/null 2>&1 || :
+		    done
+		    sleep 5
+		fi
+	    done
+	fi
+	lsof | grep '\<STR\>' >/dev/null 2>&1 && reboot='yes'
+	remove_depends streams || reboot='yes'
+	remove_depends specfs  || reboot='yes'
+	[ ":$reboot" != ':yes' ] || echo "Reboot required." >&2
     fi
     :
+}
+
+kernel_preinst () { :
+    kernel_preinst_modules
+    kernel_preinst_running
 }
 
 
@@ -170,14 +175,28 @@ install_kernel_preinst_running() {
 # Primary functions:
 # -----------------------------------------------------------------------------
 
-install_kernel_preinst() { :
-    install_kernel_preinst_modules
-    install_kernel_preinst_running
+install_kernel_preinst () { :
+    kernel_preinst
     :
 }
 
-upgrade_kernel_preinst() { :
-    install_kernel_preinst_running
+#
+# For reinstall and upgrade, because the package was installed at some
+# previous time, there is no need to go flushing out some old non-deb
+# install.
+#
+reinstall_kernel_preinst () { :
+    kernel_preinst_running
+    :
+}
+
+upgrade_kernel_preinst () { :
+    kernel_preinst_running
+    :
+}
+
+abort_upgrade_kernel_preinst () { :
+    kernel_preinst_running
     :
 }
 
