- more workup of maintainer scripts

diff --git a/debian/openss7-doc.postinst.in b/debian/openss7-doc.postinst.in
--- a/debian/openss7-doc.postinst.in
+++ b/debian/openss7-doc.postinst.in
@@ -53,17 +53,94 @@
 # =============================================================================
 subpkg=doc
 @openss7_postinst@
+datarootdir=@datarootdir@
 # -----------------------------------------------------------------------------
 # Auxiliary functions:
 # -----------------------------------------------------------------------------
+#
+# postinst_manpages() - Add our manual pages to the aprospros database.  One
+#   problem with doing this is that even the oldest of debian policies and
+#   debhelper implementations will implement the debhelper code to do this.
+#   Therefore, this function is shortcircuited for now.  (We install >3000
+#   manual pages and it takes forever anyway.)  Failing to do this altogether is
+#   not critical because most machines run an evening cron job to update these.
+#
+postinst_manpages () { :; return
+    if which makewhatis >/dev/null 2>&1 ; then
+	LANGUAGE= LANG= makewhatis -u @mandir@ || true
+    fi
+    if which mandb >/dev/null 2>&1 ; then
+	LANGUAGE= LANG= mandb -p @mandir@ || :true
+    fi
+}
+#
+# postinst_manrefs() - Some systems compress our reference database but do not
+#   provide nor invoke the zrefer command necessary to use compressed reference
+#   databases.  Therefore, we always provide a decompressed copy of the
+#   reference database.
+#
+postinst_manrefs () {
+    local m
+    for m in ${manrefs}; do
+	[ ! -f @mandir@/$m.gz  ] || gzip  -dc @mandir@/$m.gz  > @mandir@/$m
+	[ ! -f @mandir@/$m.bz2 ] || bzip2 -dc @mandir@/$m.bz2 > @mandir@/$m
+    done
+}
+#
+# postinst_manrefs() - Some systems compress our man macros but do not provide
+#   nor invoke the zsoelim command necessary to use compressed man macros.
+#   Therefore, we always provide a decompressed copy of the man macros.
+#
+postinst_manmacros () {
+    local m
+    for m in ${manmacros}; do
+	[ ! -f @mandir@/$m.gz  ] || gzip  -dc @mandir@/$m.gz  > @mandir@/$m
+	[ ! -f @mandir@/$m.bz2 ] || bzip2 -dc @mandir@/$m.bz2 > @mandir@/$m
+    done
+}
+#
+# postinst_infofiles() - Add our info files to the info directory.  One problem
+#   with doing this is that even the oldest of debian policies and debhelper
+#   implementations will implement the debhelper code to do this.  Therefore,
+#   this function is shorcricuited for now.  Current debian policies will use
+#   trigger directories to perform this action.
+#
+postinst_infofiles () { :; return
+    if [ -x /sbin/install-info ]; then
+#	Older policies do not compress info files.
+	for n in $manuals; do
+            if [ -f @infodir@/$n.info ] ; then
+                /sbin/install-info --info-dir=@infodir@ @infodir@/$n.info || true
+            elif [ -f @infodir@/$n.info.gz ] ; then
+                /sbin/install-info --info-dir=@infodir@ @infodir@/$n.info.gz || true
+            elif [ -f @infodir@/$n.info.bz2 ] ; then
+                /sbin/install-info --info-dir=@infodir@ @infodir@/$n.info.bz2 || true
+            fi
+        done
+    fi
+}
+#
+# postinst_doc() - Perform necessary activies for post installation of
+#   documentation files.  This is primarly handing man macros, reference
+#   database, info directories and aprospros databases.  Some of these
+#   operations are performed by debhelper code or directory trigger processing.
+#
+postinst_doc () { :
+    postinst_manpages
+    postinst_manrefs
+    postinst_manmacros
+    postinst_infofiles
+}
 # -----------------------------------------------------------------------------
 # Primary functions:
 # -----------------------------------------------------------------------------
 # xxx-postinst configure
 configure_postinst () { :
+    postinst_doc
 }
 # xxx-postinst configure most-recently-configured-version
 reconfigure_postinst () { :
+    postinst_doc
 }
 # xxx-postinst triggered triggered-packages
 triggered_postinst () { :
@@ -72,14 +149,17 @@ triggered_postinst () { :
 # new-prerm failed-upgrade new-version ...FAILED
 # old-posinst abort-upgrade new-version
 abort_upgrade_postinst () { :
+    postinst_doc
 }
 # con-prerm remove 'in-favour' package new-version ...FAILED
 # con-postinst abort-remove 'in-favour' package new-version
 abort_remove_postinst () { :
+    postinst_doc
 }
 # dec-prerm deconfigure 'in-favour' package-being-installed version ['removing' conflicting-package version] ...FAILED
 # dec-postinst abort-deconfigure 'in-favour' package-being-installed-but-failed version ['removing' conflicting-package version]
 abort_deconfigure_postinst () { :
+    postinst_doc
 }
 @mscript_postinst@
 @mscript_debhelper@
diff --git a/debian/openss7-doc.postrm.in b/debian/openss7-doc.postrm.in
--- a/debian/openss7-doc.postrm.in
+++ b/debian/openss7-doc.postrm.in
@@ -53,11 +53,40 @@
 # =============================================================================
 subpkg=doc
 @openss7_postrm@
+datarootdir=@datarootdir@
+# -----------------------------------------------------------------------------
+# Auxiliary functions:
+# -----------------------------------------------------------------------------
+#
+# postrm_manpages() - Update the removed and replaced manual pages in the
+#   aprospros database.  One problem with doing this is that even the oldest of
+#   debian policies and debhelper implementations will implement the debhelper
+#   code to do this.  Therefore, this function is shortcircuited for now.  (We
+#   install >3000 manual pages and it takes forever anyway.)  Failing to do this
+#   altogether is not cricical because most machines run an evening cron job to
+#   update these.
+#
+postrm_manpages () { :; return
+    if which makewhatis >/dev/null 2>&1 ; then
+	LANGUAGE= LANG= makewhatis -u ${mandir} || :
+    fi
+    if which mandb >/dev/null 2>&1 ; then
+	LANGUAGE= LANG= mandb -p ${mandir} || :
+    fi
+}
+#
+# postrm_doc() - On final removal of the package, update aprospros database with
+#   removed manual pages.
+#
+postrm_doc () { :
+    postrm_manpages
+}
 # -----------------------------------------------------------------------------
 # Primary functions:
 # -----------------------------------------------------------------------------
 # remove-postrm remove
 remove_postrm () { :
+    postrm_doc
 }
 # remove-postrm purge
 purge_postrm () { :
diff --git a/debian/openss7-kernel.preinst.in b/debian/openss7-kernel.preinst.in
--- a/debian/openss7-kernel.preinst.in
+++ b/debian/openss7-kernel.preinst.in
@@ -53,6 +53,103 @@
 # =============================================================================
 subpkg=kernel
 @openss7_preinst@
+datarootdir=@datarootdir@
+# -----------------------------------------------------------------------------
+# Auxiliary functions:
+# -----------------------------------------------------------------------------
+preinst_kernel_modules () { :
+#
+#   This is a fresh install of this version of kernel module.  Make sure that
+#   there are no tarball installed kernel modules hanging around for this
+#   kernel version.
+#
+    local list m b modl_mods line dep
+    list="${modules}" ; modl_mods=
+    if [ -d @kmoduledir@ ] ; then
+	for m in `find @kmoduledir@ \( -name 'streams*.o' -o -name 'streams*.ko' -o -name 'streams*.o.gz' -o -name 'streams*.ko.gz' \) 2>/dev/null` ; do
+		b=`echo $m | sed -r -e 's|^.*/||;s|\.(k)?o(\.gz)?||'`
+		case " $list " in (*" $b "*) ;; (*) continue ;; esac
+		echo "$m"
+		modl_mods="$modl_mods${modl_mods:+' '}$m"
+	done
+	if [ -n "$modl_mods" -a -f @kmoduledir@/modules.dep ] ; then
+#	    First we can build a dependency tree from every dependency
+#	    expression that can be found in the modules.dep file.
+	    xtrace=`set -o | sed -n 's,xtrace[[:space:]]*on,set +o xtrace,p;t;s,xtrace[[:space:]]*off,set -o xtrace,p;t'`
+	    set +x
+	    dep= ; while read line ; do
+		case $line in
+		    (*\\)   line="`echo $line | sed -e 's|\\$||'`"
+			    dep="$dep${dep:+' '}$line"; continue ;;
+		    (*)     dep="$dep${dep:+' '}$line" ;;
+		esac
+		[ -n "$dep" ] || continue;
+		set -- $dep
+		if [ $# -ge 2 ] ; then
+		    t=`echo $1 | sed -e 's|:$||'`
+		    target=target_`echo $t | sed -r -e 's|^.*/||;s|\.(k)?o(\.gz)?(:)?$||;s|[^a-zA-Z0-9_]|_|g'`
+		    shift
+		    for p in $@ ; do
+			prereq=prereq_`echo $p | sed -r -e 's|^.*/||;s|\.(k)?o(\.gz)?(:)?$||;s|[^a-zA-Z0-9_]|_|g'`
+			eval "$prereq=\"\$$prereq\${$prereq:+' '}$t\""
+			eval "$target=\"\$$target\${$target:+' '}$p\""
+		    done
+		fi
+		dep=
+	    done < @kmoduledir@/modules.dep
+	    eval "$xtrace"
+	fi
+    fi
+#   remove conflicting and dependent modules
+    if [ -n "$modl_mods" ] ; then
+	rm -f -- $modl_mods
+	for m in $list ; do
+	    prereq=prereq_`echo $m | sed -r -e 's|^.*/||;s|\.(k)?o(\.gz)?(:)?$||;s|[^a-zA-Z0-9_]|_|g'`
+	    eval "modl_deps=\"\`remove_depmods \$$prereq\`\""
+	    [ -n "$modl_deps" ] || continue
+	    rm -f -- $modl_deps
+	done
+    fi
+    :
+    return 0
+}
+#
+# FIXME: there is a way in debian to indicate that a reboot is required (use it)
+#
+preinst_kernel_running () {
+    local fields ind val signal reboot
+    if [ ":@kversion@" = ":`uname -r`" ] ; then
+#
+#	If we are upgrading and the upgrade is for the running kernel, or we are
+#	installing new on the running kernel, we have to worry about previous
+#	loaded modules for the old version or a non-deb version.
+#
+	if lsof | grep '\<STR\>' >/dev/null 2>&1 ; then
+	    if [ -x /usr/sbin/fdetach ] ; then
+		/usr/sbin/fdetach -a 2>/dev/null || :
+	    fi
+	    for signal in TERM KILL ; do
+		if lsof | grep '\<STR\>' >/dev/null 2>&1 ; then
+		    lsof | grep '\<STR\>' | \
+		    while read fields ; do
+			set -- $fields
+			if [ ":$5" != ':CHR' ] ; then continue; fi
+			ind=`expr $# - 1`
+			eval "val=\"\${$ind}\""
+			if [ ":$val" != ':STR' ] ; then continue; fi
+			kill -$signal $2 >/dev/null 2>&1 || :
+		    done
+		    sleep 5
+		fi
+	    done
+	fi
+	lsof | grep '\<STR\>' >/dev/null 2>&1 && reboot='yes'
+	remove_depends streams || reboot='yes'
+	remove_depends specfs  || reboot='yes'
+	[ ":$reboot" != ':yes' ] || echo "$script: warning: reboot required." >&2
+    fi
+    :
+}
 #   new-preinst install
 #	- files are unpacked
 #	- file list added
diff --git a/debian/openss7-repo.preinst.in b/debian/openss7-repo.preinst.in
--- a/debian/openss7-repo.preinst.in
+++ b/debian/openss7-repo.preinst.in
@@ -53,22 +53,90 @@
 # =============================================================================
 subpkg=repo
 @openss7_preinst@
+datarootdir=@datarootdir@
+# -----------------------------------------------------------------------------
+# Auxiliary functions:
+# -----------------------------------------------------------------------------
+#
+# preinst_repo() - When we go to install this subpackage fresh, we need to
+#   acquire a username and password from the user and get credentials for this
+#   machine.  When reinstalling (previous package was not purged), this function
+#   gets the existing credentials from the persistent configuration file.  Even
+#   when a package is purged, we like to keep a copy of the credentials lying
+#   around in a .dpkg-save file so that the machine credentials don't get lost.
+#
+#   Note that because the credentials are really machine credentials, we should
+#   really be saving them in /boot so that installations of other distros can
+#   also see the same machine credentials.
+#
+preinst_repo () { :
+    local d
+    d="@sysconfdir@/apt/sources.list.d"
+    [ -d $d ] || return 1
+    (
+	cd "$d"
+	un=; pw=; oldfile=; file="@PACKAGE@.list"
+	for s in '' '.dpkg-save' '.dpkg-new'; do
+	    oldfile="$file$s"
+	    if [ -r $oldfile ]; then
+                un=`sed -n -r 's,^.*deb[[:space:]][[:space:]]*http[s]?://([^@:]*)(:([^@]*))@.*$,\1,p;t end;b;: end q' $oldfile`
+                pw=`sed -n -r 's,^.*deb[[:space:]][[:space:]]*http[s]?://([^@:]*)(:([^@]*))@.*$,\3,p;t end;b;: end q' $oldfile`
+                [ -n "$un" -a -n "$pw" ] || continue
+                break
+	    fi
+	done
+	[ ":$oldfile" != ":$file" ] || mv -f -- $file $file.dpkg-save
+        ext="?hn=`hostname -f`&ip=`hostname -i | sed 'y/ /,/'`${un:+'&un='}${un}${pw:+'&pw='}${pw}"
+        ext="$ext"`echo /@reposubdir@ | sed 's,//,/,g;s,/,\&distro=,;s,/,\&relver=,;s,/,\&osarch=,'`
+	key=; [ -z "$un" ] || key="$un${pw:+':'}${pw}@"
+        url="@reposerv@://${key}@repobase@/@reporoot@/debs/$file$ext"
+        rm -f -- $file
+        if ! echo "$url" | wget -i - -O $file 2>/dev/null ; then
+            if echo "$url" | wget -i - -O /dev/null 2>&1 | grep '401 Authorization Required' >/dev/null 2>&1 ; then
+                echo 'Authorization required for repository access.' >/dev/tty
+                u='anonymous'; p=
+                read -e  -p 'Username: ' u </dev/tty >/dev/tty; u=${u:-'anonymous'}
+                if [ "$u" != 'anonymous' ] ; then
+                read -es -p 'Password: ' p </dev/tty >/dev/tty
+                echo '' >/dev/tty
+                fi
+		key=; [ -z "$u" ] || key="${u}:${p}@"
+                url="@reposerv@://${key}@repobase@/@reporoot@/debs/$file$ext"
+                rm -f -- $file
+                if ! echo "$url" | wget -i - -O $file 2>/dev/null ; then
+                    [ ":$oldfile" != ":$file" ] || mv -f -- $file.dpkg-save $file
+                    echo 'Authorization failed.' >/dev/tty
+		    return 1
+                fi
+            fi
+        fi
+        if [ ! -e $file ] ; then
+            [ ":$oldfile" != ":$file" ] || mv -f -- $file.dpkg-save $file
+	    return 1
+        fi
+    ) || return 1
+    return 0
+}
 # -----------------------------------------------------------------------------
 # Primary functions:
 # -----------------------------------------------------------------------------
 # new-preinst install
 install_preinst () { :
+    preinst_repo
 }
 # new-preinst install old-version
 reinstall_preinst () { :
+    preinst_repo
 }
 # new-preinst upgrade old-version
 upgrade_preinst () { :
+    preinst_repo
 }
 # old-postrm upgrade new-version ...FAILED
 # new-postrm failed-upgrade old-version ...FAILED
 # old-preinst abort-upgrade new-version
 abort_upgrade_preinst () { :
+    preinst_repo
 }
 @mscript_preinst@
 @mscript_debhelper@
