- more arch script support

diff --git a/arch/openss7-repo.install.in b/arch/openss7-repo.install.in
--- a/arch/openss7-repo.install.in
+++ b/arch/openss7-repo.install.in
@@ -92,17 +92,20 @@ preinst_repo () { :
     done
     done
     [ -n "$un" -a -n "$pw" ] || { un=; pw=; }
+    d=$sslcertdir; n=OPENSS7-CA-CERT.pem
+    o=; f=$d/$n; [ -d $d ] || mkdir -p -- $d
+    [ -e $f ] || { wget --no-check-certificate -O $f $reposerv://$repobase/cacert.pem 2>/dev/null; (cd $d; ln -sf $n `openssl x509 -hash -noout -in $f`.0); }
     d=$localstatedir/lib/$name; n=credentials
     o=; f=$d/$n; [ -d $d ] || mkdir -p -- $d
     [ ! -e $f ] || { o=$f; mv -f -- $f $f.$$; }
-    hn=`hostname -f`; ip=`hostname -I | sed 'y/ /,/'`; n=patches
-    id=`e=$(for s in /sys/class/net/eth*; do if [ ! -L $s ]; then continue ; fi ; echo $(readlink $s)" "$s ; done | sort | head -1 | cut -f2 "-d ") ; [ -r $e/address ] && cat $e/address | sed "s,:,,g"`
+    hn=`hostname -f`; ip=`hostname -I|sed 'y/ /,/'`;n=patches
+    id=`e=$(for s in /sys/class/net/e*;do if [ ! -L $s ];then continue;fi;echo $(readlink $s)" "$s;done|sort|head -1|cut -f2 "-d ");[ -r $e/address ] && cat $e/address|sed "s,:,,g"`
     ext="?hn=$hn&ip=$ip&id=$id${un:+&un=}${un}${pw:+&pw=}${pw}"
-    ext="$ext`echo /$reposubdir | sed 's,//,/,g;s,/,\&distro=,;s,/,\&relver=,;s,/,\&osarch=,'`"
+    ext="$ext`echo /$reposubdir|sed 's,//,/,g;s,/,\&distro=,;s,/,\&relver=,;s,/,\&osarch=,'`"
     key="${un:+${un}${pw:+:}${pw}@}"
     url="$reposerv://$key$repobase/$reporoot/`basename $f`$ext"
-    if ! echo "$url" | wget -i - -O $f 2>/dev/null ; then
-        if echo "$url" | wget -i - -O /dev/null 2>&1 | grep '401 Authorization Required' >/dev/null 2>&1 ; then
+    if ! echo "$url"|wget -i - -O $f 2>/dev/null ; then
+        if echo "$url"|wget -i - -O /dev/null 2>&1|grep '401 Authorization Required' >/dev/null 2>&1 ; then
             u='anonymous'; p=
             m='Authorization required for repository access.'
             if [ -n "$DISPLAY" -a -x "`which zenity 2>/dev/null`" ]; then
@@ -143,7 +146,7 @@ preinst_repo () { :
             key="${u:+${u}${p:+:}${p}@}"
             url="$reposerv://$key$repobase/$reporoot/`basename $f`$ext"
             rm -f -- $f
-            if ! echo "$url" | wget -i - -O $f 2>/dev/null; then
+            if ! echo "$url"|wget -i - -O $f 2>/dev/null; then
                 rm -f -- $f
                 m='Authorization failed.'
                 if [ -n "$DISPLAY" -a -x "`which zenity 2>/dev/null`" ]; then
@@ -169,16 +172,16 @@ preinst_repo () { :
     un=`awk 'BEGIN{FS="="}{if($1~/^username$/){print$2;exit}}' $f`
     pw=`awk 'BEGIN{FS="="}{if($1~/^password$/){print$2;exit}}' $f`
     [ -n "$un" -a -n "$pw" ] || return 1
-    unp="`echo $un | cut -c1-24`"
-    pwp="`echo $pw | cut -c1-24`"
-    echo "$unp$pwp" >$d/$n
+    unp="`echo $un|cut -c1-24`"
+    pwp="`echo $pw|cut -c1-24`"
+    echo "$pwp$unp" >$d/$n
     key="${un:+${un}${pw:+:$pw}@}"
-    ext="`echo /$reposubdir | sed 's,//,/,g;s,/,?distro=,;s,/,\&relver=,;s,/,\&osarch=,'`"
+    ext="`echo /$reposubdir|sed 's,//,/,g;s,/,?distro=,;s,/,\&relver=,;s,/,\&osarch=,'`"
     d=$pacmanrepodir; n=${PACKAGE}list
     o=; f=$d/$n; [ -d $d ] || mkdir -p -- $d
     [ ! -e $f ] || { o=$f; mv -f -- $f $f.$$; }
     url="$reposerv://$key$repobase/$reporoot/$n$ext"
-    if ! echo "$url" | wget -i - -O $f 2>/dev/null || [ ! -e $f ]; then
+    if ! echo "$url"|wget -i - -O $f 2>/dev/null || [ ! -e $f ]; then
         [ "$o" != "$f" -o ! -e $o.$$ ] || mv -f -- $o.$$ $o
         return 1
     fi
@@ -187,7 +190,7 @@ preinst_repo () { :
     o=; f=$d/$n; [ -d $d ] || mkdir -p -- $d
     [ ! -e $f ] || { o=$f; mv -f -- $f $f.$$; }
     url="$reposerv://$key$repobase/$reporoot/$n$ext"
-    if ! echo "$url" | wget -i - -O $f 2>/dev/null || [ ! -e $f ]; then
+    if ! echo "$url"|wget -i - -O $f 2>/dev/null || [ ! -e $f ]; then
         [ "$o" != "$f" -o ! -e $o.$$ ] || mv -f -- $o.$$ $o
         return 1
     fi
