- syncing updates

diff --git a/strvoip/scripts/missing2 b/strvoip/scripts/missing2
--- a/strvoip/scripts/missing2
+++ b/strvoip/scripts/missing2
@@ -1,7 +1,7 @@
 #! /bin/sh
 # =============================================================================
 # 
-# @(#) $RCSfile: missing2,v $ $Name:  $($Revision: 0.9.2.1 $) $Date: 2007/10/17 07:26:48 $
+# @(#) $RCSfile: missing2,v $ $Name:  $($Revision: 0.9.2.3 $) $Date: 2007/10/17 18:00:10 $
 #
 # -----------------------------------------------------------------------------
 #
@@ -46,7 +46,7 @@
 #
 # -----------------------------------------------------------------------------
 #
-# Last Modified $Date: 2007/10/17 07:26:48 $ by $Author: brian $
+# Last Modified $Date: 2007/10/17 18:00:10 $ by $Author: brian $
 #
 # =============================================================================
 
@@ -99,6 +99,8 @@ Supported PROGRAM values:
   latex		    touch the output file
   pslatex	    touch the output file
   pdflatex	    touch the output file
+  bibtex	    touch the output file
+  latex2html	    touch the output file
   dvips		    touch the output file
   dvipdf	    touch the output file
   gnuplot	    touch the output file
@@ -168,7 +170,19 @@ case $1 in
     (dvipdf|gnuplot|fig2dev|convert)
 	# do not handle --version or --help
 	;;
-    (latex|pslatex|pdflatex|dvips|*)
+    (latex2html)
+	# handles --version but not --help (well)
+	if test -z "$run" && ($1 --version) >/dev/null 2>&1 ; then
+	    # it exists, but it failed.
+	    exit 1
+	elif test ":$2" = ":--version" ; then
+	    # Could not run --version.  This is probably someone
+	    # running `$TOOL --version' to check whether $TOOL
+	    # exists and not knowing $TOOL uses missing2.
+	    exit 1
+	fi
+	;;
+    (latex|pslatex|pdflatex|bibtex|dvips|*)
 	if test -z "$run" && ($1 --version) >/dev/null 2>&1 ; then
 	    # it exists, but it failed.
 	    exit 1
@@ -198,7 +212,7 @@ case $1 in
 *** popular Linux Distributions.  On recent RPM based systems, try \`yum
 *** install tetex-latex'.  On recent DEB based systems, try \`apt-get
 *** install tetex-base tetex-bin'.  \`Latex' has been available for many
-*** years: you can get \`Latex' from an CTAN site.
+*** years: you can get \`Latex' from any CTAN site.
 ***
 EOF
 	# Note that missing2 is being executed in the build directory.
@@ -238,7 +252,7 @@ EOF
 *** RPM based systems, try \`yum install tetex-latex'.  On recent DEB
 *** based systems, try \`apt-get install tetex-base tetex-bin'.
 *** \`Latex' has been available for many years: you can get \`Latex'
-*** from an CTAN site.
+*** from any CTAN site.
 ***
 EOF
 	# Note that missing2 is being executed in the build directory.
@@ -278,7 +292,7 @@ EOF
 *** recent RPM based systems, try \`yum install tetex-latex'.  On recent
 *** DEB based systems, try \`apt-get install tetex-base tetex-bin'.
 *** \`Latex' has been available for many years: you can get \`Latex'
-*** from an CTAN site.
+*** from any CTAN site.
 ***
 EOF
 	# Note that missing2 is being executed in the build directory.
@@ -293,6 +307,83 @@ EOF
 		    exit 0
 		fi
 		# if .pdf file exists in build directory, touch it
+		OUTFILE=`echo "$OUTFILE" | sed 's,.*/,,'`
+		if test -f "$OUTFILE" ; then
+		    touch "$OUTFILE"
+		    exit 0
+		fi
+	    fi
+	fi
+	exit 1
+	;;
+    (bibtex)
+	# Calling bibtex on a file with format %[.tex] should result in a file
+	# named %.bib.  Therefore, if the file %.bib exists in the source
+	# directory, then simply touch it.  Otherwise, create a default file in
+	# the build directory and complain.
+	cat 1>&2 <<EOF
+*** WARNING: \`$1' is needed, and is $msg.
+***
+*** You may have altered some LaTeX files that need to be converted to
+*** bibliography files.  You may need the \`tetex' package to convert those
+*** LaTeX files to BIB files.  You can normally get \`tetex' as part of many
+*** popular Linux Distributions.  On recent RPM based systems, try \`yum install
+*** tetex'.  On recent DEB based systems, try \`apt-get install tetex-base
+*** tetex-bin'.  \`Bibtex' has been available for many years: you can get
+*** \`Bibtex' from any CTAN site.
+***
+EOF
+	# Note that missing2 is being executed in the build directory.
+	if test $# -gt 1 ; then
+	    eval LASTARG="\${$#}"
+	    SRCFILE=`echo "$LASTARG" | sed 's,\.tex$,,;s,$,.tex,'`
+	    if test -f "$SRCFILE" ; then
+		# if .bib file exists in source directory, touch it
+		OUTFILE=`echo "$SRCFILE" | sed 's,\.tex$,.bib,'`
+		if test -f "$OUTFILE" ; then
+		    touch "$OUTFILE"
+		    exit 0
+		fi
+		# if .bib file exists in build directory, touch it
+		OUTFILE=`echo "$OUTFILE" | sed 's,.*/,,'`
+		if test -f "$OUTFILE" ; then
+		    touch "$OUTFILE"
+		    exit 0
+		fi
+	    fi
+	fi
+	exit 1
+	;;
+    (latex2html)
+	# Calling bibtex on a file with format %[.tex] should result in a file
+	# named %.html (as long as -split 0 is given).  Therefore, if the file
+	# %.html exists in the source directory, then simply touch it.
+	# Otherwise, create a default file in the build directory and
+	# complain.
+	cat 1>&2 <<EOF
+*** WARNING: \`$1' is needed, and is $msg.
+***
+*** You may have altered some LaTeX files that need to be converted to HTML
+*** files.  You may need the \`latex2html' package to convert those LaTeX
+*** files to HTML files.  You can normally get \`latex2html' as part of many
+*** popular Linux Distributions.  On recent RPM based systems, try \`yum
+*** install latex2html'.  On recent DEB based systems, try \`apt-get install
+*** latex2html'.  \`Latex2html' has been available for many years: you can get
+*** \`Latex2html' from any CTAN site.
+***
+EOF
+	# Note that missing2 is being executed in the build directory.
+	if test $# -gt 1 ; then
+	    eval LASTARG="\${$#}"
+	    SRCFILE=`echo "$LASTARG" | sed 's,\.tex$,,;s,$,.tex,'`
+	    if test -f "$SRCFILE" ; then
+		# if .html file exists in source directory, touch it
+		OUTFILE=`echo "$SRCFILE" | sed 's,\.tex$,.html,'`
+		if test -f "$OUTFILE" ; then
+		    touch "$OUTFILE"
+		    exit 0
+		fi
+		# if .html file exists in build directory, touch it
 		OUTFILE=`echo "$OUTFILE" | sed 's,.*/,,'`
 		if test -f "$OUTFILE" ; then
 		    touch "$OUTFILE"
@@ -514,6 +605,12 @@ exit 0
 # =============================================================================
 #
 # $Log: missing2,v $
+# Revision 0.9.2.3  2007/10/17 18:00:10  brian
+# - added latex2html
+#
+# Revision 0.9.2.2  2007/10/17 17:43:04  brian
+# - build updates
+#
 # Revision 0.9.2.1  2007/10/17 07:26:48  brian
 # - added missing2: missing with other commands
 #
