Import from CVS Thu Feb  3 12:36:22 2005 -0600
- Spec file grand rework.
- updating documentation
- move recursive rpm targets to makefile fragment

diff --git a/strxns/strxns.spec.in b/strxns/strxns.spec.in
--- a/strxns/strxns.spec.in
+++ b/strxns/strxns.spec.in
@@ -1,7 +1,7 @@
 # vim: ft=spec sw=4 et
 # =============================================================================
 # 
-# @(#) $RCSfile: strxns.spec.in,v $ $Name:  $($Revision: 0.9.2.37 $) $Date: 2005/02/02 10:43:03 $
+# @(#) $RCSfile: strxns.spec.in,v $ $Name:  $($Revision: 0.9.2.38 $) $Date: 2005/02/03 12:34:56 $
 #
 # -----------------------------------------------------------------------------
 #
@@ -47,7 +47,7 @@
 #
 # -----------------------------------------------------------------------------
 #
-# Last Modified $Date: 2005/02/02 10:43:03 $ by $Author: brian $
+# Last Modified $Date: 2005/02/03 12:34:56 $ by $Author: brian $
 #
 # =============================================================================
 
@@ -78,10 +78,13 @@
 %global majbase @STRCONF_MAJBASE@
 %global makedev @STRCONF_MAKEDEV@
 %global base @PACKAGE_TARNAME@
-%global infofiles %{name}
 %global title @PACKAGE_TITLE@
 %global stitle @PACKAGE_SHORTTITLE@
-%global libname xns
+
+%global modules     ldl ip_strm_mod ip_to_dlpi
+%global libraries   xns
+%global tools       strxns_mknod ldlconfig ldltest
+%global infofiles   %{name}
 
 # because we only need to build the tools binaries once for each architecture,
 # but need to build the modules binaries once for each architecture and kernel
@@ -132,8 +135,6 @@
 %global _kmodext lis
 %global _conflict streams
 %endif
-
-%global _modules    ldl ip_strm_mod ip_to_dlpi
 
 # we have some more options that control configure for the build
 %{?disturl:%{!?url:%{expand: %%global url %{disturl}}}}
@@ -214,10 +215,10 @@ Autoreq:        true
 The %{name} package includes kernel modules, %{_STREAMS} STREAMS drivers,
 modules, libraries, utilities, test programs, daemons, and development
 environment for the development and execution of X/Open Network Services (XNS)
-protocol stack components and applications for the %{_STREAMS} STREAMS
-environment.  This distribution is only currently applicable to 2.4 kernels
-and was targetted at ix86 and ppc architectures, but should build and install
-for other architectures as well.
+protocol stack components and applications for the
+%{_STREAMS} STREAMS environment.  This distribution is only currently
+applicable to 2.4 kernels and was targetted at ix86 and ppc architectures, but
+should build and install for other architectures as well.
 
 %prep
 # ---------------------------------------------------------------------------
@@ -402,14 +403,15 @@ if [ ":%{kernel_version}" = ":`uname -r`" ] ; then
 #   if we are upgrading and the upgrade is for the running kernel, or we are
 #   installing new on the running kernel, we have to worry about previous
 #   loaded modules for the old version or a non-rpm version
-    for m in %{_modules} ; do
-        if ( /sbin/lsmod | grep -q "^streams-$m" ) ; then
+    for m in %{modules} ; do
+        m="streams-$m"
+        if ( /sbin/lsmod | grep -q "^$m" ) ; then
 #           module running, kick the stack
-            /sbin/modprobe -r `/sbin/lsmod | grep "^streams-$m" | cut -f1 '-d '`
-            if ( /sbin/lsmod | grep -q "^streams-$m" ) ; then
+            /sbin/modprobe -r `/sbin/lsmod | grep "^$m" | cut -f1 '-d '`
+            if ( /sbin/lsmod | grep -q "^$m" ) ; then
                 fdetach -a 2>/dev/null
-                /sbin/modprobe -r `/sbin/lsmod | grep "^streams-$m" | cut -f1 '-d '`
-                if ( /sbin/lsmod | grep -q "^streams-$m" ) ; then
+                /sbin/modprobe -r `/sbin/lsmod | grep "^$m" | cut -f1 '-d '`
+                if ( /sbin/lsmod | grep -q "^$m" ) ; then
                     /usr/sbin/lsof | while read -a tokens; do
                         if [ :"$tokens[4]" = :"CHR" ]; then
                             major=`echo "$tokens[5]" | sed -e 's|,.*||'`
@@ -418,9 +420,10 @@ if [ ":%{kernel_version}" = ":`uname -r`" ] ; then
                             fi
                         fi
                     done
-                    /sbin/modprobe -r `/sbin/lsmod | grep "^streams-$m" | cut -f1 '-d '`
-                    if ( /sbin/lsmod | grep -q "^streams-$m" ) ; then
-                        echo "Cannot install or upgrade with streams-$m module running." >&2
+                    /sbin/sleep 5 # wait for processes to die and close streams
+                    /sbin/modprobe -r `/sbin/lsmod | grep "^$m" | cut -f1 '-d '`
+                    if ( /sbin/lsmod | grep -q "^$m" ) ; then
+                        echo "Cannot install or upgrade with $m module running." >&2
                         exit 1
                     fi
                 fi
@@ -501,14 +504,15 @@ fi
 if [ $1 = 0 -a ":%{kernel_version}" = ":`uname -r`" ] ; then
 #   We are about to uninstall for good on a running kernel then we have to
 #   worry about which modules are running
-    for m in %{_modules} ; do
-        if ( /sbin/lsmod | grep -q "^streams-$m" ) ; then
+    for m in %{modules} ; do
+        m="streams-$m"
+        if ( /sbin/lsmod | grep -q "^$m" ) ; then
 #           modules running, kick the stack
-            /sbin/modprobe -r `/sbin/lsmod | grep "^streams-$m" | cut -f1 '-d '`
-            if ( /sbin/lsmod | grep -q "^streams-$m" ) ; then
+            /sbin/modprobe -r `/sbin/lsmod | grep "^$m" | cut -f1 '-d '`
+            if ( /sbin/lsmod | grep -q "^$m" ) ; then
                 fdetach -a
-                /sbin/modprobe -r `/sbin/lsmod | grep "^streams-$m" | cut -f1 '-d '`
-                if ( /sbin/lsmod | grep -q "^streams-$m" ) ; then
+                /sbin/modprobe -r `/sbin/lsmod | grep "^$m" | cut -f1 '-d '`
+                if ( /sbin/lsmod | grep -q "^$m" ) ; then
                     /usr/sbin/lsof | while read -a tokens; do
                         if [ :"$tokens[4]" = :"CHR" ]; then
                             major=`echo "$tokens[5]" | sed -e 's|,.*||'`
@@ -517,9 +521,10 @@ if [ $1 = 0 -a ":%{kernel_version}" = ":`uname -r`" ] ; then
                             fi
                         fi
                     done
-                    /sbin/modprobe -r `/sbin/lsmod | grep "^streams-$m" | cut -f1 '-d '`
-                    if ( /sbin/lsmod | grep -q "^streams-$m" ) ; then
-                        echo "Cannot uninstall with streams-$m module running." >&2
+                    /sbin/sleep 5 # wait for processes to die and close streams
+                    /sbin/modprobe -r `/sbin/lsmod | grep "^$m" | cut -f1 '-d '`
+                    if ( /sbin/lsmod | grep -q "^$m" ) ; then
+                        echo "Cannot uninstall with $m module running." >&2
                         exit 1
                     fi
                 fi
@@ -560,15 +565,16 @@ if [ :"%{kernel_version}" = :"`uname -r`" ] ; then
 #   one more kick at killing any loaded modules on uninstall, last stage of
 #   the upgrade on a running kernel for upgrade.
     reboot='no'
-    for m in %{_modules} ; do
-        if ( /sbin/lsmod | grep -q "^streams-$m" ) ; then
+    for m in %{modules} ; do
+        m="streams-$m"
+        if ( /sbin/lsmod | grep -q "^$m" ) ; then
 #           modules running, kick the stack
-            /sbin/modprobe -r `/sbin/lsmod | grep "^streams-$m" | cut -f1 '-d '`
-            if ( /sbin/lsmod | grep -q "^streams-$m" ) ; then
+            /sbin/modprobe -r `/sbin/lsmod | grep "^$m" | cut -f1 '-d '`
+            if ( /sbin/lsmod | grep -q "^$m" ) ; then
                 fdetach -a
-                /sbin/modprobe -r `/sbin/lsmod | grep "^streams-$m" | cut -f1 '-d '`
-                if ( /sbin/lsmod | grep -q "^streams-$m" ) ; then
-                    /sbin/insmod -ar "streams-$m"
+                /sbin/modprobe -r `/sbin/lsmod | grep "^$m" | cut -f1 '-d '`
+                if ( /sbin/lsmod | grep -q "^$m" ) ; then
+                    /sbin/insmod -ar "$m"
                     /usr/sbin/lsof | while read -a tokens; do
                         if [ :"$tokens[4]" = :"CHR" ]; then
                             major=`echo "$tokens[5]" | sed -e 's|,.*||'`
@@ -577,16 +583,17 @@ if [ :"%{kernel_version}" = :"`uname -r`" ] ; then
 #                                   extreme prejudice for removal
                                     eval "kill -KILL $tokens[1]"
                                 else
-#                                   try to get them to reload for 
+#                                   try to get them to reload for upgrade
                                     eval "kill -HUP $tokens[1]"
                                 fi
                             fi
                         fi
                     done
-                    /sbin/modprobe -r `/sbin/lsmod | grep "^streams-$m" | cut -f1 '-d '`
-                    if ( /sbin/lsmod | grep -q "^streams-$m" ) ; then
+                    /sbin/sleep 5 # wait for processes to die and close streams
+                    /sbin/modprobe -r `/sbin/lsmod | grep "^$m" | cut -f1 '-d '`
+                    if ( /sbin/lsmod | grep -q "^$m" ) ; then
                         echo "Error: modules may be still loaded" >&2
-                        /sbin/lsmod | grep "^streams-$m" >&2
+                        /sbin/lsmod | grep "^$m" >&2
                         reboot='yes'
                     fi
                 fi
@@ -614,6 +621,7 @@ fi
 Summary:        OpenSS7 %{_STREAMS} STREAMS %{stitle} devices.
 Group:          System Environment/Base
 Requires:       dev >= 3.3
+Obsoletes:      %{name}-devs
 Autoreq:        true
 %if %{?_xpm: 1}%{!?_xpm: 0}
 Icon:           %{_xpm}
@@ -666,6 +674,7 @@ Group:          System Environment/Libraries
 Prefix:         %{_libdir}
 Prefix:         %{_datadir}/locale
 Requires:       %{_streams}-lib >= %{_strvers}
+Obsoletes:      %{name}-%{_streams}-libs
 Prereq:         /sbin/ldconfig
 Autoreq:        true
 %if %{?_xpm: 1}%{!?_xpm: 0}
@@ -687,12 +696,14 @@ necessary to run applications programs and utilities developed for OpenSS7
 if [ $1 = 0 ] ; then
 #   this is supposed to be a fresh install
 #   see if there are any libraries hanging around from a non-rpm install
-    old_libs="`( /sbin/ldconfig -p | grep '\<lib.*%{libname}\> | cut '-d ' -f4 ) 2>/dev/null`"
-    if [ -n "$old_libs" ] ; then
+    libs="%{libraries}" ; for lib in $libs ; do
+        old_libs="`( /sbin/ldconfig -p | grep '\<lib'$lib'\>' | cut '-d ' -f4 ) 2>/dev/null`"
+        if [ -n "$old_libs" ] ; then
 #       old libraries hanging around, delete them
-        echo "warning: Deleting old non-rpm libraries $old_libs" >&2
-        rm -f $old_libs
-    fi
+            echo "warning: Deleting old non-rpm libraries $old_libs" >&2
+            rm -f $old_libs
+        fi
+    done
 else
     :
 #   upgrade, let RPM do its job
@@ -731,8 +742,8 @@ Group:          Documentation
 Prefix:         %{_docdir}
 Prefix:         %{_infodir}
 Prefix:         %{_mandir}
-#Requires:       %{_streams}-doc >= %{_strvers}
 Conflicts:      texinfo < 3.11
+Obsoletes:      %{name}-docs
 Prereq:         /sbin/install-info
 Autoreq:        true
 %if %{?_xpm: 1}%{!?_xpm: 0}
@@ -782,9 +793,9 @@ fi
 %files doc
 # ---------------------------------------------------------------------------
 %defattr(-,root,root)
-#%if %{BUILD_libs}
-#%doc ABOUT-NLS
-#%endif
+%if %{BUILD_libs}
+%doc ABOUT-NLS
+%endif
 %doc AUTHORS ChangeLog COPYING INSTALL NEWS README THANKS doc/manual
 %doc %{name}-%{version}-@PACKAGE_RELEASE@.lsm
 %{_infodir}/*
@@ -800,9 +811,6 @@ Summary:        OpenSS7 %{_STREAMS} STREAMS %{stitle} headers, lib and doc.
 Group:          Development/System
 Prefix:         %{_libdir}
 Prefix:         %{_includedir}
-#Requires:       %{name}-%{_streams}-lib = %{epoch}:%{version}-%{fullrelease}
-#Requires:       %{name}-doc = %{epoch}:%{version}-%{fullrelease}
-#Requires:       %{_streams}-devel >= %{_strvers}
 Autoreq:        true
 %if %{?_xpm: 1}%{!?_xpm: 0}
 Icon:           %{_xpm}
@@ -872,7 +880,8 @@ Prefix:         %{_sbindir}
 Prefix:         %{_libexecdir}
 Requires:       %{name}-%{_streams}-lib = %{epoch}:%{version}-%{fullrelease}
 Requires:       %{_streams}-lib >= %{_strvers}
-Conflicts:      %{_conflict}-lib
+Obsoletes:      %{name}-%{_streams}-utils
+Conflicts:      %{_conflict}-util
 Autoreq:        true
 %if %{?_xpm: 1}%{!?_xpm: 0}
 Icon:           %{_xpm}
@@ -884,9 +893,25 @@ Release:        %{fullrelease}
 
 # ---------------------------------------------------------------------------
 %description %{_streams}-util
-The %{name}-%{_streams}-util package provides adminstrative and configuration
+The %{name}-%{_streams}-util package provides administrative and configuration
 test utilities and commands associated with the OpenSS7 %{_STREAMS} STREAMS
 %{stitle} package.
+
+%pre %{_streams}-util
+# ---------------------------------------------------------------------------
+if [ $1 = 0 ]; then
+# this is a fresh install, look for old non-rpm tools
+    tools="%{tools}" ; for tool in $tools ; do
+        location="`which $tool 2>/dev/null`"
+        while [ -n "$location" -a -x "$location" ] ; do
+            eval "rm -f $location"
+            location="`which $tool 2>/dev/null`"
+        done
+    done
+else
+    :
+#   upgrade, let rpm do its job
+fi
 
 %if %{BUILD_tools}
 %files %{_streams}-util
@@ -901,33 +926,45 @@ test utilities and commands associated with the OpenSS7 %{_STREAMS} STREAMS
 %changelog
 # ---------------------------------------------------------------------------
 # $Log: strxns.spec.in,v $
-# Revision 0.9.2.37  2005/02/02 10:43:03  brian
-# - Build in builddir again.
+# Revision 0.9.2.38  2005/02/03 12:34:56  brian
+# - Spec file grand rework.
 #
-# Revision 0.9.2.36  2005/02/01 19:01:25  brian
-# - Working up master build.
-#
-# Revision 0.9.2.35  2005/01/29 11:22:41  brian
-# - Have master build working well.
-#
-# Revision 0.9.2.34  2005/01/27 08:30:30  brian
-# - Get tarball and srpm names right.
-#
-# Revision 0.9.2.33  2005/01/21 08:41:28  brian
-# - Work around mandrake spec-helper for uncooked manpages.
-#
-# Revision 0.9.2.32  2005/01/20 00:52:06  brian
-# - Go back to quick no dependencies compile.
-#
-# Revision 0.9.2.31  2005/01/19 07:38:49  brian
-# - Added checks and autotest options to configure.
-#
-# Revision 0.9.2.30  2005/01/18 20:23:47  brian
-# - Also reference makedev file one down.
-#
-# Revision 0.9.2.29  2005/01/18 13:31:22  brian
-# - Support multiple builds on same NFS mount.
-#
+
+* Wed Feb  2 2005 Brian Bidulock <bidulock@openss7.org>
+- Revision 0.9.2.37  2005/02/02 10:43:03  brian
+- Build in builddir again.
+
+* Tue Feb  1 2005 Brian Bidulock <bidulock@openss7.org>
+- Revision 0.9.2.36  2005/02/01 19:01:25  brian
+- Working up master build.
+
+* Sat Jan 29 2005 Brian Bidulock <bidulock@openss7.org>
+- Revision 0.9.2.35  2005/01/29 11:22:41  brian
+- Have master build working well.
+
+* Thu Jan 27 2005 Brian Bidulock <bidulock@openss7.org>
+- Revision 0.9.2.34  2005/01/27 08:30:30  brian
+- Get tarball and srpm names right.
+
+* Fri Jan 21 2005 Brian Bidulock <bidulock@openss7.org>
+- Revision 0.9.2.33  2005/01/21 08:41:28  brian
+- Work around mandrake spec-helper for uncooked manpages.
+
+* Thu Jan 20 2005 Brian Bidulock <bidulock@openss7.org>
+- Revision 0.9.2.32  2005/01/20 00:52:06  brian
+- Go back to quick no dependencies compile.
+
+* Wed Jan 19 2005 Brian Bidulock <bidulock@openss7.org>
+- Revision 0.9.2.31  2005/01/19 07:38:49  brian
+- Added checks and autotest options to configure.
+
+* Tue Jan 18 2005 Brian Bidulock <bidulock@openss7.org>
+- Revision 0.9.2.30  2005/01/18 20:23:47  brian
+- Also reference makedev file one down.
+
+* Tue Jan 18 2005 Brian Bidulock <bidulock@openss7.org>
+- Revision 0.9.2.29  2005/01/18 13:31:22  brian
+- Support multiple builds on same NFS mount.
 
 * Tue Jan 18 2005 Brian Bidulock <bidulock@openss7.org>
 - Revision 0.9.2.28  2005/01/18 10:42:40  brian
