Import from CVS Sat Dec 17 20:14:37 2005 -0600
- added pkgobject output

diff --git a/LiS/scripts/strconf-sh b/LiS/scripts/strconf-sh
--- a/LiS/scripts/strconf-sh
+++ b/LiS/scripts/strconf-sh
@@ -1,7 +1,7 @@
 #!/bin/bash
 # =============================================================================
 # 
-# @(#) $RCSfile: strconf-sh,v $ $Name:  $($Revision: 0.9.2.24 $) $Date: 2005/12/16 09:56:56 $
+# @(#) $RCSfile: strconf-sh,v $ $Name:  $($Revision: 0.9.2.25 $) $Date: 2005/12/17 20:14:37 $
 #
 # -----------------------------------------------------------------------------
 #
@@ -47,7 +47,7 @@
 #
 # -----------------------------------------------------------------------------
 #
-# Last Modified $Date: 2005/12/16 09:56:56 $ by $Author: brian $
+# Last Modified $Date: 2005/12/17 20:14:37 $ by $Author: brian $
 #
 # =============================================================================
 
@@ -158,6 +158,7 @@ confmodules=
 strmknods=
 strsetup=
 strload=
+pkgobject=
 
 # Parse our command line options once, thoroughly.
 while test "$#" -gt 0 -o ":$more" != ":"
@@ -178,17 +179,18 @@ do
         --driverconf=* | --drvrconf=* | --drvconf=* | --drconf=* | --dconf=* | --l* | \
         --confmodules=* | --confmodule=* | --confmodul=* | --confmodu=* | --confmod=* | --confmo=* | --conf=* | --con=* | --co=* | --c=* | --L=* | \
         --functionname=* | --funcname=* | --funcnam=* | --function=* | --func=* | --fncname=* | --fncnam=* | --fnc=* | --f=* | --r=* | \
-        --package=* | --packag=* | --packa=* | --pack=* | --pac=* | --pa=* | --k=*)
+        --package=* | --packag=* | --packa=* | --pack=* | --pac=* | --pa=* | --k=* | \
+        --pkgobject=* | --pkgobjec=* | --pkgobje=* | --pkgobj=* | --pkgob=* | --pkgo=* | --pkg=* | --pk=* | --g=* )
             optarg=`$echo "X$arg" | $Xsed -e 's/[-_a-zA-Z0-9]*=//'` ;;
         --*=*)
             opt=`$echo -n "X$1" | $Xsed -e 's|=.*||'`
             $echo "$program: syntax error -- \`$opt' does not accept an argument" >&2
             $echo "$help" >&2
             exit 2 ;;
-        -[bBhomHprlLsSOk])
+        -[bBhomHprlLsSOkg])
             optarg= ;;
-        -[bBhomHprlLsSOk]*)
-            optarg=`$echo "X$arg" | $Xsed -e 's/-[bBhomHprlLsSOk]//'` ;;
+        -[bBhomHprlLsSOkg]*)
+            optarg=`$echo "X$arg" | $Xsed -e 's/-[bBhomHprlLsSOkg]//'` ;;
         *)
             optarg= ;;
     esac
@@ -296,6 +298,10 @@ do
             prevopt="$arg" ; prev=package ;;
         --package=* | --packag=* | --packa=* | --pack=* | --pac=* | --pa=* | --k=* | -k*)
             package="$optarg" ; reexec="$reexec --package=\"$optarg\"" ;;
+        --pkgobject | --pkgobjec | --pkgobje | --pkgobj | --pkgob | --pkgo | --pkg | --pk | --g | -g)
+            prevopt="$arg" ; prev=pkgobject ;;
+        --pkgobject=* | --pkgobjec=* | --pkgobje=* | --pkgobj=* | --pkgob=* | --pkgo=* | --pkg=* | --pk=* | --g=* | -g*)
+            pkgobject="$optarg" ; reexec="$reexec --pkgobject=\"$optarg\"" ;;
         --) # end of options
             more_options=no
             ;;
@@ -327,7 +333,7 @@ if test -n "$prev" ; then
 fi
 
 if test X"$show_version" = Xyes ; then
-    $echo "$progname:"' Version $Name:  $($Revision: 0.9.2.24 $) $Date: 2005/12/16 09:56:56 $'
+    $echo "$progname:"' Version $Name:  $($Revision: 0.9.2.25 $) $Date: 2005/12/17 20:14:37 $'
 fi
 
 if test X"$show_help" = Xyes ; then
@@ -456,8 +462,8 @@ imajor="$basemajor"
 idnumber=1
 lineno=0
 set noglob
-cat $infile | ( \
 qlock_encountered=no
+cat $infile | (
 while read -a tokens
 do
     ((lineno++))
@@ -780,31 +786,33 @@ EOF
 major=$basemajor
 space_loads=
 space_links=
-for objname in $strconf_drv_objnames
+for object in $strconf_drv_objnames
 do
+    objname=`$echo -n $object | $strconf_tokenize`
     eval "loadable=\"\$strconf_loadable_$objname\""
     eval "name=\"\$strconf_name_$objname\""
     if test ":$loadable" = ":yes" ; then
-#        $echo "alias char-major-$major  streams-$objname		# driver $name" >>$confmodules
-        modconf_drv_loads="$modconf_drv_loads$space_loads$objname"
+#        $echo "alias char-major-$major  streams-$object		# driver $name" >>$confmodules
+        modconf_drv_loads="$modconf_drv_loads$space_loads$object"
         space_loads=' '
     else
 #        $echo "alias char-major-$major  streams			# driver $name" >>$confmodules
-        modconf_drv_links="$modconf_drv_links$space_links$objname"
+        modconf_drv_links="$modconf_drv_links$space_links$object"
         space_links=' '
     fi
     ((major++))
 done
 space_loads=
 space_links=
-for objname in $strconf_mod_objnames
+for object in $strconf_mod_objnames
 do
+    objname=`$echo -n $object | $strconf_tokenize`
     eval "loadable=\"\$strconf_loadable_$objname\""
     if test ":$loadable" = ":yes" ; then
-        modconf_mod_loads="$modconf_mod_loads$space_loads$objname"
+        modconf_mod_loads="$modconf_mod_loads$space_loads$object"
         space_loads=' '
     else
-        modconf_mod_links="$modconf_mod_links$space_links$objname"
+        modconf_mod_links="$modconf_mod_links$space_links$object"
         space_links=' '
     fi
 done
@@ -1938,6 +1946,264 @@ cat >>$confmodules <<EOF
 
 # --------------------------------
 # vim: ft=conf
+EOF
+fi
+
+#
+#   Generate pkgobject wrapper
+#
+if test x"$pkgobject" != x
+then
+pkgdir=`dirname $pkgobject`
+object=`basename $pkgobject .o`
+pkgwrapper="${pkgdir}/${object}_wrapper.c"
+modtype=''
+if test -z "$modtype" ; then
+    for obj in $strconf_drv_objnames ; do
+        if test "$obj" = "$object" ; then
+            modtype='driver'
+            break
+        fi
+    done
+fi
+if test -z "$modtype" ; then
+    for obj in $strconf_mod_objnames ; do
+        if test "$obj" = "$object" ; then
+            modtype='module'
+            break
+        fi
+    done
+fi
+if test -z "$modtype" ; then
+    $echo "$progname: error: cannot find object $object"
+    exit 1
+fi
+objname=`$echo -n $object | $strconf_tokenize`
+eval "name=\"\$strconf_name_$objname\""
+eval "realname=\"\$strconf_realname_$name\""
+eval "prefix=\"\$strconf_prefix_$name\""
+Prefix=`$echo $prefix | $strconf_uppercase`
+eval "major=\"\$strconf_major_$name\""
+eval "nmajors=\"\$strconf_nmajors_$name\""
+eval "nminors=\"\$strconf_nminors_$name\""
+eval "init=\"\$strconf_initialize_$name\""
+eval "term=\"\$strconf_terminate_$name\""
+eval "qlock=\"\$strconf_qlock_$name\""
+cat >$pkgwrapper <<EOF
+/******************************************************************* vim: ft=c
+
+ Copyright (c) 2001-2005  OpenSS7 Corporation <http://www.openss7.com>
+ Copyright (c) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>
+
+ All Rights Reserved.
+
+ This program is free software; you can redistribute it and/or modify it under
+ the terms of the GNU General Public License as published by the Free Software
+ Foundation; either version 2 of the License, or (at your option) any later
+ version.
+
+ This program is distributed in the hope that it will be useful, but WITHOUT
+ ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
+ FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
+ details.
+
+ You should have received a copy of the GNU General Public License along with
+ this program; if not, write to the Free Software Foundation, Inc., 675 Mass
+ Ave, Cambridge, MA 02139, USA.
+
+ -----------------------------------------------------------------------------
+
+ U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
+ behalf of the U.S. Government ("Government"), the following provisions apply
+ to you.  If the Software is supplied by the Department of Defense ("DoD"), it
+ is classified as "Commercial Computer Software" under paragraph 252.227-7014
+ of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
+ successor regulations) and the Government is acquiring only the license rights
+ granted herein (the license rights customarily provided to non-Government
+ users).  If the Software is supplied to any unit or agency of the Government
+ other than DoD, it is classified as "Restricted Computer Software" and the
+ Government's rights in the Software are defined in paragraph 52.227-19 of the
+ Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
+ the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
+ (or any successor regulations).
+
+ -----------------------------------------------------------------------------
+
+ Commercial licensing and support of this software is available from OpenSS7
+ Corporation at a fee.  See http://www.openss7.com/
+
+ *****************************************************************************/
+
+/*
+ * GENERATED BY $progname (`date`) FROM ${infile:-(stdin)}
+ * EDITS TO THIS FILE WILL BE LOST: EDIT $progname INSTEAD.
+ */
+
+#ident "@(#) \$RCSfile\$ \$Name\$(\$Revision\$) \$Date\$"
+
+static char const ident[] = "\$RCSfile\$ \$Name\$(\$Revision\$) \$Date\$";
+
+#include <linux/config.h>
+#include <linux/version.h>
+#include <linux/module.h>
+#include <linux/init.h>
+
+#include <sys/kmem.h>
+#include <sys/stream.h>
+#include <sys/strconf.h>
+#include <sys/ddi.h>
+
+#define _XX_DESCRIP	"UNIX/SYSTEM V RELEASE 4 STREAMS FOR LINUX"
+#define _XX_COPYRIGHT	"Copyright (c) 1997-2005 OpenSS7 Corporation.  All Rights Reserved."
+#define _XX_DEVICE	"LiS Binary Compatibility Wrapper for ${pkgobject}"
+#define _XX_CONTACT	"Brian Bidulock <bidulock@openss7.org>"
+#define _XX_LICENSE	"Proprietary"
+#define _XX_BANNER	_XX_DESCRIP	"\n" \\
+			_XX_COPYRIGHT	"\n" \\
+			_XX_DEVICE	"\n" \\
+			_XX_CONTACT
+
+MODULE_AUTHOR(_XX_CONTACT);
+MODULE_DESCRIPTION(_XX_DESCRIP);
+MODULE_SUPPORTED_DEVICE(_XX_DEVICE);
+#ifdef MODULE_LICENSE
+MODULE_LICENSE(_XX_LICENSE);
+#endif				/* MODULE_LICENSE */
+#if defined MODULE_ALIAS
+MODULE_ALIAS("streams-${object}");
+EOF
+if test :"$modtype" = :driver ; then
+    count=0
+    while test $count -lt $nmajors
+    do
+        $echo "MODULE_ALIAS(\"char-major-$((major+count++))\")" >>$pkgwrapper
+    done
+fi
+cat >>$pkgwrapper <<EOF
+#endif
+
+extern struct module_info ${prefix}info;
+EOF
+if test :"$init" = :yes ; then
+    $echo "extern void FASTCALL(${prefix}init(void));" >>$pkgwrapper
+fi
+if test :"$term" = :yes ; then
+    $echo "extern void FASTCALL(${prefix}term(void));" >>$pkgwrapper
+fi
+case $modtype in
+    driver)
+        $echo "static int _xx_majors[${nmajors}] = {" >>$pkgwrapper
+        count=0
+        while test $count -lt $nmajors
+        do
+            $echo "	$((major+count++))," >>$pkgwrapper
+        done
+        $echo "};" >>$pkgwrapper
+        cat >>$pkgwrapper <<EOF
+
+static void
+_xx_del(void)
+{
+	int err, mindex;
+
+	for (mindex = ${nmajors} - 1; mindex >= 0; mindex--) {
+		if (_xx_majors[mindex]) {
+			if ((err = lis_unregister_strdev(_xx_majors[mindex])))
+				cmn_err(CE_PANIC, "${realname}: cannot unregister major %d", _xx_majors[mindex]);
+			_xx_majors[mindex] = 0;
+		}
+	}
+}
+
+static int
+_xx_add(void)
+{
+	int err, mindex = 0, major;
+
+	cmn_err(CE_NOTE, _XX_BANNER);	/* console splash */
+	for (mindex = 0; mindex < ${nmajors}; mindex++) {
+		if ((err = lis_register_strdev(_xx_majors[mindex], &${prefix}info, ${nminors}, "${realname}")) < 0) {
+			if (mindex) {
+				cmn_err(CE_WARN, "${realname}: could not register major %d", _xx_majors[mindex]);
+				continue;
+			} else {
+				cmn_err(CE_WARN, "${realname}: could not register driver, err = %d", err);
+				return (err);
+			}
+		}
+		if (_xx_majors[mindex] == 0)
+			_xx_majors[mindex] = err;
+		if ((err = lis_register_qlock_option(_xx_majors[mindex], ${qlock:--1})) < 0)
+			cmn_err(CE_WARN, "${realname}: could not register qlock option, err = %d", err);
+	}
+	return (0);
+}
+EOF
+        ;;
+    module)
+        cat >>$pkgwrapper <<EOF
+
+static void
+_xx_del(void)
+{
+	int err;
+
+	if ((err = lis_unregister_strmod(&${prefix}info)) < 0) {
+		cmn_err(CE_PANIC, "${realname}: cannot unregister module, err = %d", err);
+		return (err);
+	}
+	return (0);
+}
+
+static int
+__xx_add(void)
+{
+	int err, modid;
+
+	cmn_err(CE_NOTE, _XX_BANNER);	/* console splash */
+	if ((modid = lis_register_strmod(&${prefix}info, "${realname}")) == LIS_NULL_MID) {
+		cmn_err(CE_WARN, "${realname}: could not register module");
+		return (-ENXIO);
+	}
+	if ((err = lis_register_qlock_option(modid, ${qlock:--1})) < 0)
+		cmn_err(CE_WARN, "${realname}: could not register qlock option, err = %d", err);
+	return (0);
+}
+EOF
+        ;;
+esac
+cat >>$pkgwrapper <<EOF
+
+static void __exit
+_xx_exit(void)
+{
+EOF
+if test :"$init" = :yes ; then
+        $echo "	${prefix}term(); /* only if we have a terminate function */" >>$pkgwrapper
+fi
+cat >>$pkgwrapper <<EOF
+	_xx_del();
+}
+
+static int __init
+_xx_init(void)
+{
+	int err;
+
+	if ((err = _xx_add())) {
+		_xx_del();
+		return (err);
+	}
+EOF
+if test :"$init" = :yes ; then
+        $echo "	${prefix}init(); /* only if we have an initialize function */" >>$pkgwrapper
+fi
+cat >>$pkgwrapper <<EOF
+	return (0);
+}
+
+module_init(_xx_init);
+module_exit(_xx_exit);
 EOF
 fi
 )
