- corrections for urpmi

diff --git a/scripts/register.in b/scripts/register.in
--- a/scripts/register.in
+++ b/scripts/register.in
@@ -55,7 +55,8 @@ PACKAGE="@PACKAGE@"
 PACKAGE_UCNAME="@PACKAGE_UCNAME@"
 PACKAGE_NAME="@PACKAGE_NAME@"
 
-DISTDIR=
+DISTDIR="@DISTDIR@"
+DESTDIR=
 rootdir=
 
 target_distro="@target_distro@"
@@ -76,8 +77,10 @@ aptvndlist="@aptvndlist@"
 aptvenddir="@aptvenddir@"
 
 urpmiconfdir="@urpmiconfdir@"
-urpmirepodir="@urpmirepodir@"
+urpmiconfig="@urpmiconfig@"
 urpmimediadir="@urpmimediadir@"
+urpminetrc="@urpmiconfdir@/netrc"
+urpmirepodir="@urpmirepodir@"
 
 yumdir="${DESTDIR}${rootdir}/etc/yum"
 yumrepodir="@yumrepodir@"
@@ -162,12 +165,13 @@ fi
 # Defaults
 
 command=
-DISTDIR="@DISTDIR@"
+distdir="@DISTDIR@"
 config=$pkgstatedir/project
 clean=
 remote=yes
 rlocal=no
 nolock=
+freshen=
 debug=0
 verbose=1
 run=
@@ -177,6 +181,17 @@ u_apt=
 u_yum=
 u_zypp=
 u_urpmi=
+
+doany () {
+    local c
+    c="$1"
+    shift
+    if [ ${debug:-0} -gt 0 ]; then
+        echo "D: $c $@" >&2
+    fi
+    eval "$c $@" || return $?
+    return 0
+}
 
 doit () {
     local c
@@ -262,7 +277,7 @@ Options:
     -z, --zypper
         update zypper installation sources [${u_zypp:-no}]
     -d, --distdir DIRECTORY
-        consider distribution directory [$DISTDIR]
+        consider distribution directory [$distdir]
     -g, --config FILE
         use specified configuration file [$config]
     -c, --clean
@@ -271,6 +286,8 @@ Options:
         local installation sources [${rlocal:-no}]
     -N, --nolock
         do not use locking commands [${nolock:-no}]
+    -F, --freshen
+        use depsolver to freshen db [${freshen:-no}]
     -n, --dryrun
         don't perform the actions, just check them
     -Q, --quiet
@@ -307,7 +324,9 @@ Configuration:
     aptvenddir="$aptvenddir"
 
     urpmiconfdir="$urpmiconfdir"
+    urpmiconfig="$urpmiconfig"
     urpmirepodir="$urpmirepodir"
+    urpminetrc="$urpminetrc"
     urpmimediadir="$urpmimediadir"
 
     yumdir="$yumdir"
@@ -421,11 +440,11 @@ while [ "$#" -gt 0 -o ":$more" != ":" ]; do
 	    optarg=`$ECHO "X$arg" | $Xsed -e 's,[-_a-zA-Z0-9]*=,,'` ;;
 	--*=*)
 	    option_noarg $arg ;;
-	-[uerRaiyzclNnQDvhVC])
+	-[uerRaiyzclNFnQDvhVC])
 	    optarg= ;;
-	-[uerRaiyzclNnQDvhVC]*)
+	-[uerRaiyzclNFnQDvhVC]*)
 	    optarg=
-	    more=`$ECHO "X$arg" | $Xsed -e 's,-[uerRaiyzclNnQDvhVC],,'`
+	    more=`$ECHO "X$arg" | $Xsed -e 's,-[uerRaiyzclNFnQDvhVC],,'`
 	    eval "arg=\`$ECHO \"X$arg\" | $Xsed -e 's,$more,,'\`"
 	    ;;
 	-[dg])
@@ -442,7 +461,7 @@ while [ "$#" -gt 0 -o ":$more" != ":" ]; do
 		case $prev in
 		    debug | verbose) eval "(($prev++))" ;;
 		    # the rest have required arguments
-		    DISTDIR | config)
+		    distdir | config)
 			option_needarg $prevopt ;;
 		esac
 		prev=; prevopt=
@@ -499,10 +518,10 @@ while [ "$#" -gt 0 -o ":$more" != ":" ]; do
 	    ;;
         --distdir | --distdi | --distd | --dist | --dis | --di | --d | -d)
             prevopt="$arg"
-            prev=DISTDIR
+            prev=distdir
             ;;
         --distdir=* | --distdi=* | --distd=* | --dist=* | --dis=* | --di=* | --d=* | -d*)
-            DISTDIR="$optarg"
+            distdir="$optarg"
             ;;
         --config | --confi | --conf | --con | --co | --c | -g)
             prevopt="$arg"
@@ -549,6 +568,9 @@ while [ "$#" -gt 0 -o ":$more" != ":" ]; do
         --nolock | --noloc | --nolck | --nolo | --no | -N)
             nolock=yes
             ;;
+        --freshen | --freshe | --fresh | --fres | --fre | --fr | --f | -F)
+            freshen=yes
+            ;;
 	--)
 	    # end of options
 	    break
@@ -567,7 +589,7 @@ case $prev in
     # these have optional arguments
     debug | verbose) eval "(($prev++))" ;;
     # the rest have required arguments
-    DISTDIR | config)
+    distdir | config)
 	option_needarg $prevopt ;;
 esac
 
@@ -611,16 +633,21 @@ if [ ${run:-yes} = yes -a ${root:-yes} = no ]; then
     $ECHO "Only root can do some things." >&2
 fi
 
-[ -x "`which apt 2>/dev/null`"    -a -d "$aptsrclist"   ] && HAVE_aptrepo=yes
-[ -x "`which urpmi 2>/dev/null`"  -a -d "$urpmirepodir" ] && HAVE_urpmirepo=yes
-[ -x "`which yum 2>/dev/null`"    -a -d "$yumdir"       ] && HAVE_yumrepo=yes
-[ -x "`which zypper 2>/dev/null`" -a -f "$zyppconfig"   ] && HAVE_zypprepo=yes
+if test ! -x "`which apt    2>/dev/null`" ; then u_apt=no;   fi
+if test ! -x "`which urpmi  2>/dev/null`" ; then u_urpmi=no; fi
+if test ! -x "`which yum    2>/dev/null`" ; then u_yum=no;   fi
+if test ! -x "`which zypper 2>/dev/null`" ; then u_zypp=no;  fi
+
+if test ! -f "$aptsrclist"   ; then u_apt=no;   fi
+if test ! -d "$urpmiconfdir" ; then u_urpmi=no; fi
+if test ! -d "$yumdir"       ; then u_yum=no;   fi
+if test ! -f "$zyppconfig"   ; then u_zypp=no;  fi
 
 find_credentials () {
     local s p d f t
     for s in '' .rpmsave .dpkg-old .rpmnew .dpkg-new ; do
         for p in product credentials; do
-            for d in $pkgstatedir/ $DISTDIR/; do
+            for d in $pkgstatedir/ $distdir/ $DISTDIR/; do
                 f=$d$p$s
                 if [ -r $f ]; then
                     username=`awk 'BEGIN{FS="="}{if($1~/^username$/){print$2;exit}}' $f`
@@ -643,7 +670,7 @@ find_credentials () {
             password=`sed -n -r 's,^.*baseurl[[:space:]]*=[[:space:]]*http[s]?://([^@:]*)(:([^@]*))@.*$,\3,p;t end;b;: end q' $f`
             if [ -n "$username" -a -n "$password" ]; then break 1; fi
         fi
-        f=$urpmiconfdir/netrc$s
+        f=$urpminetrc$s
         if [ -r $f ]; then
             username=`sed -n -r 's,^machine[[:space:]]*'$repobase'[[:space:]]*login[[:space:]]*([^[:space:]]*)[[:space:]]*password[[:space:]]*([^[:space:]]*)[[:space:]]*.*$,\1,p;t end;b;: end q' $f`
             password=`sed -n -r 's,^machine[[:space:]]*'$repobase'[[:space:]]*login[[:space:]]*([^[:space:]]*)[[:space:]]*password[[:space:]]*([^[:space:]]*)[[:space:]]*.*$,\2,p;t end;b;: end q' $f`
@@ -660,7 +687,10 @@ find_credentials () {
             done
         done
     done
-    [ -n "$username" -a -n "$password" ] || return 1
+    if [ -z "$username" -o -z "$password" ]; then
+        echo "Cannot find credentials (after looking everywhere)." >&2
+        return 1
+    fi
     return 0
 }
 
@@ -696,12 +726,12 @@ get_temp () {
     t="$1"
     n="`basename $t`"; [ -n "$n" ] || return 1
     t="$t.$$"
-    rm -f -- $t
+    doany rm -f -- $t
     url="$reposerv://`get_key`$repobase/$reporoot/$n`get_ext`"
     if ! echo "$url" | wget -i - -O $t 2>/dev/null; then
         e=$(echo "$url" | wget -i - -O /dev/null 2>&1)
         [ ${debug:-0} -eq 0 ] || echo "$e" >&2
-        [ ${debug:-0} -ne 0 ] || rm -f -- $t
+        [ ${debug:-0} -ne 0 ] || doany rm -f -- $t
         if echo "$e" | grep -i '401 Authorization Required' >/dev/null 2>&1; then
             return 2
         fi
@@ -719,7 +749,7 @@ get_url () {
     t=${TMPDIR:-/var/tmp}/$n
     get_temp $t || return $?
     doroot cp -fp -- $t.$$ $f
-    [ ${debug:-0} -ne 0 ] || rm -f -- $t.$$
+    [ ${debug:-0} -ne 0 ] || doany rm -f -- $t.$$
     return 0
 }
 
@@ -729,7 +759,7 @@ get_local () {
     n="`basename $f`"; [ -n "$n" ] || return 1
     d="`dirname  $f`"; [ -n "$d" ] || d=.
     [ -d "$d" ] || doroot mkdir -p -- "$d"
-    file="$DISTDIR/$reporoot/$repotype/$distro/$relver/$osarch"
+    file="$distdir/$repotype/$distro/$relver/$osarch"
     case "$n" in
         product|credentials)
             file="$file/$n" ;;
@@ -864,36 +894,46 @@ update_credentials () {
 }
 
 refresh_yum () {
-    if [ ${nolock:-no} != yes -a -x "`which yum 2>/dev/null`" ]; then
-        doroot yum makecache
+    if [ \( ${nolock:-no} != yes -o ${freshen:-no} = yes \) -a -x "`which yum 2>/dev/null`" ]; then
+        doroot yum makecache || :
+    else
+        echo "You must perform \`sudo yum makecache' yourself." >&2
     fi
 }
 
 refresh_zypp () {
-    if [ ${nolock:-no} != yes -a -x "`which zypper 2>/dev/null`" ]; then
-        doroot zypper refresh
+    if [ \( ${nolock:-no} != yes -o ${freshen:-no} = yes \) -a -x "`which zypper 2>/dev/null`" ]; then
+        doroot zypper refresh || :
+    else
+        echo "You must perform \`sudo zypper refresh' yourself." >&2
     fi
 }
 
 refresh_urpmi () {
-    if [ ${nolock:-no} != yes -a -x "`which urpmi.update 2>/dev/null`" ]; then
-        doroot urpmi.update -a -f
+    if [ \( ${nolock:-no} != yes -o ${freshen:-no} = yes \) -a -x "`which urpmi.update 2>/dev/null`" ]; then
+        doroot urpmi.update -a -f || :
+    else
+        echo "You must perform \`sudo uprmi.update -a -f' yourself." >&2
     fi
 }
 
 refresh_apt () {
-    if [ ${nolock:-no} != yes -a -x "`which apt-get 2>/dev/null`" ]; then
-        doroot apt-get update
+    if [ \( ${nolock:-no} != yes -o ${freshen:-no} = yes \) -a -x "`which apt-get 2>/dev/null`" ]; then
+        doroot apt-get update || :
+    else
+        echo "You must perform \`sudo apt-get update' yourself." >&2
     fi
-    if [ ${nolock:-no} != yes -a -x "`which apt-cache 2>/dev/null`" ]; then
-        doroot apt-cache gencaches
+    if [ \( ${nolock:-no} != yes -o ${freshen:-no} = yes \) -a -x "`which apt-cache 2>/dev/null`" ]; then
+        doroot apt-cache gencaches || :
+    else
+        echo "You must perform \`sudo apt-cache gencaches' yourself." >&2
     fi
 }
 
 erase_yum () {
     local s t
     for s in $PACKAGE $PACKAGE-local; do
-        t=$yumrepodir/$s.repooo
+        t=$yumrepodir/$s.repo
         [ ! -e $t ] || doroot rm -f -- $t
     done
 }
@@ -909,7 +949,7 @@ erase_zypp () {
             t=$zyppcreddir/${s}credentials
             [ ! -e $t ] || doroot rm -f -- $t
             find $localstatedir/cache/zypp -name $s':'$PACKAGE'*' 2>/dev/null | \
-            while read f; do if -d "$f"; then doroot rm -fr -- "$f"; else doroot rm -f -- "$f"; fi; done
+            while read f; do if [ -d "$f" ]; then doroot "rm -fr -- \"$f\""; else doroot "rm -f -- \"$f\""; fi; done
         fi
     done
 }
@@ -920,29 +960,29 @@ erase_urpmi () {
         if [ ${nolock:-no} != yes -a -x "`which urpmi.removemedia 2>/dev/null`" ]; then
             doroot urpmi.removemedia -y $s
         else
-            f=$urpmiconfdir/urpmi.cfg
+            f=$urpmiconfig
             if [ -r $f ]; then
                 t=${TMPDIR:-/var/tmp}/urpmi.cfg.$$
-                rm -f -- $t
-                cat /dev/null >$t
-                sed '/^.*('$s'[0-9]*).*{/,/}/d' $f | cat -s >$t
+                doany rm -f -- $t
+                doany "cat /dev/null >$t"
+                doany "sed '/^.*('$s'[0-9]*).*{/,/}/d' $f | cat -s >$t"
                 doroot cp -fp -- $t $f
-                [ ${debug:-0} -ne 0 ] || rm -f -- $t
+                [ ${debug:-0} -ne 0 ] || doany rm -f -- $t
             fi
             find $localstatedir/lib/urpmi -name '*('$s'[0-9]*)*' 2>/dev/null | \
-            while read f; do if -d "$f"; then doroot rm -fr -- "$f"; else doroot rm -f -- "$f"; fi; done
+            while read f; do if [ -d "$f" ]; then doroot "rm -fr -- \"$f\""; else doroot "rm -f -- \"$f\""; fi; done
         fi
     done
-    f=$urpmiconfdir/netrc
+    f=$urpminetrc
     if [ -r $f ]; then
         t=${TMPDIR:-/var/tmp}/netrc.$$
-        rm -f -- $t
-        ( umask 0077; cat /dev/null >$t )
-        sed '/^machine[[:space:]]*'$repobase'/d' $f >>$t
+        doany rm -f -- $t
+        doany "( umask 0077; cat /dev/null >$t )"
+        doany "sed '/^machine[[:space:]]*'$repobase'/d' $f >>$t"
         doroot cp -fp -- $t $f
-        [ ${debug:-0} -ne 0 ] || rm -f -- $t
+        [ ${debug:-0} -ne 0 ] || doany rm -f -- $t
     fi
-    rm -fr -- $urpmimediadir
+    doroot rm -fr -- $urpmimediadir
 }
 
 erase_apt () {
@@ -954,10 +994,10 @@ erase_apt () {
         [ ! -e $t ] || doroot rm -f -- $t
     done
     if [ ${nolock:-no} = yes -o ! -x "`which apt-get 2>/dev/null`" ]; then
-        for s in $repobase $DISTDIR; do
+        for s in $repobase $distdir; do
             s=`echo "$s" | sed -r 's,[^a-zA-Z0-9\._],?,g'`
             find $localstatedir/lib/apt -name $s'*' 2>/dev/null | \
-            while read f; do if -d "$f"; then doroot rm -fr -- "$f"; else doroot rm -f -- "$f"; fi; done
+            while read f; do if [ -d "$f" ]; then doroot "rm -fr -- \"$f\""; else doroot "rm -f -- \"$f\""; fi; done
         done
     fi
 }
@@ -983,20 +1023,18 @@ update_zypp () {
     get_file $zyppservdir/$s.service || return 1
     if [ ${rlocal:-no} = no ]; then
         [ -d $zyppcreddir ] || doroot mkdir -p -- $zyppcreddir
-        if [ ${run:-yes} = yes -a ${root:-yes} = yes ]; then
-            ( umask 0077; echo -e "username=$username\npassword=$password" >$zyppcreddir/${s}credentials )
-        fi
+        doroot "( umask 0077; echo -e \"username=$username\\npassword=$password\" >$zyppcreddir/${s}credentials )"
     fi
     return 0
 }
 
 update_urpmi () {
-    local s m c t f
+    local s m c t f r
     if [ ${nolock:-no} != yes -a -x "`which uprmi.addmedia 2>/dev/null`" ]; then
         doroot "urpmi.addmedia --distrib ${PACKAGE} '$reposerv://`get_key`$repobase/$reporoot/rpms/$distro/$relver/$osarch'"
     else
         t=${TMPDIR:-/var/tmp}/netrc.$$
-        f=$urpmiconfdir/netrc
+        f=$urpminetrc
         if [ ${rlocal:=no} = yes ] ; then
             s=$PACKAGE-local
             m=media.cfg
@@ -1006,11 +1044,9 @@ update_urpmi () {
             m=media.cfg
             c=urpmi.cfg
         fi
-        rm -f -- $t
-        ( umask 0077; cat /dev/null >$t )
-        {   if [ -r $f ]; then cat $f; fi
-            echo "machine $repobase login $username password $password"
-        } >>$t
+        doany rm -f -- $t
+        doany "( umask 0077; cat /dev/null >$t )"
+        doany "{ if [ -r $f ]; then cat $f; fi; echo "machine $repobase login $username password $password"; } >>$t"
         doroot cp -fp -- $t $f
         [ ${debug:-0} -ne 0 ] || rm -f -- $t
         get_file $urpmimediadir/$m || return 1
@@ -1018,21 +1054,11 @@ update_urpmi () {
         doroot "echo '$reposerv://$repobase/$reporoot/rpms/$distro/$relver/$osarch' >$urpmimediadir/url"
         doroot "echo '$reposerv://$repobase/$reporoot/rpms/$distro/$relver/$osarch' >$urpmimediadir/mirrorlist"
         t=${TMPDIR:-/var/tmp}/$c.edit.$$
-        s=$urpmimediadir/$c
-        f=$urpmiconfdir/$c
-        {
-            if [ -r $f ]; then
-                sed -n '/^{/,/^}/p' $f
-            fi
-            if [ -r $s ]; then
-                cat $s
-            fi
-            if [ -r $f ]; then
-                sed '/^{/,/^}/d;/^.*('$s'[0-9]*).*{/,/}/d' $f
-            fi
-        } | cat -s >$t
+        r=$urpmimediadir/$c
+        f=$urpmiconfig
+        doany "{ sed -n '/^{/,/^}/p' $f; cat $r; sed '/^{/,/^}/d;/^.*('$s'[0-9]*).*{/,/}/d' $f; } 2>/dev/null | cat -s >$t"
         doroot cp -fp -- $t $f
-        [ ${debug:-0} -ne 0 ] || rm -f -- $t
+        [ ${debug:-0} -ne 0 ] || doany rm -f -- $t
     fi
     return 0
 }
