Import from CVS Sun Feb 13 08:14:57 2005 -0600
Finished up these helper scripts.

diff --git a/streams/scripts/install_initd b/streams/scripts/install_initd
--- a/streams/scripts/install_initd
+++ b/streams/scripts/install_initd
@@ -1,7 +1,7 @@
 #!/bin/bash
 # =============================================================================
 # 
-# @(#) $RCSfile: install_initd,v $ $Name:  $($Revision: 0.9.2.1 $) $Date: 2005/02/12 22:45:48 $
+# @(#) $RCSfile: install_initd,v $ $Name:  $($Revision: 0.9.2.3 $) $Date: 2005/02/13 10:16:47 $
 #
 # -----------------------------------------------------------------------------
 #
@@ -47,11 +47,11 @@
 #
 # -----------------------------------------------------------------------------
 #
-# Last Modified $Date: 2005/02/12 22:45:48 $ by $Author: brian $
+# Last Modified $Date: 2005/02/13 10:16:47 $ by $Author: brian $
 #
 # =============================================================================
 
-ident='@(#) $RCSfile: install_initd,v $ $Name:  $($Revision: 0.9.2.1 $) $Date: 2005/02/12 22:45:48 $'
+ident='@(#) $RCSfile: install_initd,v $ $Name:  $($Revision: 0.9.2.3 $) $Date: 2005/02/13 10:16:47 $'
 
 ECHO='echo'
 SHELL='/bin/bash'
@@ -115,13 +115,13 @@ fi
 # Make sure IFS has a sensible default
 : ${IFS=" 	"}
 
-chkconfig_letters='abcdefghijklmnopqrstuvwxyz'
-chkconfig_LETTERS='ABCDEFGHIJKLMNOPQRSTUVWXYZ'
-chkconfig_Letters=$strconf_letters$strconf_LETTERS
-chkconfig_numbers='0123456789'
-chkconfig_alphano=$strconf_Letters$strconf_numbers
-chkconfig_uppercase="$SED y%*$strconf_letters%P$strconf_LETTERS%;s%[^_$strconf_alphano]%_%g"
-chkconfig_tokenize="$SED s%[^a-zA-Z0-9]%_%g"
+initd_letters='abcdefghijklmnopqrstuvwxyz'
+initd_LETTERS='ABCDEFGHIJKLMNOPQRSTUVWXYZ'
+initd_Letters=$strconf_letters$strconf_LETTERS
+initd_numbers='0123456789'
+initd_alphano=$strconf_Letters$strconf_numbers
+initd_uppercase="$SED y%*$strconf_letters%P$strconf_LETTERS%;s%[^_$strconf_alphano]%_%g"
+initd_tokenize="$SED s%[^a-zA-Z0-9]%_%g"
 
 # Defaults
 
@@ -185,11 +185,6 @@ Options:
 	prints the version and exits
     -C, --copying
 	prints copying permissions and exits
-Environment:
-    DESTDIR
-	the location of the target directory
-    rootdir
-	the location of the root directory
 EOF
 }
 
@@ -435,11 +430,8 @@ initname="$(basename $filename)"
 initrddir="$(dirname $filename)"
 
 if test ! -d "${initrddir:-.}" ; then
-    initrddir="${DESTDIR}${rootdir}${initrddir}"
-    if test ! -d "${initrddir:-.}" ; then
-	$ECHO "error: directory '${initrddir:-.}' does not exist"
-	exit 1
-    fi
+    $ECHO "error: directory '${initrddir:-.}' does not exist"
+    exit 1
 fi
 
 initrddir=`(cd $initrddir ; pwd)`
@@ -451,32 +443,33 @@ if test ! -f "$filename" ; then
 fi
 
 declare -a chkconfig
-
 chkconfig=(`grep '^#[[:space:]][[:space:]]*chkconfig:[[:space:]][[:space:]]*[-0-7][0-7]*[[:space:]][[:space:]]*[0-9][0-9][[:space:]][[:space:]]*[0-9][0-9][[:space:]]*' $filename`)
+lsbconfig="$(cat $filename | sed -e '/^### BEGIN INIT INFO$/,/^### END INIT INFO$/!d')"
 
-if test -z "${chkconfig[*]}" ; then
-    $ECHO "error: '$initname' does not support chkconfig"
+if [ -z "${chkconfig[*]}" -a -z "${lsbconfig}" ] ; then
+    $ECHO "service $initname does not support $program" >&2
     exit 1
 fi
 
-slevs="${chkconfig[2]}"
-sprio="${chkconfig[3]}"
-kprio="${chkconfig[4]}"
-
-slevs=`echo "$slevs" | sed -e 's|.|& |g;s| $||'`
-
-klevs=
-for l in 0 1 2 3 4 5 6 ; do
-    case " $slevs " in
-	(*" $l "*) continue ;;
-	(*) klevs="${klevs}${klevs:+ }${l}" ;;
-    esac
-done
-
-$ECHO "slevs = '$slevs'"
-$ECHO "klevs = '$klevs'"
-$ECHO "sprio = '$sprio'"
-$ECHO "kprio = '$kprio'"
+if test -n "${chkconfig[*]}" ; then
+    slevs="${chkconfig[2]}"
+    sprio="${chkconfig[3]}"
+    kprio="${chkconfig[4]}"
+    slevs=`echo "$slevs" | sed -e 's|.|& |g;s| $||'`
+    klevs=
+    for l in 0 1 2 3 4 5 6 ; do
+	case " $slevs " in
+	    (*" $l "*) continue ;;
+	    (*) klevs="${klevs}${klevs:+ }${l}" ;;
+	esac
+    done
+else
+    slevs=`echo "$lsbconf" | grep '^# Default-Start:' | sed -e 's|^# Default-Start:[[:space:]]*||'`
+    klevs=`echo "$lsbconf" | grep '^# Default-Stop:' | sed -e 's|^# Default-Stop:[[:space:]]*||'`
+#   cannot handle priorities yet...
+    $ECHO "service $initname does not support $program" >&2
+    exit 1
+fi
 
 basedir="$(basename $initrddir)"
 
@@ -487,13 +480,6 @@ fi
 
 initroot="$(dirname $initrddir)"
 
-for dir in $initroot/rc[0-6].d ; do
-    if test ! -d $dir ; then
-	$ECHO "error: '$initroot/rc[0-6].d' do not exist"
-	exit 1
-    fi
-done
-
 for l in 0 1 2 3 4 5 6 ; do
     if test ! -d $initroot/rc${l}.d ; then
 	mkdir -p -- $initroot/rc${l}.d
@@ -502,16 +488,14 @@ for l in 0 1 2 3 4 5 6 ; do
     case " $slevs " in
 	(*" $l "*)
 	    [ -L S${sprio}${initname} -a "$(readlink S${sprio}${initname})" = ../init.d/$initname ] \
-	    || ln -sf ../init.d/$initname S${sprio}${initname} || :
+	    || ln -sf ../init.d/$initname S${sprio}${initname}
 	    ;;
 	(*)
 	    [ -L K${kprio}${initname} -a "$(readlink K${kprio}${initname})" = ../init.d/$initname ] \
-	    || ln -sf ../init.d/$initname K${kprio}${initname} || :
+	    || ln -sf ../init.d/$initname K${kprio}${initname}
 	    ;;
     esac
     popd >/dev/null
 done
-
-
 
 # vim: ft=sh sw=4
