Import from CVS Thu Jul 14 05:14:27 2005 -0600
- checks for hangin source manpages
- better checks
- mask one more slash

diff --git a/strcompat/scripts/check_libs b/strcompat/scripts/check_libs
--- a/strcompat/scripts/check_libs
+++ b/strcompat/scripts/check_libs
@@ -1,7 +1,7 @@
 #!/bin/bash
 # =============================================================================
 # 
-# @(#) $RCSfile: check_libs,v $ $Name:  $($Revision: 0.9.2.24 $) $Date: 2005/07/12 04:57:52 $
+# @(#) $RCSfile: check_libs,v $ $Name:  $($Revision: 0.9.2.27 $) $Date: 2005/07/14 09:10:17 $
 #
 # -----------------------------------------------------------------------------
 #
@@ -47,7 +47,7 @@
 #
 # -----------------------------------------------------------------------------
 #
-# Last Modified $Date: 2005/07/12 04:57:52 $ by $Author: brian $
+# Last Modified $Date: 2005/07/14 09:10:17 $ by $Author: brian $
 #
 # =============================================================================
 
@@ -92,6 +92,22 @@ function echo_w()
 	echo "$me:$2: W: $1" >&5
 	((warnings++))
 }
+function echo_fls()
+{
+	echo_s "$3" "$4"
+}
+function echo_flw()
+{
+	echo "$1:$2: warning: $3" >&2
+	echo "$me:$4: W: $3" >&5
+	((warnings++))
+}
+function echo_fle()
+{
+	echo "$1:$2: error: $3" >&2
+	echo "$me:$4: E: $3" >&5
+	((errors++))
+}
 
 export -p | while read line
 do
@@ -105,7 +121,9 @@ then
 	else
 		manpath="${top_builddir}/doc/man:${top_builddir}/man:${top_builddir}:./doc/man:./man:.${mandir:+:${mandir}}"
 	fi
+	srcpath="${top_srcdir}/doc/man:${top_srcdir}/man:${top_srcdir}:${srcdir}/doc/man:${srcdir}/man:${srcdir}${mandir:+:$mandir}"
 	searchpath=`echo "$manpath" | sed -e 's|:| |g'`
+	sourcepath=`echo "$srcpath" | sed -e 's|:| |g'`
 	#
 	# Check for manual pages corresponding to the library names so that we are sure that each
 	# module or drier has some high level documentation.
@@ -143,6 +161,17 @@ then
 		if test :$found = :yes ; then
 			echo_s "found $string" $LINENO
 		else
+			for page in $list; do
+				for dir in $sourcepath ; do
+					test -d $dir || continue
+					files=`ls $dir/$page*.man` 2>/dev/null
+					for file in $files ; do
+						if test -f $file ; then
+							echo_w "manual source page for $mcname, $file exists" $LINENO
+						fi
+					done
+				done
+			done
 			echo_e "cannot find $string" $LINENO
 		fi
 	done
@@ -276,6 +305,17 @@ then
 		if test :$found = :yes ; then
 			echo_s "found $string" $LINENO
 		else
+			for page in $list; do
+				for dir in $sourcepath ; do
+					test -d $dir || continue
+					files=`ls $dir/$page*.man 2>/dev/null`
+					for file in $files ; do
+						if test -f $file ; then
+							echo_w "manual source page for $symbol, $file exists" $LINENO
+						fi
+					done
+				done
+			done
 			eval "$on_error \"cannot find \$string\" \$LINENO"
 		fi
 #		echo_d "man -aw -M $manpath -S 2:3 $symbol 2>&1" $LINENO
diff --git a/strsctp/scripts/check_streams b/strsctp/scripts/check_streams
--- a/strsctp/scripts/check_streams
+++ b/strsctp/scripts/check_streams
@@ -1,7 +1,7 @@
 #!/bin/bash
 # =============================================================================
 # 
-# @(#) $RCSfile: check_streams,v $ $Name:  $($Revision: 0.9.2.9 $) $Date: 2005/07/12 04:57:52 $
+# @(#) $RCSfile: check_streams,v $ $Name:  $($Revision: 0.9.2.12 $) $Date: 2005/07/14 09:10:17 $
 #
 # -----------------------------------------------------------------------------
 #
@@ -47,13 +47,18 @@
 #
 # -----------------------------------------------------------------------------
 #
-# Last Modified $Date: 2005/07/12 04:57:52 $ by $Author: brian $
+# Last Modified $Date: 2005/07/14 09:10:17 $ by $Author: brian $
 #
 # =============================================================================
 
 me=`basename $0`
 errors=0
 warnings=0
+
+abs_top_builddir=`(cd $top_builddir; pwd)`
+abs_builddir=`(cd $builddir; pwd)`
+abs_top_srcdir=`(cd $top_srcdir; pwd)`
+abs_srcdir=`(cd $srcdir; pwd)`
 
 exec 5>>$top_builddir/$me.log
 
@@ -91,6 +96,22 @@ function echo_w()
 #	fi
 	echo "$me:$2: W: $1" >&5
 	((warnings++))
+}
+function echo_fls()
+{
+	echo_s "$3" "$4"
+}
+function echo_flw()
+{
+	echo "$1:$2: warning: $3" >&2
+	echo "$me:$4: W: $3" >&5
+	((warnings++))
+}
+function echo_fle()
+{
+	echo "$1:$2: error: $3" >&2
+	echo "$me:$4: E: $3" >&5
+	((errors++))
 }
 
 export -p | while read line
@@ -152,9 +173,11 @@ then
 	if test -n "$PKG_MANPATH" ; then
 		manpath="$PKG_MANPATH"
 	else
-		manpath="${top_builddir}/doc/man:${top_builddir}/man:${top_builddir}:./doc/man:./man:.${mandir:+:${mandir}}"
+		manpath="${abs_top_builddir}/doc/man:${abs_top_builddir}/man:${abs_top_builddir}:./doc/man:./man:.${mandir:+:${mandir}}"
 	fi
+	srcpath="${abs_top_srcdir}/doc/man:${abs_top_srcdir}/man:${abs_top_srcdir}:${abs_srcdir}/doc/man:${abs_srcdir}/man:${abs_srcdir}${mandir:+:$mandir}"
 	searchpath=`echo "$manpath" | sed -e 's|:| |g'`
+	sourcepath=`echo "$srcpath" | sed -e 's|:| |g'`
 	#
 	# For each driver name, check that there is a manual page in section 4.
 	#
@@ -189,6 +212,17 @@ then
 		if test :$found = :yes ; then
 			echo_s "found $string" $LINENO
 		else
+			for page in $list; do
+				for dir in $sourcepath ; do
+					test -d $dir || continue
+					files=`ls $dir/$page*.man 2>/dev/null`
+					for file in $files ; do
+						if test -f $file ; then
+							echo_flw "$file" "1" "manual source page for $string" $LINENO
+						fi
+					done
+				done
+			done
 			echo_e "cannot find $string" $LINENO
 		fi
 	done
@@ -223,6 +257,17 @@ then
 		if test :$found = :yes ; then
 			echo_s "found $string" $LINENO
 		else
+			for page in $list; do
+				for dir in $sourcepath ; do
+					test -d $dir || continue
+					files=`ls $dir/$page*.man 2>/dev/null`
+					for file in $files ; do
+						if test -f $file ; then
+							echo_flw "$file" "1" "manual source page for $string" $LINENO
+						fi
+					done
+				done
+			done
 			echo_e "cannot find $string" $LINENO
 		fi
 	done
@@ -260,6 +305,17 @@ then
 		if test :$found = :yes ; then
 			echo_s "found $string" $LINENO
 		else
+			for page in $list; do
+				for dir in $sourcepath ; do
+					test -d $dir || continue
+					files=`ls $dir/$page*.man 2>/dev/null`
+					for file in $files ; do
+						if test -f $file ; then
+							echo_flw "$file" "1" "manual source page for $string" $LINENO
+						fi
+					done
+				done
+			done
 			echo_e "cannot find $string" $LINENO
 		fi
 	done
diff --git a/strxnet/scripts/check_commands b/strxnet/scripts/check_commands
--- a/strxnet/scripts/check_commands
+++ b/strxnet/scripts/check_commands
@@ -1,7 +1,7 @@
 #!/bin/bash
 # =============================================================================
 # 
-# @(#) $RCSfile: check_commands,v $ $Name:  $($Revision: 0.9.2.26 $) $Date: 2005/07/12 04:57:52 $
+# @(#) $RCSfile: check_commands,v $ $Name:  $($Revision: 0.9.2.28 $) $Date: 2005/07/14 09:10:17 $
 #
 # -----------------------------------------------------------------------------
 #
@@ -47,7 +47,7 @@
 #
 # -----------------------------------------------------------------------------
 #
-# Last Modified $Date: 2005/07/12 04:57:52 $ by $Author: brian $
+# Last Modified $Date: 2005/07/14 09:10:17 $ by $Author: brian $
 #
 # =============================================================================
 
@@ -97,6 +97,22 @@ function echo_w()
 #	fi
 	echo "$me:$2: W: $1" >&5
 	((warnings++))
+}
+function echo_fls()
+{
+	echo_s "$3" "$4"
+}
+function echo_flw()
+{
+	echo "$1:$2: warning: $3" >&2
+	echo "$me:$4: W: $3" >&5
+	((warnings++))
+}
+function echo_fle()
+{
+	echo "$1:$2: error: $3" >&2
+	echo "$me:$4: E: $3" >&5
+	((errors++))
 }
 
 export -p | while read line
