Import from CVS Wed Jul 13 10:10:59 2005 -0600
- make header filenames absolute

diff --git a/strcompat/scripts/check_decls b/strcompat/scripts/check_decls
--- a/strcompat/scripts/check_decls
+++ b/strcompat/scripts/check_decls
@@ -1,7 +1,7 @@
 #!/bin/bash
 # =============================================================================
 # 
-# @(#) $RCSfile: check_decls,v $ $Name:  $($Revision: 0.9.2.5 $) $Date: 2005/07/13 01:37:14 $
+# @(#) $RCSfile: check_decls,v $ $Name:  $($Revision: 0.9.2.7 $) $Date: 2005/07/13 12:01:21 $
 #
 # -----------------------------------------------------------------------------
 #
@@ -47,7 +47,7 @@
 #
 # -----------------------------------------------------------------------------
 #
-# Last Modified $Date: 2005/07/13 01:37:14 $ by $Author: brian $
+# Last Modified $Date: 2005/07/13 12:01:21 $ by $Author: brian $
 #
 # =============================================================================
 
@@ -92,17 +92,21 @@ function echo_w()
 	echo "$me:$2: W: $1" >&5
 	((warnings++))
 }
-function echo_fle()
+function echo_fls()
 {
-	echo "$1:$2: error: $3" >&2
-	echo "$me:$4: E: $1:$2: error: $3" >&5
-	((errors++))
+	echo_s $3 $4
 }
 function echo_flw()
 {
 	echo "$1:$2: warning: $3" >&2
-	echo "$me:$4: E: $1:$2: warning: $3" >&5
+	echo "$me:$4: W: $3" >&5
 	((warnings++))
+}
+function echo_fle()
+{
+	echo "$1:$2: error: $3" >&2
+	echo "$me:$4: E: $3" >&5
+	((errors++))
 }
 
 export -p | while read line
@@ -145,7 +149,11 @@ then
 			echo_t "testing ${tokens[1]} ${tokens[0]} for exported symbol"
 			case "${tokens[0]}" in
 				(_*)	on_error='echo_flw' ;;
-				(*)	on_error='echo_fle' ;;
+				(*)	if test :"$WARN_EXCESS" = :yes
+					then on_error='echo_flw'
+					else on_error='echo_fle'
+					fi
+					;;
 			esac
 			case " $symbols " in
 				(*" ${tokens[0]} "*)
