Import from CVS Mon Dec 19 12:47:33 2005 -0600
- locking down for release

diff --git a/strbcm/scripts/remove_initd b/strbcm/scripts/remove_initd
--- a/strbcm/scripts/remove_initd
+++ b/strbcm/scripts/remove_initd
@@ -1,7 +1,7 @@
 #!/bin/bash
 # =============================================================================
 # 
-# @(#) $RCSfile: remove_initd,v $ $Name:  $($Revision: 0.9.2.6 $) $Date: 2005/12/16 09:24:55 $
+# @(#) $RCSfile: remove_initd,v $ $Name:  $($Revision: 0.9.2.7 $) $Date: 2005/12/19 12:44:59 $
 #
 # -----------------------------------------------------------------------------
 #
@@ -47,11 +47,11 @@
 #
 # -----------------------------------------------------------------------------
 #
-# Last Modified $Date: 2005/12/16 09:24:55 $ by $Author: brian $
+# Last Modified $Date: 2005/12/19 12:44:59 $ by $Author: brian $
 #
 # =============================================================================
 
-ident='@(#) $RCSfile: remove_initd,v $ $Name:  $($Revision: 0.9.2.6 $) $Date: 2005/12/16 09:24:55 $'
+ident='@(#) $RCSfile: remove_initd,v $ $Name:  $($Revision: 0.9.2.7 $) $Date: 2005/12/19 12:44:59 $'
 
 ECHO='echo'
 SHELL='/bin/bash'
@@ -469,21 +469,30 @@ rootdir=${rootdir//\/rc.d/}
 rootdir=${rootdir//\/init.d/}
 rootdir=${rootdir//\/etc/}
 
-# if [ -z "$rootdir" ] ; then
-# # If we are installing on the host, we might as well use the host's
-# # own removal function, it one exists
-#     if [ -x /usr/lib/lsb/install_initd ] ; then
-# 	/usr/lib/lsb/remove_initd $filename
-# 	exit $?
-#     fi
-#     if [ -x /sbin/insserv ] ; then
-# 	/sbin/insserv -r $filename
-# 	exit $?
-#     fi
-#     if [ -x /sbin/chkconfig ] ; then
-# 	/sbin/chkconfig --del $initname
-#     fi
-# fi
+# If we are installing on the host, we might as well use the host's
+# own removal function, it one exists
+if [ -z "$rootdir" ] ; then
+    if [ -x /usr/lib/lsb/install_initd ] ; then
+	$ECHO " /usr/lib/lsb/remove_initd $filename"
+	/usr/lib/lsb/remove_initd $filename
+	RETVAL=$?
+	[ $RETVAL -eq 0 ] && exit 0
+    fi
+    if [ -x /sbin/insserv ] ; then
+	$ECHO " /sbin/insserv -r $filename"
+	/sbin/insserv -r $filename
+	RETVAL=$?
+	[ $RETVAL -eq 0 ] && exit 0
+    fi
+    if [ -x /sbin/chkconfig ] ; then
+	$ECHO " /sbin/chkconfig --del $initname"
+	/sbin/chkconfig --del $initname
+	RETVAL=$?
+	[ $RETVAL -eq 0 ] && exit 0
+    fi
+fi
+
+# Fall back to doing it ourselves
 
 sysconfdir="${rootdir}/etc"
 
@@ -519,7 +528,7 @@ elif [ -d $sysconfdir/rc.d/rc0.d ] ; then
     basedir="init.d"
     flavor="chkconfig"
 else
-    $ECHO "error: $program cannot grok SysV init for $initname" >&2
+    $ECHO "warning: $program cannot grok SysV init for $initname" >&2
     exit 1
 fi
 
diff --git a/streams/scripts/install_initd b/streams/scripts/install_initd
--- a/streams/scripts/install_initd
+++ b/streams/scripts/install_initd
@@ -1,7 +1,7 @@
 #!/bin/bash
 # =============================================================================
 # 
-# @(#) $RCSfile: install_initd,v $ $Name:  $($Revision: 0.9.2.5 $) $Date: 2005/12/16 09:24:55 $
+# @(#) $RCSfile: install_initd,v $ $Name:  $($Revision: 0.9.2.6 $) $Date: 2005/12/19 12:44:59 $
 #
 # -----------------------------------------------------------------------------
 #
@@ -47,11 +47,11 @@
 #
 # -----------------------------------------------------------------------------
 #
-# Last Modified $Date: 2005/12/16 09:24:55 $ by $Author: brian $
+# Last Modified $Date: 2005/12/19 12:44:59 $ by $Author: brian $
 #
 # =============================================================================
 
-ident='@(#) $RCSfile: install_initd,v $ $Name:  $($Revision: 0.9.2.5 $) $Date: 2005/12/16 09:24:55 $'
+ident='@(#) $RCSfile: install_initd,v $ $Name:  $($Revision: 0.9.2.6 $) $Date: 2005/12/19 12:44:59 $'
 
 ECHO='echo'
 SHELL='/bin/bash'
@@ -469,27 +469,33 @@ rootdir=${rootdir//\/init.d/}
 rootdir=${rootdir//\/etc/}
 
 # If we are installing on the host, we might as well use the host's
-# own install function, if one exists
+# own install function, if one exists.  chkconfig works best on most
+# platforms, insserv next, and, strangely enough, lsb is the least
+# compatible.
 
 if [ -z "$rootdir" ] ; then
     if [ -x /usr/lib/lsb/install_initd ] ; then
 	$ECHO " /usr/lib/lsb/install_initd $filename"
 	/usr/lib/lsb/install_initd $filename
-	exit $?
+	RETVAL=$?
+	[ $RETVAL -eq 0 ] && exit 0
     fi
     if [ -x /sbin/insserv ] ; then
 	$ECHO " /sbin/insserv -v $filename"
 	/sbin/insserv -v $filename
-	exit $?
+	RETVAL=$?
+	[ $RETVAL -eq 0 ] && exit 0
     fi
     if [ -x /sbin/chkconfig ] ; then
 	$ECHO " /sbin/chkconfig --add $initname"
 	/sbin/chkconfig --add $initname
 	RETVAL=$?
 	[ $RETVAL -eq 0 ] && /sbin/chkconfig --list $initname
-	exit $RETVAL
+	[ $RETVAL -eq 0 ] && exit 0
     fi
 fi
+
+# Fall back to doing it ourselves.
 
 sysconfdir="${rootdir}/etc"
 
@@ -525,7 +531,7 @@ elif [ -d $sysconfdir/rc.d/rc0.d ] ; then
     basedir="init.d"
     flavor="chkconfig"
 else
-    $ECHO "error: $program cannot grok SysV init for $initname" >&2
+    $ECHO "warning: $program cannot grok SysV init for $initname" >&2
     exit 1
 fi
 
