Import from CVS Fri Mar 10 02:57:38 2006 -0600
- updating configuration script and process

diff --git a/strbcm/scripts/strconf-sh b/strbcm/scripts/strconf-sh
--- a/strbcm/scripts/strconf-sh
+++ b/strbcm/scripts/strconf-sh
@@ -1,7 +1,7 @@
 #!/bin/bash
 # =============================================================================
 # 
-# @(#) $RCSfile: strconf-sh,v $ $Name:  $($Revision: 0.9.2.31 $) $Date: 2006/03/09 14:01:16 $
+# @(#) $RCSfile: strconf-sh,v $ $Name:  $($Revision: 0.9.2.32 $) $Date: 2006/03/10 02:57:38 $
 #
 # -----------------------------------------------------------------------------
 #
@@ -46,7 +46,7 @@
 #
 # -----------------------------------------------------------------------------
 #
-# Last Modified $Date: 2006/03/09 14:01:16 $ by $Author: brian $
+# Last Modified $Date: 2006/03/10 02:57:38 $ by $Author: brian $
 #
 # =============================================================================
 
@@ -74,6 +74,7 @@ EOF
     exit 0
 fi
 
+edirname=`$echo "$0" | ${SED} -e 's|[^/]*$||;s|^$|.|'`
 progname=`$echo "$0" | ${SED} -e 's%^.*/%%'`
 modename="$progname"
 reexec="$SHELL $0"
@@ -113,6 +114,15 @@ fi
 
 # Make sure IFS has a sensible default
 : ${IFS=" 	"}
+
+#
+# Now we need to find the source and build directories.  Of course, the build
+# directory is the current directory, however, the source directory is
+# whatever directory we were invoked in minus the 'scripts' component.  If it
+# was specified relative, it will be relative.
+#
+srcdir=`$echo $0 | sed -e 's|/scripts/[^/]*$||'`
+builddir='.'
 
 strconf_letters='abcdefghijklmnopqrstuvwxyz'
 strconf_LETTERS='ABCDEFGHIJKLMNOPQRSTUVWXYZ'
@@ -159,7 +169,7 @@ confmodules=
 strmknods=
 strsetup=
 strload=
-packagedirs=
+packagedir=
 
 # Parse our command line options once, thoroughly.
 while test "$#" -gt 0 -o ":$more" != ":"
@@ -182,7 +192,7 @@ do
         --functionname=* | --funcname=* | --funcnam=* | --function=* | --func=* | --fncname=* | --fncnam=* | --fnc=* | --f=* | --r=* | \
         --package=* | --packag=* | --packa=* | --pack=* | --pac=* | --pa=* | --k=* | \
         --pkgobject=* | --pkgobjec=* | --pkgobje=* | --pkgobj=* | --pkgob=* | --pkgo=* | --pkg=* | --pk=* | --g=* | \
-        --packagedirs=* | --packagedir=* | --packagedi=* | --packaged=* | --d=* \
+        --packagedir=* | --packagedi=* | --packaged=* | --d=* \
         )
             optarg=`$echo "X$arg" | $Xsed -e 's/[-_a-zA-Z0-9]*=//'` ;;
         --*=*)
@@ -305,10 +315,10 @@ do
             prevopt="$arg" ; prev=pkgobject ;;
         --pkgobject=* | --pkgobjec=* | --pkgobje=* | --pkgobj=* | --pkgob=* | --pkgo=* | --pkg=* | --pk=* | --g=* | -g*)
             pkgobject="$optarg" ; reexec="$reexec --pkgobject=\"$optarg\"" ;;
-        --packagedirs | --packagedir | --packagedi | --packaged | --d | -d)
-            prevopt="$arg" ; prev=packagedirs ;;
-        --packagedirs=* | --packagedir=* | --packagedi=* | --packaged=* | --d=* | -d*)
-            packagedirs="$optarg" ; reexec="$reexec --packagedirs=\"$optarg\"" ;;
+        --packagedir | --packagedi | --packaged | --d | -d)
+            prevopt="$arg" ; prev=packagedir ;;
+        --packagedir=* | --packagedi=* | --packaged=* | --d=* | -d*)
+            packagedir="$optarg" ; reexec="$reexec --packagedir=\"$optarg\"" ;;
         --) # end of options
             more_options=no
             ;;
@@ -340,7 +350,7 @@ if test -n "$prev" ; then
 fi
 
 if test X"$show_version" = Xyes ; then
-    $echo "$progname:"' Version $Name:  $($Revision: 0.9.2.31 $) $Date: 2006/03/09 14:01:16 $'
+    $echo "$progname:"' Version $Name:  $($Revision: 0.9.2.32 $) $Date: 2006/03/10 02:57:38 $'
 fi
 
 if test X"$show_help" = Xyes ; then
@@ -393,15 +403,15 @@ Options:
     -g, --pkgobject=[PKGOBJECT]
         full path and filename of object file to package
         [default: $default_pkgobject]
-    -d, --packagedirs=[PACKAGEDIR[,PACKAGEDIR]]
-        full path to source and binary package directory
+    -d, --packagedir=[PACKAGEDIR]
+        full path or vpath to binary package directory
         [default: $default_packagedir]
 EOF
     exit 0
 fi
 
 if test "x$nonopt" != "x"; then
-    infile="$nonopt ${1+$@}"
+    infile="$nonopt${1+ $@}"
     reexec="$reexec $infile"
 else
     # reading standard input
@@ -476,7 +486,8 @@ idnumber=1
 lineno=0
 set noglob
 qlock_encountered=no
-cat $infile | (
+if test -n "$infile" ; then exec 0<$infile ; fi
+filename="$infile"
 while read -a tokens
 do
     ((lineno++))
@@ -484,6 +495,10 @@ do
         continue
     fi
     case ":${tokens[0]}" in
+        (:file)
+            # new keyword indicating the file that the configuration came from
+            filename="${tokens[1]}"
+            ;;
         (:driver)
             token=`$echo -n ${tokens[1]} | $strconf_tokenize`
             eval "otherno=\"\$strconf_driver_lineno_$token\""
@@ -533,6 +548,7 @@ do
             eval "strconf_driver_lineno_$token=\"\$lineno\""
             eval "strconf_driver_$token='${tokens[*]}'"
             strconf_driver_names="$strconf_driver_names $token"
+            eval "strconf_filename_$token='$filename'"
             eval "strconf_realname_$token='${tokens[1]}'"
             eval "strconf_prefix_$token='${tokens[2]}'"
             eval "strconf_major_$token=$major"
@@ -549,7 +565,7 @@ do
             esac
             ((imajor+=nmajors))
             ;;
-        :module)
+        (:module)
             token=`$echo -n ${tokens[1]} | $strconf_tokenize`
             eval "otherno=\"\$strconf_module_lineno_$token\""
             if test -n "$otherno" ; then
@@ -559,12 +575,13 @@ do
             eval "strconf_module_lineno_$token=\"\$lineno\""
             eval "strconf_module_$token='${tokens[*]}'"
             strconf_module_names="$strconf_module_names $token"
+            eval "strconf_filename_$token='$filename'"
             eval "strconf_realname_$token='${tokens[1]}'"
             eval "strconf_prefix_$token='${tokens[2]}'"
             eval "strconf_id_$token=$idnumber"
             ((idnumber++))
             ;;
-        :objname)
+        (:objname)
             case ":${tokens[1]}" in
                 :driver)
                     token=`$echo -n ${tokens[2]} | $strconf_tokenize`
@@ -602,7 +619,7 @@ do
                     ;;
             esac
             ;;
-        :autopush)
+        (:autopush)
             token=`$echo -n ${tokens[1]} | $strconf_tokenize`
 #            eval "otherno=\"\$strconf_autopush_lineno_$token\""
 #            if test -n "$otherno" ; then
@@ -619,7 +636,7 @@ ${tokens[9]} ${tokens[10]} ${tokens[11]} ${tokens[12]} ${tokens[13]} \
 ${tokens[14]} ${tokens[15]} ${tokens[16]} ${tokens[17]} ${tokens[18]} \
 ${tokens[19]}'"
             ;;
-        :loadable)
+        (:loadable)
             token=`$echo -n ${tokens[1]} | $strconf_tokenize`
             eval "otherno=\"\$strconf_loadable_lineno_$token\""
             if test -n "$otherno" ; then
@@ -629,7 +646,7 @@ ${tokens[19]}'"
             eval "strconf_loadable_lineno_$token=\"\$lineno\""
             eval "strconf_loadable_$token='yes'"
             ;;
-        :initialize)
+        (:initialize)
             token=`$echo -n ${tokens[1]} | $strconf_tokenize`
             eval "otherno=\"\$strconf_initialize_lineno_$token\""
             if test -n "$otherno" ; then
@@ -639,7 +656,7 @@ ${tokens[19]}'"
             eval "strconf_initialize_lineno_$token=\"\$lineno\""
             eval "strconf_initialize_$token='yes'"
             ;;
-        :terminate)
+        (:terminate)
             token=`$echo -n ${tokens[1]} | $strconf_tokenize`
             eval "otherno=\"\$strconf_terminate_lineno_$token\""
             if test -n "$otherno" ; then
@@ -649,7 +666,7 @@ ${tokens[19]}'"
             eval "strconf_terminate_lineno_$token=\"\$lineno\""
             eval "strconf_terminate_$token='yes'"
             ;;
-        :node)
+        (:node)
             token=`$echo -n ${tokens[1]} | $strconf_tokenize`
             eval "otherno=\"\$strconf_node_lineno_$token\""
             if test -n "$otherno" ; then
@@ -671,7 +688,7 @@ ${tokens[19]}'"
             eval "strconf_minname_$token='${minorname}'"
             strconf_node_names="$strconf_node_names $token"
             ;;
-        :device)
+        (:device)
             token=`$echo -n ${tokens[1]} | $strconf_tokenize`
             eval "otherno=\"\$strconf_device_lineno_$token\""
             if test -n "$otherno" ; then
@@ -681,7 +698,7 @@ ${tokens[19]}'"
             eval "strconf_device_lineno_$token=\"\$lineno\""
             eval "strconf_device_$token='${tokens[*]}'"
             ;;
-        :qlock)
+        (:qlock)
             case ":${tokens[1]}" in
                 (:driver|:module) ;;
                 (:*) $echo "$progname: syntax error ${infile:-(stdin)} +$lineno : unknown object type \`${tokens[1]}'" >&2
@@ -2214,16 +2231,36 @@ fi
 #
 #   Generate package object wrappers and make rules as required
 #
-if test -n "$packagedirs"
+if test -n "$packagedir"
 then
-    pkgdirs=(`$echo $packagedirs | sed -e 's|,| |g'`)
-    for dir in ${pkgdirs[*]} ; do
-        if test ! -d $dir ; then
-            $echo "$progname: error: directory \"$dir\" does not exit" >&2
-            exit 1
-        fi
-    done
+    if test ! -d $packagedir ; then
+        $echo "$progname: error: directory \"$packagedir\" does not exit" >&2
+        exit 1
+    fi
+    case $packagedir in
+        (.*|/*) # non-vpath
+        pkgdirs=("$packagedir");
+        ;;
+        (*)
+        pkgdirs=("$builddir/$packagedir" "$srcdir/$packagedir");
+        ;;
+    esac
     for object in $strconf_drv_objnames ; do
+        objname=`$echo -n $object | $strconf_tokenize`
+        eval "file=\"\$strconf_filename_$objname\""
+        skip='yes'
+        for dir in ${pkgdirs[*]} ; do
+            if test -n "$file" ; then
+                case $file in
+                    ("$dir"*)
+                    skip='no'
+                    break
+                    ;;
+                esac
+            fi
+        done
+        # skip objects not configured in a package directory or subdirectory
+        test ":$skip" = ":yes" && continue
         found='no'
         for dir in ${pkgdirs[*]} ; do
             if test -f "$dir/$object.o" ; then
@@ -2238,6 +2275,21 @@ then
         fi
     done
     for object in $strconf_mod_objnames ; do
+        objname=`$echo -n $object | $strconf_tokenize`
+        eval "file=\"\$strconf_filename_$objname\""
+        skip='yes'
+        for dir in ${pkgdirs[*]} ; do
+            if test -n "$file" ; then
+                case $file in
+                    ("$dir"*)
+                    skip='no'
+                    break
+                    ;;
+                esac
+            fi
+        done
+        # skip objects not configured in a package directory or subdirectory
+        test ":$skip" = ":yes" && continue
         found='no'
         for dir in ${pkgdirs[*]} ; do
             if test -f "$dir/$object.o" ; then
@@ -2271,6 +2323,7 @@ then
             ;;
         esac
         pkgwrapper="${pkgdirs[0]}/${object}_wrapper.c"
+        $echo "$progname: generating $pkgwrapper from ${infile:-(stdin)}" >&1
         objname=`$echo -n $object | $strconf_tokenize`
         eval "loadable=\"\$strconf_loadable_$objname\""
         if test :"$loadable" = :yes ; then linkdef=0 ; else linkdef=1 ; fi
@@ -2502,6 +2555,5 @@ module_exit(_xx_exit);
 EOF
     done
 fi
-)
 
 # vim: ft=sh sw=4 et nocin nosi
